<!DOCTYPE html>
<html lang="en"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/quarto-contrib/live-runtime/live-runtime.js" type="module"></script>
<link href="../site_libs/quarto-contrib/live-runtime/live-runtime.css" rel="stylesheet"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.25">

  <meta name="author" content="Imron Rosyadi">
  <title>Physics</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-b0356e9119c1bdfd0db189d130feb51c.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <script type="module" src="../site_libs/quarto-ojs/quarto-ojs-runtime.js"></script>
  <link href="../site_libs/quarto-ojs/quarto-ojs.css" rel="stylesheet">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Physics</h1>
  <p class="subtitle">Chapter 1: The Nature of Light</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Imron Rosyadi 
</div>
</div>
</div>

</section>
<section id="chapter-1-the-nature-of-light" class="slide level2">
<h2>Chapter 1: The Nature of Light</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>Learning Objectives</strong></p>
<p>By the end of this chapter, you will be able to:</p>
<ul>
<li>Understand how light propagates and interacts with different media.</li>
<li>Explain the principles of reflection, refraction, and total internal reflection.</li>
<li>Describe the phenomena of dispersion, Huygens’s principle, and polarization.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="the-propagation-of-light" class="slide level2">
<h2>1.1 The Propagation of Light</h2>
<ul>
<li>Light travels at a finite speed, <code>c</code>, in a vacuum.</li>
<li>This speed is one of physics’ fundamental constants: <span class="math inline">\(c = 2.99792458 \times 10^8 \text{ m/s} \approx 3.00 \times 10^8 \text{ m/s}\)</span>.</li>
<li>Light’s speed changes in different materials.</li>
</ul>
<aside class="notes">
<p>In this section, we’ll explore how light travels and how its speed is measured.</p>
<p>We’ll also introduce the concept of the index of refraction.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="early-measurements-of-light-speed" class="slide level2">
<h2>Early Measurements of Light Speed</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Ole Roemer (1675)</strong></p>
<ul>
<li>Studied Io, a moon of Jupiter.</li>
<li>Noticed fluctuations in Io’s eclipse period depending on Earth’s position.</li>
<li>Calculated <span class="math inline">\(c \approx 2.0 \times 10^8 \text{ m/s}\)</span> (33% below accepted value).</li>
</ul>
</div><div class="column" style="width:50%;">
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/8db6a3fce634f035cf643c891d7c881af6309c54" height="300"></p>
<p><em>Figure 1.2: Roemer’s method to determine the speed of light.</em></p>
</div></div>
<aside class="notes">
<p>Roemer’s observation was groundbreaking. The changing distance between Earth and Jupiter caused delays in observing Io’s eclipses, directly related to the finite speed of light. Although his value was approximate, it was the first quantitative estimate.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="terrestrial-measurements" class="slide level2">
<h2>Terrestrial Measurements</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Armand Fizeau (1849)</strong></p>
<ul>
<li>First successful terrestrial measurement.</li>
<li>Used a rapidly rotating toothed wheel and a mirror 8 km away.</li>
<li>Measured <span class="math inline">\(c \approx 3.15 \times 10^8 \text{ m/s}\)</span> (5% too high).</li>
</ul>
</div><div class="column" style="width:50%;">
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/0f1e16f5407a195d0e5840264f6056d83e16abad" height="300"></p>
<p><em>Figure 1.3: Fizeau’s method for measuring the speed of light.</em></p>
</div></div>
<aside class="notes">
<p>Fizeau’s method was ingenious, using mechanical means to chop light into pulses and measure their travel time over a known distance. This was a significant step as it didn’t rely on astronomical observations.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="modern-measurements" class="slide level2">
<h2>Modern Measurements</h2>
<ul>
<li><strong>Jean Bernard Léon Foucault (1862):</strong> Modified Fizeau’s method with a rotating mirror.
<ul>
<li>Measured <span class="math inline">\(c \approx 2.98 \times 10^8 \text{ m/s}\)</span> (within 0.6% of accepted value).</li>
</ul></li>
<li><strong>Albert Michelson (1878-1926):</strong> Refined Foucault’s technique.
<ul>
<li>Achieved (2.99796 ± 4) <span class="math inline">\(\times 10^8 \text{ m/s}\)</span>.</li>
</ul></li>
<li><strong>Present Day:</strong> The speed of light in a vacuum is defined as <span class="math display">\[ c = 2.99792458 \times 10^8 \text{ m/s} \]</span> Approximately <span class="math inline">\(3.00 \times 10^8 \text{ m/s}\)</span> for typical calculations.</li>
</ul>
<aside class="notes">
<p>Foucault’s and Michelson’s work greatly improved the precision of light speed measurements, demonstrating the incredible consistency of this fundamental constant. The modern definition of ‘c’ is now exact, and the meter is defined based on it.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="speed-of-light-in-matter-index-of-refraction" class="slide level2">
<h2>Speed of Light in Matter: Index of Refraction</h2>
<ul>
<li>Light travels slower in matter than in a vacuum.</li>
<li>This reduced speed is described by the <strong>index of refraction</strong> (<em>n</em>). <span class="math display">\[ n = \frac{c}{v} \]</span> where <em>v</em> is the speed of light in the material.</li>
<li>Since <span class="math inline">\(v \le c\)</span>, then <span class="math inline">\(n \ge 1\)</span>.</li>
<li><em>n</em> varies slightly with the wavelength of light.</li>
</ul>
<aside class="notes">
<p>The index of refraction is a crucial property of a material, telling us how much the speed of light is reduced within it. This change in speed is responsible for many optical phenomena, including refraction itself.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="index-of-refraction-in-various-media" class="slide level2">
<h2>Index of Refraction in Various Media</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Medium</th>
<th><em>n</em></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Air (0°C, 1 atm)</td>
<td>1.000293</td>
</tr>
<tr class="even">
<td>Water, fresh (20°C)</td>
<td>1.333</td>
</tr>
<tr class="odd">
<td>Glass, crown (20°C)</td>
<td>1.52</td>
</tr>
<tr class="even">
<td>Diamond (20°C)</td>
<td>2.419</td>
</tr>
</tbody>
</table>
<p><em>Table 1.1: Representative indices of refraction for light with wavelength 589 nm.</em></p>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>For gases, <em>n</em> is very close to 1.0, meaning light travels almost as fast as in a vacuum.</p>
</div>
</div>
</div>
<aside class="notes">
<p>Notice how dramatically the index of refraction can vary, especially for materials like diamond. This difference in ‘n’ is what makes diamonds sparkle. The slight variation with wavelength, though not always significant, is key to understanding dispersion.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="example-speed-of-light-in-zircon" class="slide level2">
<h2>Example: Speed of Light in Zircon</h2>
<p><strong>Question:</strong> Calculate the speed of light in zircon, which has an index of refraction of 1.923.</p>
<p><strong>Strategy:</strong></p>
<p>Use the definition of the index of refraction: <span class="math inline">\(n = c/v\)</span>.</p>
<p>Rearrange to solve for <span class="math inline">\(v\)</span>: <span class="math inline">\(v = c/n\)</span>.</p>
<p><strong>Solution:</strong> Given <span class="math inline">\(c = 3.00 \times 10^8 \text{ m/s}\)</span> and <span class="math inline">\(n = 1.923\)</span>. <span class="math display">\[ v = \frac{3.00 \times 10^8 \text{ m/s}}{1.923} \approx 1.56 \times 10^8 \text{ m/s} \]</span></p>
<p><strong>Significance:</strong> The speed of light in zircon is about half its speed in a vacuum.</p>
<aside class="notes">
<p>This calculation demonstrates the direct relationship between the index of refraction and the speed of light in a medium. A higher index means a slower speed.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-ray-model-of-light" class="slide level2 scrollable">
<h2>The Ray Model of Light</h2>
<ul>
<li>Light travels in straight lines called <strong>rays</strong>.</li>
<li>This model is valid when light interacts with objects much larger than its wavelength (e.g., visible light and objects &gt; 1 micron).</li>
<li><strong>Geometric optics</strong> studies light propagation using the ray model.</li>
<li>Light changes direction when:
<ol type="1">
<li>Reflected from a surface (e.g., a mirror).</li>
<li>Refracted when passing from one material to another (e.g., air to glass).</li>
</ol></li>
</ul>
<aside class="notes">
<p>The ray model simplifies the study of light by treating it as straight lines, which makes many optical phenomena understandable through geometry. This is applicable in everyday situations where objects are much larger than light’s wavelength.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="how-light-travels" class="slide level2 scrollable">
<h2>How Light Travels</h2>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/63f7a057b488b1f1e2964deebf1aaa3809ba18d0" height="400"></p>
<p><em>Figure 1.4: Three methods for light to travel from a source to another location.</em></p>
<aside class="notes">
<ol type="a">
<li>Direct travel through empty space, like sunlight to Earth.</li>
<li>Travel through media, like light through a window to an observer.</li>
<li>Reflection from an object, like light off a mirror. In all these cases, the ray model applies, showing light interacting with objects much larger than its wavelength.</li>
</ol>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-law-of-reflection" class="slide level2">
<h2>1.2 The Law of Reflection</h2>
<ul>
<li>When light strikes a surface, it bounces off according to the <strong>law of reflection</strong>.</li>
<li>The angle of reflection (<span class="math inline">\(\theta_r\)</span>) equals the angle of incidence (<span class="math inline">\(\theta_i\)</span>). <span class="math display">\[ \theta_r = \theta_i \]</span></li>
<li>Angles are measured relative to the <strong>normal</strong> (perpendicular line) to the surface.</li>
</ul>
<aside class="notes">
<p>The law of reflection is fundamental to understanding how mirrors work and how light interacts with surfaces. It’s a simple yet powerful rule that governs phenomena from seeing your image in a mirror to how telescopes collect light.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="specular-vs.-diffuse-reflection" class="slide level2">
<h2>Specular vs.&nbsp;Diffuse Reflection</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Smooth Surfaces (Specular Reflection)</strong></p>
<ul>
<li>Reflect light at specific angles.</li>
<li>Form clear images (e.g., mirrors, still water).</li>
</ul>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/2ec40e79fe8ab79809acd7d60b527f258a0ea32b" height="200"></p>
<p><em>Figure 1.5: Specular reflection from a smooth surface.</em></p>
</div><div class="column" style="width:50%;">
<p><strong>Rough Surfaces (Diffuse Reflection)</strong></p>
<ul>
<li>Scatter light in many directions.</li>
<li>Allow objects to be seen from any angle (e.g., paper, clothing).</li>
</ul>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/f4ba0bd48f4798cf410fe1303143651464524373" height="200"></p>
<p><em>Figure 1.6: Diffuse reflection from a rough surface.</em></p>
</div></div>
<aside class="notes">
<p>The nature of the surface dictates whether reflection is specular or diffuse. Specular reflection is like a well-organized march, while diffuse reflection is like a crowd dispersing in all directions. Both are governed by the law of reflection at the microscopic level, but the macroscopic appearance differs due to the surface’s texture relative to the light’s wavelength.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="images-from-mirrors" class="slide level2">
<h2>Images from Mirrors</h2>
<ul>
<li>Mirror images appear to be behind the mirror.</li>
<li>The image distance behind the mirror is equal to the object distance in front.</li>
<li>These images are not optical illusions; they can be captured by cameras.</li>
<li>This phenomenon makes rooms appear larger.</li>
</ul>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/6ce3caa63450479cce23cbb3aa69877fa941daeb" height="350"></p>
<p><em>Figure 1.8: Your image in a mirror appears behind it, at the same distance as you are in front.</em></p>
<aside class="notes">
<p>The formation of images by mirrors is a core concept in geometric optics. The light rays obey the law of reflection, and our brains interpret these reflected rays as originating from a point behind the mirror. This is how virtual images are formed.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="corner-reflectors-retroreflectors" class="slide level2">
<h2>Corner Reflectors (Retroreflectors)</h2>
<ul>
<li>An object with two (or three) mutually perpendicular reflecting surfaces.</li>
<li>Reflects incoming light rays back <strong>exactly parallel</strong> to their original direction.</li>
<li>Independent of the angle of incidence.</li>
</ul>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/5c51b6098a70a1ba72581c8058820aabe32e715b" height="300"></p>
<p><em>Figure 1.9: A light ray striking two perpendicular mirrors is reflected back parallel to its incident direction.</em></p>
<aside class="notes">
<p>Corner reflectors are incredibly useful because they return light directly to its source. This property is due to successive reflections off perpendicular surfaces.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="applications-of-corner-reflectors" class="slide level2">
<h2>Applications of Corner Reflectors</h2>
<ul>
<li><strong>Bicycle/Car Reflectors:</strong> Enhance visibility for drivers.</li>
<li><strong>Apollo Moon Reflectors:</strong> Used by astronauts to measure the Earth-Moon distance with lasers.</li>
<li><strong>Radar Reflectors:</strong> Make small boats visible to radar systems, preventing collisions.</li>
</ul>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/1fb808cd9e8c123533b93d8e4261392d2320d687" height="300"></p>
<p><em>Figure 1.10: (a) Astronaut placing a corner reflector on the Moon. (b) Bicycle safety reflectors.</em></p>
<aside class="notes">
<p>The versatility of corner reflectors is evident in their wide range of applications, from everyday safety items to advanced scientific instruments. Their ability to return light to the source makes them highly effective in situations where visibility or precise distance measurement is critical.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="refraction" class="slide level2">
<h2>1.3 Refraction</h2>
<ul>
<li><strong>Refraction</strong> is the bending of light as it passes from one medium to another.</li>
<li>Caused by a change in the speed of light (<span class="math inline">\(v = c/n\)</span>).</li>
<li>Responsible for phenomena like lenses, optical fibers, and apparent distortions in water.</li>
</ul>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/98e9512239011823a8390ec7b61070a63e24bcaf" height="350"></p>
<p><em>Figure 1.12: Fish appearing in two places due to refraction.</em></p>
<aside class="notes">
<p>Refraction is one of the most common optical phenomena we encounter. Think about a straw in a glass of water appearing bent, or how eyeglasses correct vision. The underlying cause is the change in the speed of light as it crosses the boundary between different materials, which in turn changes its direction.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="direction-of-refraction" class="slide level2">
<h2>Direction of Refraction</h2>
<ul>
<li>When light enters a medium with a <strong>higher index of refraction</strong> (slowing down), it bends <strong>towards the normal</strong>.</li>
<li>When light enters a medium with a <strong>lower index of refraction</strong> (speeding up), it bends <strong>away from the normal</strong>.</li>
<li>The path of light is reversible.</li>
</ul>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/8b259bce8f845c00c3558701727c0446ffa2fbcb" height="350"></p>
<p><em>Figure 1.13: Light bending (a) towards the normal (<span class="math inline">\(n_2 &gt; n_1\)</span>) and (b) away from the normal (<span class="math inline">\(n_2 &lt; n_1\)</span>).</em></p>
<aside class="notes">
<p>It’s important to remember these rules for bending. Imagine light as a car. If one wheel hits a patch of mud (slower medium) before the other, the car will turn. The same principle applies to light waves entering a new medium at an angle.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="snells-law-law-of-refraction" class="slide level2">
<h2>Snell’s Law (Law of Refraction)</h2>
<ul>
<li>Describes the quantitative relationship between angles and indices of refraction. <span class="math display">\[ n_1 \sin \theta_1 = n_2 \sin \theta_2 \]</span>
<ul>
<li><span class="math inline">\(n_1, n_2\)</span>: indices of refraction for medium 1 and 2.</li>
<li><span class="math inline">\(\theta_1\)</span>: incident angle (in medium 1).</li>
<li><span class="math inline">\(\theta_2\)</span>: refracted angle (in medium 2).</li>
</ul></li>
</ul>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Discovered by Willebrord Snell in 1621, and earlier by Ibn Sahl in 984.</p>
</div>
</div>
</div>
<aside class="notes">
<p>Snell’s Law is a cornerstone of geometric optics, allowing us to precisely calculate how much light will bend when it passes between different media. It connects the angles of incidence and refraction with the properties of the materials themselves.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="example-determining-the-index-of-refraction" class="slide level2">
<h2>Example: Determining the Index of Refraction</h2>
<p><strong>Question:</strong> Light goes from air (medium 1) into an unknown medium (medium 2). If the incident angle is <span class="math inline">\(30.0^\circ\)</span> and the refracted angle is <span class="math inline">\(22.0^\circ\)</span>, find <span class="math inline">\(n_2\)</span>.</p>
<p><strong>Strategy:</strong></p>
<p>Use Snell’s law: <span class="math inline">\(n_1 \sin \theta_1 = n_2 \sin \theta_2\)</span>.</p>
<p>Given <span class="math inline">\(n_1 = 1.00\)</span> (air), <span class="math inline">\(\theta_1 = 30.0^\circ\)</span>, <span class="math inline">\(\theta_2 = 22.0^\circ\)</span>.</p>
<p>Solve for <span class="math inline">\(n_2\)</span>.</p>
<p><strong>Solution:</strong></p>
<p><span class="math display">\[ n_2 = \frac{n_1 \sin \theta_1}{\sin \theta_2} = \frac{(1.00) \sin 30.0^\circ}{\sin 22.0^\circ} = \frac{0.500}{0.375} \approx 1.33 \]</span></p>
<p><strong>Significance:</strong></p>
<p>This value, <span class="math inline">\(n_2 = 1.33\)</span>, is the index of refraction for water.</p>
<aside class="notes">
<p>This example shows how Snell’s law can be used to identify an unknown material by measuring the bending of light. It highlights the practical application of the law.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="example-a-larger-change-in-direction" class="slide level2">
<h2>Example: A Larger Change in Direction</h2>
<p><strong>Question:</strong> If light goes from air to diamond with an incident angle of <span class="math inline">\(30.0^\circ\)</span>, calculate the refracted angle (<span class="math inline">\(\theta_2\)</span>).</p>
<p><strong>Strategy:</strong></p>
<p>Use Snell’s law: <span class="math inline">\(n_1 \sin \theta_1 = n_2 \sin \theta_2\)</span>.</p>
<p>Given <span class="math inline">\(n_1 = 1.00\)</span> (air), <span class="math inline">\(\theta_1 = 30.0^\circ\)</span>.</p>
<p>Look up <span class="math inline">\(n_2 = 2.419\)</span> for diamond (from Table 1.1).</p>
<p>Solve for <span class="math inline">\(\theta_2\)</span>.</p>
<p><strong>Solution:</strong></p>
<p><span class="math display">\[ \sin \theta_2 = \frac{n_1 \sin \theta_1}{n_2} = \frac{(1.00) \sin 30.0^\circ}{2.419} = \frac{0.500}{2.419} \approx 0.207 \]</span></p>
<p><span class="math display">\[ \theta_2 = \sin^{-1}(0.207) \approx 11.9^\circ \]</span></p>
<p><strong>Significance:</strong></p>
<p>Diamond causes a much larger change in direction (<span class="math inline">\(11.9^\circ\)</span> vs.&nbsp;<span class="math inline">\(22.0^\circ\)</span> for water) due to its significantly higher index of refraction.</p>
<aside class="notes">
<p>This example reinforces that a greater difference in refractive indices leads to a more pronounced bending of light. This large bending effect in diamond is one reason for its famous sparkle.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="total-internal-reflection" class="slide level2">
<h2>1.4 Total Internal Reflection</h2>
<ul>
<li>Occurs when light travels from a medium with a <strong>higher index of refraction</strong> to one with a <strong>lower index of refraction</strong> (<span class="math inline">\(n_1 &gt; n_2\)</span>).</li>
<li>If the incident angle (<span class="math inline">\(\theta_1\)</span>) exceeds a certain <strong>critical angle</strong> (<span class="math inline">\(\theta_c\)</span>), all light is reflected back into the first medium.</li>
<li>No light is refracted into the second medium.</li>
<li>The reflected light still obeys the law of reflection (<span class="math inline">\(\theta_r = \theta_1\)</span>).</li>
</ul>
<aside class="notes">
<p>Total internal reflection is a fascinating phenomenon where a “perfect mirror” effect is achieved without any metallic coating. It only happens under specific conditions, primarily when light tries to move from a denser medium to a less dense one at a sufficiently steep angle.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="critical-angle-theta_c" class="slide level2">
<h2>Critical Angle (<span class="math inline">\(\theta_c\)</span>)</h2>
<ul>
<li><p>The incident angle at which the angle of refraction is <span class="math inline">\(90^\circ\)</span>.</p></li>
<li><p>Using Snell’s Law (<span class="math inline">\(n_1 \sin \theta_1 = n_2 \sin \theta_2\)</span>), with <span class="math inline">\(\theta_1 = \theta_c\)</span> and <span class="math inline">\(\theta_2 = 90^\circ\)</span>:</p>
<p><span class="math display">\[ n_1 \sin \theta_c = n_2 \sin 90^\circ \]</span></p>
<p><span class="math display">\[ n_1 \sin \theta_c = n_2 \]</span></p></li>
<li><p>Therefore, the critical angle is:</p>
<p><span class="math display">\[ \theta_c = \sin^{-1} \left( \frac{n_2}{n_1} \right) \quad \text{for } n_1 &gt; n_2 \]</span></p></li>
</ul>
<aside class="notes">
<p>The critical angle is a threshold. Below this angle, both reflection and refraction occur. At the critical angle, the refracted ray skims along the surface. Beyond the critical angle, only total internal reflection occurs.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="total-internal-reflection-diagram" class="slide level2">
<h2>Total Internal Reflection Diagram</h2>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/04ec0eee011cdb2ef56e5cd841f274fb0c0cdc25" height="400"></p>
<p><em>Figure 1.14: (a) Refraction and reflection. (b) Critical angle, <span class="math inline">\(\theta_c\)</span>. (c) Total internal reflection.</em></p>
<aside class="notes">
<p>Observe how the refracted ray moves further from the normal as the incident angle increases (a). At the critical angle (b), the refracted ray is parallel to the surface. Beyond that (c), all light is reflected internally.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="example-critical-angle-for-polystyrene" class="slide level2">
<h2>Example: Critical Angle for Polystyrene</h2>
<p><strong>Question:</strong> What is the critical angle for light traveling in a polystyrene pipe (<span class="math inline">\(n_1 = 1.49\)</span>) surrounded by air (<span class="math inline">\(n_2 = 1.00\)</span>)?</p>
<p><strong>Strategy:</strong></p>
<p>Confirm <span class="math inline">\(n_1 &gt; n_2\)</span>.</p>
<p>Use the critical angle formula: <span class="math inline">\(\theta_c = \sin^{-1} \left( \frac{n_2}{n_1} \right)\)</span>.</p>
<p><strong>Solution:</strong></p>
<p><span class="math display">\[ \theta_c = \sin^{-1} \left( \frac{1.00}{1.49} \right) = \sin^{-1}(0.671) \approx 42.2^\circ \]</span></p>
<p><strong>Significance:</strong></p>
<p>Any light ray inside the plastic hitting the surface at an angle greater than <span class="math inline">\(42.2^\circ\)</span> will be totally reflected, effectively turning the inside surface into a perfect mirror.</p>
<aside class="notes">
<p>This calculation demonstrates why clear plastic can act as a mirror under certain conditions, a principle central to fiber optics. The critical angle is specific to the pair of materials involved.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="fiber-optics" class="slide level2">
<h2>Fiber Optics</h2>
<ul>
<li>A key application of total internal reflection.</li>
<li>Light is transmitted down thin fibers of plastic or glass.</li>
<li>Light strikes the inner surface at an angle greater than <span class="math inline">\(\theta_c\)</span>, leading to continuous internal reflection.</li>
<li>Fibers have a core (higher <em>n</em>) and cladding (lower <em>n</em>) to ensure reflection.</li>
</ul>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/ae2be39cfc304402b5e19cda3d91bcb921c377e8" height="300"></p>
<p><em>Figure 1.15: Light guided down an optical fiber by total internal reflection.</em></p>
<aside class="notes">
<p>Fiber optics has revolutionized communication and medicine. The ability to guide light efficiently over long distances or around corners is due entirely to total internal reflection. The cladding prevents light from leaking between fibers.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="applications-of-fiber-optics" class="slide level2">
<h2>Applications of Fiber Optics</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Medical Endoscopes</strong></p>
<ul>
<li>Explore body interiors without major surgery.</li>
<li>Transmit light in, return images out.</li>
<li>Used for diagnostics and microsurgery.</li>
</ul>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/6b0b3d76916fabd75be8834fbe1de21bcaffadf3" height="200"></p>
<p><em>Figure 1.16: (a) Image transmission through optical fibers. (b) Endoscope image.</em></p>
</div><div class="column" style="width:50%;">
<p><strong>Telecommunications</strong></p>
<ul>
<li>Transmit telephone, internet, and cable TV signals.</li>
<li>Advantages:
<ul>
<li><strong>Low loss:</strong> Light travels far without amplification.</li>
<li><strong>High bandwidth:</strong> More data per fiber.</li>
<li><strong>Reduced crosstalk:</strong> Signals don’t interfere.</li>
</ul></li>
</ul>
</div></div>
<aside class="notes">
<p>The impact of fiber optics is immense. In medicine, it allows for minimally invasive procedures. In communications, it forms the backbone of the internet, enabling rapid and efficient data transfer across continents.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="diamonds-and-total-internal-reflection" class="slide level2">
<h2>Diamonds and Total Internal Reflection</h2>
<ul>
<li>Diamonds sparkle due to total internal reflection and high index of refraction (<span class="math inline">\(n_{diamond} = 2.419\)</span>).</li>
<li>Critical angle for diamond to air is very small: <span class="math inline">\(\theta_c = \sin^{-1}(1.00/2.419) \approx 24.4^\circ\)</span>.</li>
<li>Light entering a diamond has trouble getting back out.</li>
<li>Facets are cut to ensure multiple internal reflections, concentrating light before it exits.</li>
</ul>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/aaec0d0945978dfbbb9aab0341b5661fdb290da5" height="300"></p>
<p><em>Figure 1.19: Light trapped inside a diamond by total internal reflection, creating sparkle.</em></p>
<aside class="notes">
<p>The small critical angle of diamond means that most light that enters it will undergo multiple internal reflections before exiting, which creates the brilliant sparkle we associate with diamonds. This is why diamond cutting is such a precise art, aimed at maximizing these internal reflections.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="dispersion" class="slide level2">
<h2>1.5 Dispersion</h2>
<ul>
<li><strong>Dispersion</strong> is the spreading of white light into its full spectrum of wavelengths (colors).</li>
<li>Occurs because the index of refraction (<em>n</em>) for a given medium depends slightly on wavelength.</li>
<li>Shorter wavelengths (e.g., violet) have a higher <em>n</em> and bend more than longer wavelengths (e.g., red).</li>
</ul>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/c6501c17d8787d1b8b87cd7a53d1d2b17fb156d7" height="350"></p>
<p><em>Figure 1.20: Rainbow (a) and light dispersed by a prism (b) show the same spectrum of colors.</em></p>
<aside class="notes">
<p>Dispersion is the reason we see rainbows and why prisms split white light into its constituent colors. The subtle variation of refractive index with wavelength, known as anomalous dispersion, is critical to this phenomenon.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="wavelength-and-color" class="slide level2">
<h2>Wavelength and Color</h2>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/a6ccb37f8d63d3350fd9863895915cf71fd1abc6" height="300"></p>
<p><em>Figure 1.21: The visible light spectrum, showing colors associated with different wavelengths.</em></p>
<aside class="notes">
<p>This spectrum illustrates the continuous nature of colors in visible light, ordered by wavelength. Red has the longest wavelength, and violet has the shortest.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="dispersion-by-a-prism" class="slide level2">
<h2>Dispersion by a Prism</h2>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/bd9f61d63d44e79973cbd52bcc6a3363a154ea5e" height="350"></p>
<p><em>Figure 1.22: (a) A single wavelength refracted by a prism. (b) White light dispersed by a prism.</em></p>
<aside class="notes">
<p>As white light enters the prism, each wavelength is refracted at a slightly different angle due to its unique index of refraction in the glass. This separates the colors, with violet bending most and red bending least, producing the spectrum.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="example-dispersion-by-crown-glass" class="slide level2 scrollable">
<h2>Example: Dispersion by Crown Glass</h2>
<p><strong>Question:</strong> A beam of white light enters crown glass from air at an incidence angle of <span class="math inline">\(43.2^\circ\)</span>. What is the angle between the red (660 nm) and violet (410 nm) parts of the refracted light?</p>
<p><strong>Strategy:</strong></p>
<ol type="1">
<li>Find <span class="math inline">\(n\)</span> for red and violet light in crown glass from Table 1.2.
<ul>
<li><span class="math inline">\(n_{red} = 1.512\)</span></li>
<li><span class="math inline">\(n_{violet} = 1.530\)</span></li>
</ul></li>
<li>Use Snell’s Law (<span class="math inline">\(n_{air} \sin \theta_{air} = n \sin \theta\)</span>) to find <span class="math inline">\(\theta_{red}\)</span> and <span class="math inline">\(\theta_{violet}\)</span>.
<ul>
<li><span class="math inline">\(n_{air} = 1.000\)</span>, <span class="math inline">\(\theta_{air} = 43.2^\circ\)</span>.</li>
</ul></li>
<li>Calculate the difference: <span class="math inline">\(\Delta \theta = \theta_{red} - \theta_{violet}\)</span>.</li>
</ol>
<p><strong>Solution:</strong></p>
<p>For red light:</p>
<p><span class="math display">\[ \theta_{red} = \sin^{-1} \left( \frac{1.000 \sin 43.2^\circ}{1.512} \right) \approx 27.0^\circ \]</span></p>
<p>For violet light:</p>
<p><span class="math display">\[ \theta_{violet} = \sin^{-1} \left( \frac{1.000 \sin 43.2^\circ}{1.530} \right) \approx 26.4^\circ \]</span></p>
<p>Difference:</p>
<p><span class="math display">\[ \Delta \theta = 27.0^\circ - 26.4^\circ = 0.6^\circ \]</span></p>
<p><strong>Significance:</strong></p>
<p>Even a small angular separation can become noticeable over long distances.</p>
<aside class="notes">
<p>This calculation demonstrates how the small difference in the index of refraction for different wavelengths leads to measurable dispersion. This effect, though seemingly small here, is magnified in phenomena like rainbows.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="rainbows" class="slide level2">
<h2>Rainbows</h2>
<ul>
<li>Formed by a combination of refraction and total internal reflection in water droplets.</li>
<li>Light enters a drop, refracts, reflects from the back, and refracts again upon exiting.</li>
<li>Since water disperses light, each color exits at a slightly different angle.</li>
<li>Observer must look away from the Sun at a specific angle.</li>
</ul>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/29e9306888db9db61e64d1979b522725513902ff" height="300"></p>
<p><em>Figure 1.23: Light path in a water drop forming a rainbow.</em></p>
<aside class="notes">
<p>Rainbows are a beautiful natural display of dispersion. The specific geometry of light entering, reflecting within, and exiting the spherical water droplets is what creates the distinct arc of colors.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="primary-and-secondary-rainbows" class="slide level2 scrollable">
<h2>Primary and Secondary Rainbows</h2>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/edeec3343171a7a570915c1d0d4ef21c3b7ccd81" height="350"></p>
<p><em>Figure 1.24: (a) Different colors seen at different angles. (b) The arc of a rainbow. (c) A double rainbow.</em></p>
<aside class="notes">
<ol type="a">
<li>Shows that different colors reach the observer’s eye from different droplets. (b) Explains why rainbows are arcs – the specific angle relative to the sun. (c) A secondary rainbow is rarer and results from two internal reflections, with colors reversed compared to the primary.</li>
</ol>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="huygenss-principle" class="slide level2">
<h2>1.6 Huygens’s Principle</h2>
<ul>
<li>A method to determine how and where waves propagate.</li>
<li>States that every point on a wave front acts as a source of tiny, spherical <strong>wavelets</strong>.</li>
<li>These wavelets spread out in the forward direction at the same speed as the wave.</li>
<li>The <strong>new wave front</strong> is the surface tangent to all of these wavelets.</li>
</ul>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/dcbab4784e0280e35487921602b110b3168f7da2" height="250"></p>
<p><em>Figure 1.26: Huygens’s principle applied to a straight wave front.</em></p>
<aside class="notes">
<p>Christiaan Huygens’s principle is a powerful conceptual tool for understanding wave propagation, especially when dealing with reflection, refraction, and diffraction. It allows us to visualize how waves move forward from one point in time to the next.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="explaining-reflection-with-huygenss-principle" class="slide level2">
<h2>Explaining Reflection with Huygens’s Principle</h2>
<ul>
<li>When a wave front strikes a mirror, each point on the wave front emits wavelets.</li>
<li>Wavelets from points that hit the mirror first travel further.</li>
<li>The tangent to these wavelets forms the new reflected wave front.</li>
<li>This geometrically demonstrates that <span class="math inline">\(\theta_r = \theta_i\)</span>.</li>
</ul>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/092a9b5d22926a5e74272b6e830820cd0c6869ac" height="300"></p>
<p><em>Figure 1.27: Huygens’s principle explains the law of reflection.</em></p>
<aside class="notes">
<p>Huygens’s principle provides a beautiful and intuitive way to understand the law of reflection from a wave perspective, showing how the macroscopic behavior emerges from the microscopic propagation of wavelets.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="explaining-refraction-with-huygenss-principle" class="slide level2">
<h2>Explaining Refraction with Huygens’s Principle</h2>
<ul>
<li>When a wave front passes into a new medium, the speed of wavelets changes.</li>
<li>If speed decreases (higher <em>n</em>), wavelets travel less distance in the same time.</li>
<li>This causes the new wave front to change direction, bending towards the normal.</li>
<li>This derivation leads directly to Snell’s Law.</li>
</ul>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/a2abcf4d3a79f1458955e53dc78d221e545ebb56" height="300"></p>
<p><em>Figure 1.28: Huygens’s principle explains the law of refraction.</em></p>
<aside class="notes">
<p>Similarly, for refraction, Huygens’s principle reveals why light bends when changing media. The change in the speed of the wavelets in the new medium alters the direction of the overall wave front, providing a wave-based justification for Snell’s Law.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="diffraction" class="slide level2">
<h2>Diffraction</h2>
<ul>
<li><strong>Diffraction</strong> is the bending of waves around the edges of an opening or an obstacle.</li>
<li>It is a fundamental wave characteristic.</li>
<li>The amount of diffraction is most noticeable when the wavelength is comparable to the size of the opening/obstacle.</li>
</ul>
<div class="columns">
<div class="column" style="width:50%;">
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/b182b66aa22cfaa94c3abf3167e636b80cfdb7e3" height="250"></p>
<p><em>Figure 1.30: (a) Light acts like a ray. (b) Sound waves (larger wavelength) diffract.</em></p>
</div><div class="column" style="width:50%;">
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/fb9a00f9b4e16999d810bea0fe365e0f85346097" height="250"></p>
<p><em>Figure 1.31: Huygens’s principle illustrates diffraction through an opening.</em></p>
</div></div>
<aside class="notes">
<p>The contrasting behavior of light and sound passing through a doorway highlights the role of wavelength in diffraction. Since light’s wavelength is tiny, its diffraction is usually negligible unless it encounters very small openings, which is when its wave nature becomes evident.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="polarization" class="slide level2">
<h2>1.7 Polarization</h2>
<ul>
<li><strong>Polarization</strong> is the attribute that a wave’s oscillations have a definite direction relative to its propagation.</li>
<li>For electromagnetic (EM) waves, polarization refers to the direction of the electric field oscillations.</li>
<li><strong>Unpolarized light</strong> has electric fields oscillating in random directions.</li>
<li><strong>Polarized light</strong> has electric fields oscillating in a specific direction (e.g., vertical, horizontal).</li>
</ul>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/4fa977f9a5b2781017e0df0ff2ba7f3f3201cbd6" height="250"></p>
<p><em>Figure 1.33: Direction of polarization is the direction of the electric field.</em></p>
<aside class="notes">
<p>Polarization is a unique property of transverse waves like light. Unlike longitudinal waves, where oscillations are parallel to propagation, transverse waves can oscillate in different planes perpendicular to propagation. This difference is what polarization describes.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="polarizing-filters-and-maluss-law" class="slide level2">
<h2>Polarizing Filters and Malus’s Law</h2>
<ul>
<li><strong>Polaroid materials</strong> act as polarizing slits, allowing only light with a specific polarization direction to pass.</li>
<li>The <strong>polarization axis</strong> is the direction parallel to which the electric field passes.</li>
<li><strong>Malus’s Law:</strong> Describes the intensity of polarized light after passing through a polarizing filter. <span class="math display">\[ I = I_0 \cos^2 \theta \]</span>
<ul>
<li><span class="math inline">\(I_0\)</span>: incident polarized light intensity.</li>
<li><span class="math inline">\(I\)</span>: transmitted light intensity.</li>
<li><span class="math inline">\(\theta\)</span>: angle between the direction of polarization and the filter’s axis.</li>
</ul></li>
</ul>
<aside class="notes">
<p>Polarizing filters are made of long molecules aligned in one direction. They absorb electric field components parallel to the molecules and transmit those perpendicular to them, hence the polarization axis is perpendicular to the molecule alignment. Malus’s law is a quantitative way to predict the intensity reduction.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="maluss-law-diagram" class="slide level2">
<h2>Malus’s Law Diagram</h2>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/8ae176c806cbd189dada45ef3ad27f4513fd2556" height="300"></p>
<p><em>Figure 1.37: A polarizing filter transmits only the component of the wave parallel to its axis.</em></p>
<aside class="notes">
<p>This diagram visually represents how a polarizing filter works. Only the component of the incident electric field that is aligned with the filter’s axis is transmitted, leading to a reduction in intensity proportional to <span class="math inline">\(\cos^2\theta\)</span>.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="example-intensity-reduction-by-a-polarizing-filter" class="slide level2">
<h2>Example: Intensity Reduction by a Polarizing Filter</h2>
<p><strong>Question:</strong> What angle is needed between polarized light and a filter’s axis to reduce intensity by 90.0%?</p>
<p><strong>Strategy:</strong></p>
<p>Given <span class="math inline">\(I = 0.100 I_0\)</span>.</p>
<p>Use Malus’s Law: <span class="math inline">\(I = I_0 \cos^2 \theta\)</span>.</p>
<p>Solve for <span class="math inline">\(\theta\)</span>.</p>
<p><strong>Solution:</strong></p>
<p><span class="math display">\[ 0.100 I_0 = I_0 \cos^2 \theta \]</span></p>
<p><span class="math display">\[ \cos^2 \theta = 0.100 \]</span></p>
<p><span class="math display">\[ \cos \theta = \sqrt{0.100} \approx 0.3162 \]</span></p>
<p><span class="math display">\[ \theta = \cos^{-1}(0.3162) \approx 71.6^\circ \]</span></p>
<p><strong>Significance:</strong> A large angle (<span class="math inline">\(71.6^\circ\)</span>) is required for such a significant reduction, but at <span class="math inline">\(45^\circ\)</span>, intensity is already halved.</p>
<aside class="notes">
<p>This example shows that Malus’s Law is not linear; a small change in angle near 0 degrees has less effect than a small change near 90 degrees. This non-linear response is characteristic of cosine squared relationships.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="polarization-by-reflection" class="slide level2">
<h2>Polarization by Reflection</h2>
<ul>
<li>When unpolarized light reflects off a surface, it becomes <strong>partially polarized</strong>.</li>
<li>The reflected light is preferentially horizontally polarized.</li>
<li>Polarizing sunglasses, with vertical axes, block much of this glare.</li>
<li><strong>Brewster’s Law:</strong> Reflected light is completely polarized at <strong>Brewster’s angle</strong> (<span class="math inline">\(\theta_b\)</span>). <span class="math display">\[ \tan \theta_b = \frac{n_2}{n_1} \]</span> where <span class="math inline">\(n_1\)</span> is the incident medium and <span class="math inline">\(n_2\)</span> is the reflecting medium.</li>
<li>At <span class="math inline">\(\theta_b\)</span>, the reflected and refracted rays are perpendicular.</li>
</ul>
<aside class="notes">
<p>Polarization by reflection is a common natural phenomenon. The reason reflected light is largely horizontally polarized is complex but can be intuitively understood as the vertical component of the electric field “sticking” to the surface more readily than the horizontal component, which “bounces off” more efficiently.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="polarization-by-reflection-diagram" class="slide level2">
<h2>Polarization by Reflection Diagram</h2>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/5f568be3772fbabcf334e30df514167de19b0f39" height="350"></p>
<p><em>Figure 1.38: Unpolarized light reflects from a surface, becoming partially horizontally polarized.</em></p>
<aside class="notes">
<p>The diagram clearly shows how the horizontal component of polarization is more strongly reflected, making the reflected light predominantly horizontally polarized. Brewster’s angle is a special case where this horizontal polarization is complete.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="polarization-by-scattering" class="slide level2">
<h2>Polarization by Scattering</h2>
<ul>
<li>Light scattered by air molecules (or other particles like smoke/dust) becomes <strong>partially polarized</strong>.</li>
<li>Electrons in air molecules vibrate perpendicular to the incident light’s direction.</li>
<li>They re-radiate light with polarization perpendicular to the original ray direction.</li>
<li>This explains why the blue sky appears brighter or dimmer when viewed through polarizing sunglasses.</li>
</ul>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/d808d5ffccdbfd5bc92ff1131dc30ee94af05ec9" height="300"></p>
<p><em>Figure 1.41: Polarization by scattering from air molecules.</em></p>
<aside class="notes">
<p>Scattering is another natural process that polarizes light. The blue color of the sky is due to scattering, and the polarization observed in scattered light confirms the transverse wave nature of light. Photographers use polarizing filters to enhance sky contrast.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="liquid-crystals-and-optical-activity" class="slide level2">
<h2>Liquid Crystals and Optical Activity</h2>
<ul>
<li><strong>Liquid Crystal Displays (LCDs):</strong> Based on the ability of liquid crystals to rotate light’s polarization by 90°.
<ul>
<li>This rotation can be turned off by applying a voltage.</li>
<li>Used in screens (watches, phones, TVs) to create contrast.</li>
</ul></li>
<li><strong>Optical Activity:</strong> Some substances (e.g., sugar water, insulin) rotate the plane of polarization of light passing through them.
<ul>
<li>Due to asymmetrical molecular shapes.</li>
<li>Used to measure concentrations or analyze molecular structures.</li>
</ul></li>
</ul>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/0f20a168a795681df10283d2ebc7f7ad678d2aa3" height="300"></p>
<p><em>Figure 1.42: (a) LCD with no voltage (light passes). (b) LCD with voltage (light blocked).</em></p>
<aside class="notes">
<p>LCD technology is a prime example of applying polarization effects. The ability of liquid crystals to either rotate or not rotate polarized light, depending on an applied voltage, is ingeniously used to create the pixels on our screens. Optical activity, meanwhile, is a valuable tool in chemistry and biology for substance analysis.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="key-takeaways" class="slide level2">
<h2>Key Takeaways</h2>
<ul>
<li><strong>Speed of Light:</strong> Constant <code>c</code> in vacuum, slower in matter, defined by index of refraction <code>n = c/v</code>.</li>
<li><strong>Ray Model:</strong> Light travels in straight lines (rays) when interacting with objects much larger than its wavelength.</li>
<li><strong>Reflection:</strong> Angle of incidence equals angle of reflection (<span class="math inline">\(\theta_i = \theta_r\)</span>).</li>
<li><strong>Refraction:</strong> Bending of light due to change in speed; governed by Snell’s Law (<span class="math inline">\(n_1 \sin \theta_1 = n_2 \sin \theta_2\)</span>).</li>
<li><strong>Total Internal Reflection:</strong> Occurs when light goes from higher to lower <code>n</code> and incident angle exceeds critical angle (<span class="math inline">\(\theta_c = \sin^{-1}(n_2/n_1)\)</span>). Crucial for fiber optics and diamond sparkle.</li>
<li><strong>Dispersion:</strong> Spreading of white light into colors due to <code>n</code> depending on wavelength (e.g., rainbows, prisms).</li>
<li><strong>Huygens’s Principle:</strong> Every point on a wavefront is a source of wavelets; explains reflection, refraction, and diffraction.</li>
<li><strong>Polarization:</strong> Direction of electric field oscillations in an EM wave. Unpolarized light has random oscillations.</li>
<li><strong>Malus’s Law:</strong> Intensity of polarized light through a filter: <span class="math inline">\(I = I_0 \cos^2 \theta\)</span>.</li>
<li><strong>Polarization by Reflection/Scattering:</strong> Reflected light is preferentially horizontally polarized; scattered light is partially polarized. Brewster’s angle (<span class="math inline">\(\tan \theta_b = n_2/n_1\)</span>) for complete polarization by reflection.</li>
</ul>
</section>
<section id="key-equations" class="slide level2">
<h2>Key Equations</h2>
<table class="caption-top">
<colgroup>
<col style="width: 29%">
<col style="width: 70%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Equation</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(c \approx 3.00 \times 10^8 \text{ m/s}\)</span></td>
<td style="text-align: left;">Speed of light in a vacuum</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(n = \frac{c}{v}\)</span></td>
<td style="text-align: left;">Index of refraction</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\theta_r = \theta_i\)</span></td>
<td style="text-align: left;">Law of reflection</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(n_1 \sin \theta_1 = n_2 \sin \theta_2\)</span></td>
<td style="text-align: left;">Snell’s Law (Law of refraction)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\theta_c = \sin^{-1} \left( \frac{n_2}{n_1} \right)\)</span></td>
<td style="text-align: left;">Critical angle for total internal reflection (<span class="math inline">\(n_1 &gt; n_2\)</span>)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(I = I_0 \cos^2 \theta\)</span></td>
<td style="text-align: left;">Malus’s Law (intensity of polarized light through a filter)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\tan \theta_b = \frac{n_2}{n_1}\)</span></td>
<td style="text-align: left;">Brewster’s Law (angle for complete polarization by reflection)</td>
</tr>
</tbody>
</table>
</section>
<section id="key-terms" class="slide level2">
<h2>Key Terms</h2>
<table class="caption-top">
<colgroup>
<col style="width: 12%">
<col style="width: 87%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Term</th>
<th style="text-align: left;">Definition</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Speed of Light (<em>c</em>)</strong></td>
<td style="text-align: left;">The speed at which light and all other electromagnetic radiation propagates in a vacuum, approximately <span class="math inline">\(3.00 \times 10^8 \text{ m/s}\)</span>.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Index of Refraction (<em>n</em>)</strong></td>
<td style="text-align: left;">A dimensionless quantity that describes how fast light travels through a medium, defined as the ratio of the speed of light in vacuum to its speed in the medium (<span class="math inline">\(n = c/v\)</span>).</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Ray Model of Light</strong></td>
<td style="text-align: left;">A model that describes light propagation as straight lines (rays), valid when light interacts with objects much larger than its wavelength.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Law of Reflection</strong></td>
<td style="text-align: left;">States that the angle of reflection equals the angle of incidence (<span class="math inline">\(\theta_r = \theta_i\)</span>), both measured relative to the normal to the surface.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Refraction</strong></td>
<td style="text-align: left;">The bending of light as it passes from one transparent medium to another, caused by a change in the speed of light.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Snell’s Law</strong></td>
<td style="text-align: left;">The mathematical relationship governing refraction: <span class="math inline">\(n_1 \sin \theta_1 = n_2 \sin \theta_2\)</span>.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Total Internal Reflection</strong></td>
<td style="text-align: left;">The phenomenon where all incident light is reflected back into the first medium when it strikes a boundary with a second medium of lower index of refraction at an angle greater than the critical angle.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Critical Angle (<span class="math inline">\(\theta_c\)</span>)</strong></td>
<td style="text-align: left;">The incident angle that produces an angle of refraction of <span class="math inline">\(90^\circ\)</span>.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Dispersion</strong></td>
<td style="text-align: left;">The spreading of white light into its full spectrum of wavelengths, due to the dependence of the index of refraction on wavelength.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Huygens’s Principle</strong></td>
<td style="text-align: left;">A method stating that every point on a wave front is a source of wavelets that spread out in the forward direction, with the new wave front being tangent to these wavelets.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Diffraction</strong></td>
<td style="text-align: left;">The bending of a wave around the edges of an opening or an obstacle.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Polarization</strong></td>
<td style="text-align: left;">The attribute that a wave’s oscillations have a definite direction relative to the direction of propagation of the wave (for EM waves, the direction of the electric field).</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Unpolarized Light</strong></td>
<td style="text-align: left;">Light consisting of waves with electric fields oscillating in random directions.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Polarizing Filter</strong></td>
<td style="text-align: left;">A material that transmits only light with electric fields oscillating parallel to its polarization axis.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Malus’s Law</strong></td>
<td style="text-align: left;"><span class="math inline">\(I = I_0 \cos^2 \theta\)</span>, describing the intensity of polarized light after passing through a polarizing filter.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Brewster’s Angle (<span class="math inline">\(\theta_b\)</span>)</strong></td>
<td style="text-align: left;">The angle of incidence at which light reflected from a surface is completely polarized.</td>
</tr>
</tbody>
</table>


<script type="ojs-module-contents">
eyJjb250ZW50cyI6W119
</script>
<div id="exercise-loading-indicator" class="exercise-loading-indicator d-none d-flex align-items-center gap-2">
<div id="exercise-loading-status" class="d-flex gap-2">

</div>
<div class="spinner-grow spinner-grow-sm">

</div>
</div>
<script type="vfs-file">
W10=
</script>
</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="../qrjs_pics/unsoed_logo.png" class="slide-logo"></p>
<div class="footer footer-default">
<p><a href="https://imron-slide.vercel.app">irosyadi-2025</a></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': false,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: true,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script type="ojs-module-contents">
    eyJjb250ZW50cyI6W119
    </script>
    <script type="module">
    if (window.location.protocol === "file:") { alert("The OJS runtime does not work with file:// URLs. Please use a web server to view this document."); }
    window._ojs.paths.runtimeToDoc = "../../book_3";
    window._ojs.paths.runtimeToRoot = "../..";
    window._ojs.paths.docToRoot = "..";
    window._ojs.selfContained = false;
    window._ojs.runtime.interpretFromScriptTags();
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>