<!DOCTYPE html>
<html lang="en"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/quarto-contrib/live-runtime/live-runtime.js" type="module"></script>
<link href="../site_libs/quarto-contrib/live-runtime/live-runtime.css" rel="stylesheet"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.25">

  <meta name="author" content="Imron Rosyadi">
  <title>Physics – Physiscs</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-b0356e9119c1bdfd0db189d130feb51c.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <script type="module" src="../site_libs/quarto-ojs/quarto-ojs-runtime.js"></script>
  <link href="../site_libs/quarto-ojs/quarto-ojs.css" rel="stylesheet">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Physiscs</h1>
  <p class="subtitle">Chapter 14: Fluid Mechanics</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Imron Rosyadi 
</div>
</div>
</div>

</section>
<section id="chapter-14.1-fluids-density-and-pressure" class="slide level2">
<h2>Chapter 14.1: Fluids, Density, and Pressure</h2>
<h3 id="learning-objectives">Learning Objectives</h3>
<p>By the end of this section, you will be able to:</p>
<ul>
<li>State the different phases of matter.</li>
<li>Describe the characteristics of the phases of matter at the molecular or atomic level.</li>
<li>Distinguish between compressible and incompressible materials.</li>
<li>Define density and its related SI units.</li>
<li>Compare and contrast the densities of various substances.</li>
<li>Define pressure and its related SI units.</li>
<li>Explain the relationship between pressure and force.</li>
<li>Calculate force given pressure and area.</li>
</ul>
<aside class="notes">
<p>Today, we’re diving into the fundamental concepts of fluid mechanics, starting with the basics of fluids, density, and pressure. We’ll cover the different phases of matter and their characteristics at the molecular level. You’ll learn to differentiate between compressible and incompressible materials, define density and pressure, understand their SI units, and perform basic calculations involving them.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="phases-of-matter" class="slide level2">
<h2>Phases of Matter</h2>
<p>Matter exists commonly as:</p>
<ul>
<li><strong>Solid:</strong> Rigid, specific shape, definite volume.
<ul>
<li>Atoms/molecules are in close proximity with strong forces, forming a lattice structure.</li>
<li>Resist shearing forces.</li>
</ul></li>
<li><strong>Liquid:</strong> Indefinite shape, definite volume.
<ul>
<li>Molecules bonded but can move past each other.</li>
<li>Yield to shearing forces; they flow.</li>
<li>Resist compression like solids.</li>
</ul></li>
<li><strong>Gas:</strong> Indefinite shape, indefinite volume.
<ul>
<li>Molecules far apart, weak forces.</li>
<li>Easily compressible; they flow and expand to fill containers.</li>
</ul></li>
</ul>
<aside class="notes">
<p>Think about ice, water, and steam. These are all the same substance, H2O, but they behave very differently because of their phase. Solids are like a well-organized team, holding their positions. Liquids are like a crowd that can move around but still stays together. Gases are like individuals freely moving in a large open space. The key difference is the strength of intermolecular forces and the freedom of molecular movement.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="molecular-arrangement-in-phases" class="slide level2">
<h2>Molecular Arrangement in Phases</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/072509312983c51d189605198f1897684966f789" height="300"></p>
<p><em>Figure 14.2: (a) Solid (b) Liquid (c) Gas</em></p>
</div><div class="column" style="width:50%;">
<ul>
<li><strong>Solid (a):</strong> Atoms are in close contact, held in fixed positions by strong forces (like springs).
<ul>
<li>Limited movement.</li>
</ul></li>
<li><strong>Liquid (b):</strong> Atoms are in close contact but can slide over one another.
<ul>
<li>Fewer bonds, allowing for flow.</li>
</ul></li>
<li><strong>Gas (c):</strong> Atoms move about freely and are separated by large distances.
<ul>
<li>Very weak forces; expands to fill container.</li>
</ul></li>
</ul>
</div></div>
<aside class="notes">
<p>This figure visually demonstrates the molecular differences. In solids, notice the tight, almost fixed arrangement. In liquids, they are still close but can slip past each other, which is why liquids flow. In gases, there’s a lot of empty space, making them highly compressible and allowing them to expand freely.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="compressible-vs.-incompressible-fluids" class="slide level2">
<h2>Compressible vs.&nbsp;Incompressible Fluids</h2>
<ul>
<li><strong>Incompressible Fluid:</strong> Requires an extremely large force to change its volume.
<ul>
<li>Liquids (e.g., water) are generally considered incompressible.</li>
<li>Molecules are closely packed.</li>
</ul></li>
<li><strong>Compressible Fluid:</strong> Volume changes significantly with pressure.
<ul>
<li>Gases (e.g., air) are highly compressible.</li>
<li>Molecules are far apart, with weak interactions.</li>
</ul></li>
</ul>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>In fluid mechanics, we often treat liquids as incompressible, which simplifies many calculations. Gases, however, are almost always treated as compressible.</p>
</div>
</div>
</div>
<aside class="notes">
<p>The distinction between compressible and incompressible is crucial. For liquids, like water in a hydraulic system, assuming incompressibility is often a very good approximation. For gases, like air in a tire, compression is a fundamental aspect of their behavior.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="density-rho" class="slide level2">
<h2>Density (<span class="math inline">\(\rho\)</span>)</h2>
<ul>
<li><strong>Definition:</strong> Mass per unit volume.</li>
</ul>
<p><span class="math display">\[ \rho = \frac{m}{V} \]</span></p>
<ul>
<li><strong>SI Unit:</strong> Kilograms per cubic meter (<span class="math inline">\(\text{kg/m}^3\)</span>).
<ul>
<li>Common cgs unit: <span class="math inline">\(\text{g/cm}^3\)</span> (<span class="math inline">\(1 \text{ g/cm}^3 = 1000 \text{ kg/m}^3\)</span>).</li>
</ul></li>
<li>Density determines if an object floats or sinks.
<ul>
<li><strong>Example:</strong> Wood floats in water because its density is less than water’s. Brass sinks because its density is greater.</li>
</ul></li>
</ul>
<aside class="notes">
<p>Density is a fundamental property. It’s not just about how heavy something is, but how much mass is packed into a given space. This is why a small brass object can weigh the same as a large piece of wood, yet behave differently in water. The brass has much more mass per unit volume.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="density-and-floating" class="slide level2">
<h2>Density and Floating</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/712245877ab3abdcd6bd019333d5bcff08b8aeed" height="300"></p>
<p><em>Figure 14.3: (a) Same mass, different volumes. (b) Brass sinks, wood floats.</em></p>
</div><div class="column" style="width:50%;">
<ul>
<li>Even if a block of brass and a block of wood have the same mass (and thus weight):
<ul>
<li>Brass has a smaller volume, meaning higher density.</li>
<li>Wood has a larger volume, meaning lower density.</li>
</ul></li>
<li>When placed in water:
<ul>
<li>Brass (<span class="math inline">\(\rho_{brass} &gt; \rho_{water}\)</span>) sinks.</li>
<li>Wood (<span class="math inline">\(\rho_{wood} &lt; \rho_{water}\)</span>) floats.</li>
</ul></li>
</ul>
</div></div>
<aside class="notes">
<p>This image beautifully illustrates the concept of density’s role in buoyancy. Despite having equal mass, their differing volumes lead to different densities, which dictates their behavior in water.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="densities-of-common-substances" class="slide level2">
<h2>Densities of Common Substances</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Substance</th>
<th><span class="math inline">\(\rho (\text{kg/m}^3)\)</span></th>
<th>Phase</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Gold</td>
<td><span class="math inline">\(1.93 \times 10^4\)</span></td>
<td>Solid</td>
</tr>
<tr class="even">
<td>Lead</td>
<td><span class="math inline">\(1.13 \times 10^4\)</span></td>
<td>Solid</td>
</tr>
<tr class="odd">
<td>Mercury</td>
<td><span class="math inline">\(1.36 \times 10^4\)</span></td>
<td>Liquid</td>
</tr>
<tr class="even">
<td>Water (<span class="math inline">\(4.0^\circ\text{C}\)</span>)</td>
<td><span class="math inline">\(1.000 \times 10^3\)</span></td>
<td>Liquid</td>
</tr>
<tr class="odd">
<td>Ice (<span class="math inline">\(0^\circ\text{C}\)</span>)</td>
<td><span class="math inline">\(9.17 \times 10^2\)</span></td>
<td>Solid</td>
</tr>
<tr class="even">
<td>Oak</td>
<td><span class="math inline">\(7.10 \times 10^2\)</span></td>
<td>Solid</td>
</tr>
<tr class="odd">
<td>Air (<span class="math inline">\(0^\circ\text{C}\)</span>)</td>
<td><span class="math inline">\(1.29 \times 10^0\)</span></td>
<td>Gas</td>
</tr>
<tr class="even">
<td>Hydrogen (<span class="math inline">\(0^\circ\text{C}\)</span>)</td>
<td><span class="math inline">\(9.00 \times 10^{-2}\)</span></td>
<td>Gas</td>
</tr>
</tbody>
</table>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>Densities of liquids and solids are roughly comparable and much greater than gases. Gases are highly dependent on temperature and pressure. Water has a unique density behavior, reaching maximum density at <span class="math inline">\(4.0^\circ\text{C}\)</span>, explaining why ice floats.</p>
</div>
</div>
</div>
<aside class="notes">
<p>Table 14.1 in the textbook has a more comprehensive list. This condensed version highlights some key points: note the vast difference between solids/liquids and gases. Also, the intriguing property of water’s density peaking at 4 degrees Celsius is why lakes freeze from the top down, insulating life below.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="homogeneous-vs.-heterogeneous-substances" class="slide level2">
<h2>Homogeneous vs.&nbsp;Heterogeneous Substances</h2>
<ul>
<li><strong>Homogeneous Substance:</strong> Density is constant throughout.
<ul>
<li>Example: A solid iron bar.</li>
</ul></li>
<li><strong>Heterogeneous Substance:</strong> Density varies within the substance.
<ul>
<li>Example: Swiss cheese (cheese + gas voids).</li>
<li><strong>Local Density:</strong> <span class="math inline">\(\rho = \lim_{\Delta V \to 0} \frac{\Delta m}{\Delta V}\)</span></li>
</ul></li>
</ul>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/5379e17b7814e480c56347941b75020d84b8396c" height="200"></p>
<p><em>Figure 14.4: Local density in a heterogeneous mixture.</em></p>
<aside class="notes">
<p>While we often assume uniform density for simplicity, it’s important to recognize that real-world materials can be heterogeneous. Local density helps describe variations within such materials.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="specific-gravity" class="slide level2">
<h2>Specific Gravity</h2>
<ul>
<li><strong>Definition:</strong> Ratio of a material’s density to the density of water at <span class="math inline">\(4.0^\circ\text{C}\)</span> (<span class="math inline">\(1000 \text{ kg/m}^3\)</span>). <span class="math display">\[ \text{Specific gravity} = \frac{\text{Density of material}}{\text{Density of water}} \]</span></li>
<li><strong>Dimensionless Quantity:</strong> Useful for comparing densities without units.</li>
<li><strong>Example:</strong> Aluminum has a specific gravity of 2.7, meaning it’s 2.7 times denser than water.</li>
</ul>
<aside class="notes">
<p>Specific gravity is a handy tool. Since water’s density is conveniently 1 g/cm<span class="math inline">\(^3\)</span>, the specific gravity often corresponds directly to the numerical value of density in g/cm<span class="math inline">\(^3\)</span>. It removes the need to worry about different unit systems when comparing materials.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="pressure-p" class="slide level2">
<h2>Pressure (<em>p</em>)</h2>
<ul>
<li><strong>Definition:</strong> Normal force <em>F</em> per unit area <em>A</em> over which the force is applied. <span class="math display">\[ p = \frac{F}{A} \]</span></li>
<li><strong>Pressure at a point:</strong> <span class="math inline">\(p = \frac{dF}{dA}\)</span> for an infinitesimal area.</li>
<li><strong>SI Unit:</strong> Pascal (Pa), where <span class="math inline">\(1 \text{ Pa} = 1 \text{ N/m}^2\)</span>.</li>
<li><strong>Scalar Quantity:</strong> Pressure has no direction, but the force due to pressure is always perpendicular to the surface.</li>
</ul>
<aside class="notes">
<p>Pressure is a scalar because it describes a distributed force over an area. However, when we talk about the force <em>exerted by</em> pressure, it’s always perpendicular to the surface. Think about a sharp needle vs.&nbsp;a finger: the same force, but the much smaller area of the needle tip results in immense pressure, enough to pierce skin.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="pressure-and-force" class="slide level2">
<h2>Pressure and Force</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/f61c7b37e2188f52e763f90e969cd7a8c921b9d4" height="250"></p>
<p><em>Figure 14.5: (a) Finger (b) Needle.</em></p>
</div><div class="column" style="width:50%;">
<ul>
<li>The effect of a force depends heavily on the area over which it’s applied.</li>
<li><strong>Example:</strong>
<ul>
<li>A finger applies force over a large area, resulting in low pressure.</li>
<li>A needle applies the same force over a tiny area, resulting in very high pressure.</li>
</ul></li>
</ul>
</div></div>
<aside class="notes">
<p>This is a simple yet powerful illustration of the pressure definition. It’s why snowshoes work (distribute weight over a large area, reducing pressure) and why sharp knives cut well (concentrate force over a small area, increasing pressure).</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="pressure-in-a-fluid-of-constant-density" class="slide level2">
<h2>Pressure in a Fluid of Constant Density</h2>
<ul>
<li>Pressure in a static fluid increases with depth.</li>
<li>The pressure at a depth <em>h</em> below the surface of a fluid with constant density <span class="math inline">\(\rho\)</span> is: <span class="math display">\[ p = p_0 + \rho g h \]</span>
<ul>
<li><span class="math inline">\(p_0\)</span>: atmospheric pressure at the surface.</li>
<li><span class="math inline">\(\rho\)</span>: fluid density.</li>
<li><span class="math inline">\(g\)</span>: acceleration due to gravity.</li>
<li><span class="math inline">\(h\)</span>: depth.</li>
</ul></li>
</ul>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/7d5fb9a856cb5ad9a127815ba824c757170e348a" height="200"></p>
<p><em>Figure 14.6: Pressure at the bottom of a container.</em></p>
<aside class="notes">
<p>This equation is fundamental for static fluids. Imagine diving deeper into a swimming pool; you feel the pressure increase. That’s due to the weight of the water column above you, added to the atmospheric pressure pushing down on the surface. The pressure acts on all surfaces at that depth equally.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="example-dam-force" class="slide level2 scrollable">
<h2>Example: Dam Force</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/bdb7b78b0285a91fef5c0325050db783cef56282" height="250"></p>
<p><em>A dam retaining a reservoir.</em></p>
</div><div class="column" style="width:50%;">
<p><strong>Problem:</strong> A dam is 500-m wide, and water is 80.0-m deep.</p>
<ol type="a">
<li>What is the average pressure on the dam due to water?</li>
<li>Calculate the force against the dam.</li>
</ol>
<p><strong>Solution:</strong></p>
<ol type="a">
<li>Average depth <span class="math inline">\(h = 40.0 \text{ m}\)</span>.</li>
</ol>
<p><span class="math inline">\(p = \rho g h = (10^3 \text{ kg/m}^3)(9.80 \text{ m/s}^2)(40.0 \text{ m}) = 3.92 \times 10^5 \text{ N/m}^2 = 392 \text{ kPa}\)</span>.</p>
<ol start="2" type="a">
<li>Area <span class="math inline">\(A = (80.0 \text{ m})(500 \text{ m}) = 4.00 \times 10^4 \text{ m}^2\)</span>.</li>
</ol>
<p><span class="math inline">\(F = p A = (3.92 \times 10^5 \text{ N/m}^2)(4.00 \times 10^4 \text{ m}^2) = 1.57 \times 10^{10} \text{ N}\)</span>.</p>
</div></div>
<aside class="notes">
<p>For the dam example, since pressure increases linearly with depth, we use the pressure at the average depth to find the average pressure. Then, applying the definition of pressure, we calculate the total force. This force is massive, highlighting the engineering challenges in dam construction.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="pressure-and-container-shape" class="slide level2">
<h2>Pressure and Container Shape</h2>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/d052dd394fdc46bf5a3fbecb3a0a502b0d12e19d" height="250"></p>
<p><em>Figure 14.9: Fluid levels in connected containers of different shapes.</em></p>
<ul>
<li>The pressure in a fluid depends only on the depth from the surface, not on the shape of the container.</li>
<li>This is why liquids seek the same level in interconnected containers, regardless of their shape.</li>
</ul>
<aside class="notes">
<p>This phenomenon, often called the “hydrostatic paradox,” demonstrates that the pressure at a given depth is uniform regardless of the volume or shape of the container above it. It’s a direct consequence of pressure being a scalar quantity and depending only on depth.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="atmospheric-pressure-variation-with-height" class="slide level2">
<h2>Atmospheric Pressure Variation with Height</h2>
<ul>
<li>Unlike liquids, air density changes significantly with height.</li>
<li>Assuming constant air temperature and ideal gas behavior, atmospheric pressure drops exponentially with height: <span class="math display">\[ p(y) = p_0 \exp(-\alpha y) \]</span>
<ul>
<li><span class="math inline">\(p_0\)</span>: pressure at sea level.</li>
<li><span class="math inline">\(\alpha = \frac{mg}{k_B T}\)</span> is a constant.</li>
<li><span class="math inline">\(1/\alpha\)</span> is the pressure scale height (approx. 8800 m for Earth’s atmosphere).</li>
</ul></li>
</ul>
<div class="callout callout-caution callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Caution</strong></p>
</div>
<div class="callout-content">
<p>This exponential drop is an approximation assuming constant temperature and gravity, which isn’t perfectly true over large distances.</p>
</div>
</div>
</div>
<aside class="notes">
<p>This exponential decay of pressure is why mountain climbers need oxygen at high altitudes and why weather balloons burst at very high altitudes. The air becomes progressively thinner as you ascend.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="pressure-direction-in-fluids" class="slide level2">
<h2>Pressure Direction in Fluids</h2>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/e482a00e699ae7dfe2d8fe76fa1e5d9c8c18871a" height="250"></p>
<p><em>Figure 14.10: (a) Tire pressure (b) Swimmer.</em></p>
<ul>
<li>Fluid pressure is a scalar, but the forces due to pressure are always exerted <strong>perpendicular</strong> to any surface.</li>
<li>Fluids cannot withstand shearing forces.</li>
<li>This is evident in:
<ul>
<li>Tire walls (air pushes outwards perpendicularly).</li>
<li>Swimmers (water pushes inward perpendicularly from all directions, with greater force from below due to depth).</li>
</ul></li>
</ul>
<aside class="notes">
<p>The inability of fluids to resist shear stress is fundamental. It means that any force exerted <em>by</em> a fluid on a surface must be normal to that surface. This is why a balloon takes a spherical shape when inflated and why forces on a submerged object are always perpendicular to its surface.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="chapter-14.2-measuring-pressure" class="slide level2">
<h2>Chapter 14.2: Measuring Pressure</h2>
<h3 id="learning-objectives-1">Learning Objectives</h3>
<p>By the end of this section, you will be able to:</p>
<ul>
<li>Define gauge pressure and absolute pressure.</li>
<li>Explain various methods for measuring pressure.</li>
<li>Understand the working of open-tube barometers.</li>
<li>Describe in detail how manometers and barometers operate.</li>
</ul>
<aside class="notes">
<p>Now that we understand pressure, let’s explore how it’s actually measured. We’ll differentiate between two important types of pressure readings: gauge and absolute. Then, we’ll delve into the mechanics of manometers and barometers, which are classic tools for pressure measurement.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="gauge-pressure-vs.-absolute-pressure" class="slide level2">
<h2>Gauge Pressure vs.&nbsp;Absolute Pressure</h2>
<ul>
<li><strong>Gauge Pressure (<span class="math inline">\(p_g\)</span>):</strong> Pressure relative to atmospheric pressure.
<ul>
<li>Most common pressure gauges (e.g., tire pressure, scuba tanks) read zero at atmospheric pressure.</li>
<li>Can be positive (above atmospheric) or negative (below atmospheric, like in a vacuum chamber).</li>
</ul></li>
<li><strong>Absolute Pressure (<span class="math inline">\(p_{abs}\)</span>):</strong> Total pressure, including atmospheric pressure. <span class="math display">\[ p_{abs} = p_g + p_{atm} \]</span>
<ul>
<li>Cannot be negative for fluids (fluids push, not pull). Minimum absolute pressure is zero (perfect vacuum).</li>
</ul></li>
</ul>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>Always be clear whether a pressure value refers to gauge or absolute pressure, especially in problem-solving. Unless stated otherwise, assume gauge pressure in everyday contexts.</p>
</div>
</div>
</div>
<aside class="notes">
<p>This distinction is critical in engineering and physics. When a scuba tank reads 3000 psi, it’s gauge pressure. The actual pressure inside the tank is 3000 psi + 14.7 psi (atmospheric pressure). For fluids, negative absolute pressure is physically impossible because fluids can’t ‘pull’.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="pressure-measuring-devices" class="slide level2">
<h2>Pressure Measuring Devices</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/238db010483a859b4e2a74fe6e74734a087e613d" height="250"></p>
<p><em>Figure 14.11: (a) Gas cylinder gauge (b) Tire gauge (c) Ionization gauge.</em></p>
</div><div class="column" style="width:50%;">
<p>Various devices measure pressure:</p>
<ul>
<li><strong>Mechanical gauges:</strong> (a) Gas cylinder gauges, (b) tire gauges.</li>
<li><strong>Strain gauges:</strong> Measure material shape change due to pressure.</li>
<li><strong>Capacitance pressure gauges:</strong> Measure capacitance change due to shape.</li>
<li><strong>Piezoelectric pressure gauges:</strong> Generate voltage from pressure difference.</li>
<li><strong>Ion gauges:</strong> Measure pressure by ionizing molecules in vacuum systems (c).</li>
</ul>
</div></div>
<aside class="notes">
<p>The principle behind most pressure gauges is that some physical property changes predictably with pressure. From simple mechanical deformation to complex electrical effects, engineers leverage various phenomena to get a pressure reading.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="manometers" class="slide level2 scrollable">
<h2>Manometers</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/b0891fd72b6ce4bf4c929d67307466e6ecaa8aee" height="300"></p>
<p><em>Figure 14.12: Open-tube manometers.</em></p>
</div><div class="column" style="width:50%;">
<ul>
<li>U-shaped tube filled with a fluid (often mercury).</li>
<li>Measures gauge pressure by comparing fluid levels.</li>
<li>One side open to atmosphere (<span class="math inline">\(p_{atm}\)</span>).</li>
<li>Gauge pressure: <span class="math inline">\(p_g = h \rho g\)</span>.
<ul>
<li><ol start="2" type="a">
<li>If <span class="math inline">\(p_{abs} &gt; p_{atm}\)</span>, <span class="math inline">\(p_g\)</span> is positive.</li>
</ol></li>
<li><ol start="3" type="a">
<li>If <span class="math inline">\(p_{abs} &lt; p_{atm}\)</span>, <span class="math inline">\(p_g\)</span> is negative.</li>
</ol></li>
<li>The difference in height, <span class="math inline">\(h\)</span>, indicates the pressure difference.</li>
</ul></li>
</ul>
</div></div>
<aside class="notes">
<p>Manometers are simple but effective. The key is that pressure at the same horizontal level within a continuous fluid must be equal. By measuring the height difference in the fluid column, we directly measure the pressure difference.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="barometers" class="slide level2">
<h2>Barometers</h2>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/630ff58f744b75b6ab78144f8f59e0ffc7b16c8d" height="300"></p>
<p><em>Figure 14.13: A mercury barometer.</em></p>
<ul>
<li>Invented by Torricelli in 1643.</li>
<li>Measures <strong>atmospheric pressure</strong>.</li>
<li>A glass tube, closed at one end and filled with mercury, inverted into a pool of mercury.</li>
<li>A near-perfect vacuum exists above the mercury column in the tube.</li>
<li>Atmospheric pressure supports the column of mercury: <span class="math inline">\(h \rho g = p_{atm}\)</span>.</li>
<li>Used by meteorologists for weather forecasting (rising mercury = improving weather).</li>
</ul>
<aside class="notes">
<p>Barometers provide a direct measurement of atmospheric pressure. The height of the mercury column is a direct consequence of the external atmospheric pressure pushing down on the mercury in the dish, balancing the weight of the mercury in the tube. The vacuum above the mercury is crucial for accurate measurement.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="fluid-heights-in-an-open-u-tube-example" class="slide level2">
<h2>Fluid Heights in an Open U-Tube Example</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/7dd5455b194c0884c2e6847359d5c371fbb8a58d" height="250"></p>
<p><em>Figure 14.14: Two liquids in a U-tube.</em></p>
</div><div class="column" style="width:50%;">
<p><strong>Problem:</strong> Two immiscible liquids of densities <span class="math inline">\(\rho_1\)</span> and <span class="math inline">\(\rho_2\)</span> (<span class="math inline">\(\rho_2 &lt; \rho_1\)</span>) are in an open U-tube. Derive a formula for the height difference <span class="math inline">\(h_2 - h_1\)</span>.</p>
<p><strong>Solution:</strong> Equate pressures at the interface level in both arms: <span class="math inline">\(p_0 + \rho_1 g h_1 = p_0 + \rho_2 g h_2\)</span> <span class="math inline">\(\rho_1 h_1 = \rho_2 h_2\)</span> <span class="math inline">\(h_1 = \frac{\rho_2}{\rho_1} h_2\)</span> Height difference: <span class="math inline">\(h_2 - h_1 = h_2 - \frac{\rho_2}{\rho_1} h_2 = (1 - \frac{\rho_2}{\rho_1}) h_2\)</span>.</p>
</div></div>
<aside class="notes">
<p>This example uses the principle that points at the same horizontal level within the same continuous fluid have equal pressure. By choosing the interface as our reference level, we can relate the heights of the two liquids and their densities to atmospheric pressure.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="units-of-pressure" class="slide level2">
<h2>Units of Pressure</h2>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Unit</th>
<th>Definition</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Pascal (Pa)</td>
<td><span class="math inline">\(1 \text{ N/m}^2\)</span></td>
</tr>
<tr class="even">
<td>pounds per square inch (psi)</td>
<td><span class="math inline">\(1 \text{ psi} = 6.895 \times 10^3 \text{ Pa}\)</span></td>
</tr>
<tr class="odd">
<td>Atmosphere (atm)</td>
<td><span class="math inline">\(1 \text{ atm} = 1.013 \times 10^5 \text{ Pa} = 760 \text{ mm Hg} = 14.7 \text{ psi}\)</span></td>
</tr>
<tr class="even">
<td>Millibar (mbar)</td>
<td><span class="math inline">\(1 \text{ mbar} = 100 \text{ Pa}\)</span> (<span class="math inline">\(1000 \text{ mbar} = 1 \times 10^5 \text{ Pa}\)</span>)</td>
</tr>
<tr class="odd">
<td>Torr</td>
<td><span class="math inline">\(1 \text{ torr} = 1 \text{ mm Hg} = 133.3 \text{ Pa}\)</span></td>
</tr>
<tr class="even">
<td>Bar</td>
<td><span class="math inline">\(1 \text{ bar} = 10^5 \text{ Pa}\)</span></td>
</tr>
</tbody>
</table>
<aside class="notes">
<p>It’s important to be familiar with these different units, as they are used in various fields. Meteorologists often use millibars, while medical professionals might refer to blood pressure in mm Hg. Converting between them is a common task in fluid mechanics.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="chapter-14.3-pascals-principle-and-hydraulics" class="slide level2">
<h2>Chapter 14.3: Pascal’s Principle and Hydraulics</h2>
<h3 id="learning-objectives-2">Learning Objectives</h3>
<p>By the end of this section, you will be able to:</p>
<ul>
<li>State Pascal’s principle.</li>
<li>Describe applications of Pascal’s principle.</li>
<li>Derive relationships between forces in a hydraulic system.</li>
</ul>
<aside class="notes">
<p>We’re moving on to a very practical aspect of fluid mechanics: Pascal’s Principle. This principle is the cornerstone of hydraulics, which powers many machines we use daily, from car brakes to construction equipment. We’ll learn what the principle states, see its applications, and derive key relationships.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="pascals-principle" class="slide level2">
<h2>Pascal’s Principle</h2>
<ul>
<li><strong>Statement:</strong> When a change in pressure is applied to an enclosed fluid, it is transmitted undiminished to all portions of the fluid and to the walls of its container.</li>
<li>This principle applies to the <strong>change in pressure</strong>, not necessarily the absolute pressure being the same everywhere (as pressure still varies with depth).</li>
</ul>
<div class="columns">
<div class="column" style="width:50%;">
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/64f1e3d59341aa9f1f3157079b33cfad3cca8d95" height="200"></p>
<p><em>Figure 14.15: Pressure change in a fluid with a piston.</em></p>
</div><div class="column" style="width:50%;">
<ul>
<li>If you add a weight <span class="math inline">\(Mg\)</span> to a piston of area <span class="math inline">\(A\)</span>, the pressure at the top increases by <span class="math inline">\(\Delta p = \frac{Mg}{A}\)</span>.</li>
<li>According to Pascal’s principle, this <span class="math inline">\(\Delta p\)</span> is transmitted throughout the entire fluid.
<ul>
<li><span class="math inline">\(\Delta p_{top} = \Delta p_{bottom} = \Delta p_{everywhere}\)</span>.</li>
</ul></li>
</ul>
</div></div>
<aside class="notes">
<p>Pascal’s principle is a profound insight. It means that if you squeeze a sealed container filled with fluid, that squeeze force is distributed evenly throughout the fluid, regardless of where or how hard you squeeze. This uniform transmission of pressure change is what makes hydraulics so powerful.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="applications-of-pascals-principle-hydraulic-systems" class="slide level2">
<h2>Applications of Pascal’s Principle: Hydraulic Systems</h2>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/b740655a210ea22cf3092817c2fea10fe3ceb25c" height="300"></p>
<p><em>Figure 14.16: A typical hydraulic system.</em></p>
<ul>
<li>Hydraulic systems use Pascal’s principle to multiply forces.</li>
<li>An input force <span class="math inline">\(F_1\)</span> on a small area <span class="math inline">\(A_1\)</span> creates a pressure <span class="math inline">\(p_1 = F_1/A_1\)</span>.</li>
<li>This pressure is transmitted to a larger area <span class="math inline">\(A_2\)</span>, creating a larger output force <span class="math inline">\(F_2\)</span>.</li>
<li>Since <span class="math inline">\(p_1 = p_2\)</span> (assuming same height, negligible friction): <span class="math display">\[ \frac{F_1}{A_1} = \frac{F_2}{A_2} \]</span>
<ul>
<li>If <span class="math inline">\(A_2 &gt; A_1\)</span>, then <span class="math inline">\(F_2 &gt; F_1\)</span>.</li>
</ul></li>
</ul>
<aside class="notes">
<p>This equation is the core of hydraulic force multiplication. A small force applied over a small area can generate a much larger force over a larger area. This is analogous to a lever, but with the added flexibility of being able to transmit this force through curved pipes and to multiple points simultaneously, using an incompressible fluid like oil.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="hydraulic-jack" class="slide level2">
<h2>Hydraulic Jack</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/dfa2bc4a5926dfdc021e460e52b173adf8061b19" height="250"></p>
<p><em>Figure 14.17: (a) Hydraulic jack principle (b) Car on a hydraulic jack.</em></p>
</div><div class="column" style="width:50%;">
<ul>
<li>A small input force (<span class="math inline">\(F_1\)</span>) over a small piston area (<span class="math inline">\(A_1\)</span>) lifts a large load (<span class="math inline">\(F_2\)</span>) on a large piston area (<span class="math inline">\(A_2\)</span>).</li>
<li>The ratio of forces is directly proportional to the ratio of areas: <span class="math display">\[ F_2 = F_1 \frac{A_2}{A_1} \]</span></li>
<li>Commonly used to lift heavy objects like cars.</li>
</ul>
</div></div>
<aside class="notes">
<p>Hydraulic jacks are a prime example of force multiplication. A person can lift a car with relatively little effort by repeatedly applying a small force over a small piston area, gradually raising the larger piston. While force is multiplied, work is conserved; the smaller piston moves a greater distance than the larger one.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="example-calculating-force-on-wheel-cylinders-automobile-brakes" class="slide level2">
<h2>Example: Calculating Force on Wheel Cylinders (Automobile Brakes)</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/07f682ab2c594e0da0bde036df2651f85f19ff53" height="250"></p>
<p><em>Figure 14.18: Hydraulic brake system.</em></p>
</div><div class="column" style="width:50%;">
<p><strong>Problem:</strong> A 500 N force is exerted on a pedal cylinder (master cylinder) with diameter 0.500 cm. Each wheel cylinder has a diameter of 2.50 cm. Calculate the force <span class="math inline">\(F_2\)</span> at each wheel cylinder.</p>
<p><strong>Solution:</strong></p>
<p><span class="math inline">\(F_1 = 500 \text{ N}\)</span></p>
<p><span class="math inline">\(d_1 = 0.500 \text{ cm} \Rightarrow r_1 = 0.250 \text{ cm}\)</span></p>
<p><span class="math inline">\(d_2 = 2.50 \text{ cm} \Rightarrow r_2 = 1.25 \text{ cm}\)</span></p>
<p>Using <span class="math inline">\(\frac{F_1}{A_1} = \frac{F_2}{A_2}\)</span>:</p>
<p><span class="math inline">\(F_2 = F_1 \frac{A_2}{A_1} = F_1 \frac{\pi r_2^2}{\pi r_1^2} = F_1 \frac{r_2^2}{r_1^2}\)</span></p>
<p><span class="math inline">\(F_2 = (500 \text{ N}) \frac{(1.25 \text{ cm})^2}{(0.250 \text{ cm})^2} = (500 \text{ N}) \frac{1.5625}{0.0625} = 1.25 \times 10^4 \text{ N}\)</span>.</p>
</div></div>
<aside class="notes">
<p>This calculation shows how a relatively small force on the brake pedal translates into a very large force at each wheel, enabling effective braking. Note that the force is multiplied by a factor equal to the square of the ratio of the radii. This large increase in force is why hydraulic brakes are so effective.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="chapter-14.4-archimedes-principle-and-buoyancy" class="slide level2">
<h2>Chapter 14.4: Archimedes’ Principle and Buoyancy</h2>
<h3 id="learning-objectives-3">Learning Objectives</h3>
<p>By the end of this section, you will be able to:</p>
<ul>
<li>Define buoyant force.</li>
<li>State Archimedes’ principle.</li>
<li>Describe the relationship between density and Archimedes’ principle.</li>
</ul>
<aside class="notes">
<p>We’re now shifting gears to understand why some objects float and others sink – the concept of buoyancy. This section will introduce Archimedes’ principle, a cornerstone of fluid statics, and explain how an object’s density relates to whether it floats or sinks.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="buoyant-force-f_b" class="slide level2">
<h2>Buoyant Force (<span class="math inline">\(F_B\)</span>)</h2>
<ul>
<li><strong>Definition:</strong> The upward force on any object in any fluid.</li>
<li>Arises because pressure increases with depth.
<ul>
<li>Upward force on the bottom of an object is greater than the downward force on the top.</li>
</ul></li>
<li><strong>Result:</strong> Net upward force on the object.</li>
<li>Present whether an object floats, sinks, or is suspended.</li>
</ul>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/890168a9ef96d6cdea88cf7a401fd7bd9618187a" height="250"></p>
<p><em>Figure 14.20: Net buoyant force on an object.</em></p>
<aside class="notes">
<p>Think about pushing a beach ball underwater. You feel that upward push – that’s buoyant force. It’s a direct consequence of the pressure difference between the top and bottom of the object. The deeper parts experience higher pressure, leading to a greater upward force.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="archimedes-principle" class="slide level2">
<h2>Archimedes’ Principle</h2>
<ul>
<li><strong>Statement:</strong> The buoyant force on an object equals the weight of the fluid it displaces.</li>
</ul>
<p><span class="math display">\[ F_B = w_{fl} \]</span></p>
<pre><code>-   $F_B$: buoyant force.
-   $w_{fl}$: weight of the fluid displaced by the object.</code></pre>
<div class="columns">
<div class="column" style="width:50%;">
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/5a46d1ddb0527a659f67d046baa694cd45291b22" height="250"></p>
<p><em>Figure 14.21: Buoyant force equals weight of displaced fluid.</em></p>
</div><div class="column" style="width:50%;">
<ul>
<li>Named after Archimedes of Syracuse.</li>
<li>When an object is submerged, it pushes aside, or <em>displaces</em>, a certain volume of fluid. The weight of that displaced fluid is exactly the buoyant force acting on the object.</li>
</ul>
</div></div>
<aside class="notes">
<p>This is one of the oldest and most elegant principles in physics. It elegantly links the buoyant force to something measurable: the weight of the fluid pushed out of the way. This principle is true whether the object floats, sinks, or is completely submerged.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="density-and-archimedes-principle" class="slide level2">
<h2>Density and Archimedes’ Principle</h2>
<ul>
<li>An object’s <strong>average density</strong> determines if it floats:
<ul>
<li>If <span class="math inline">\(\rho_{obj} &lt; \rho_{fl}\)</span>: Object floats.</li>
<li>If <span class="math inline">\(\rho_{obj} &gt; \rho_{fl}\)</span>: Object sinks.</li>
<li>If <span class="math inline">\(\rho_{obj} = \rho_{fl}\)</span>: Object remains suspended (neutrally buoyant).</li>
</ul></li>
<li><strong>Fraction submerged:</strong> For a floating object, the fraction of its volume submerged is: <span class="math display">\[ \text{fraction submerged} = \frac{V_{sub}}{V_{obj}} = \frac{\rho_{obj}}{\rho_{fl}} \]</span></li>
</ul>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/956cc8fefc220b1f1cd8ee5f4ad923da1e1cef6c" height="250"></p>
<p><em>Figure 14.22: Unloaded vs.&nbsp;loaded ship.</em></p>
<aside class="notes">
<p>This is a powerful relationship. It explains why a massive steel ship floats (its average density, including the air inside, is less than water) while a small pebble sinks. The fraction of a floating object that is submerged is a direct ratio of its density to the fluid’s density.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="example-calculating-average-density" class="slide level2">
<h2>Example: Calculating Average Density</h2>
<p><strong>Problem:</strong> A 60.0-kg woman floats in fresh water with 97.0% of her volume submerged when her lungs are full of air. What is her average density?</p>
<p><strong>Given:</strong></p>
<p><span class="math inline">\(m_{person} = 60.0 \text{ kg}\)</span></p>
<p>Fraction submerged = 0.970</p>
<p><span class="math inline">\(\rho_{water} = 1.000 \times 10^3 \text{ kg/m}^3\)</span></p>
<p><strong>Solution:</strong></p>
<p>Using the formula for fraction submerged:</p>
<p><span class="math inline">\(\text{fraction submerged} = \frac{\rho_{obj}}{\rho_{fl}}\)</span></p>
<p><span class="math inline">\(\rho_{person} = (\text{fraction submerged}) \times \rho_{water}\)</span></p>
<p><span class="math inline">\(\rho_{person} = (0.970) \times (1.000 \times 10^3 \text{ kg/m}^3) = 970 \text{ kg/m}^3\)</span>.</p>
<p><strong>Significance:</strong> Her average density is indeed less than water, which is why she floats.</p>
<aside class="notes">
<p>This example demonstrates how we can use the fraction of an object submerged to determine its average density. It’s a practical application of Archimedes’ principle and the concept of density.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="measuring-density-with-apparent-weight" class="slide level2">
<h2>Measuring Density with Apparent Weight</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/68abd62995221fcb63db2077b93564859cd05083" height="250"></p>
<p><em>Figure 14.23: Weighing a coin in air and water.</em></p>
</div><div class="column" style="width:50%;">
<ul>
<li>An object’s <strong>apparent weight</strong> when submerged is less than its actual weight in air.</li>
<li><strong>Apparent weight loss = Weight of fluid displaced = Buoyant force.</strong></li>
<li>By weighing an object in air (<span class="math inline">\(W_{air}\)</span>) and then submerged in a fluid (<span class="math inline">\(W_{app}\)</span>): <span class="math inline">\(F_B = W_{air} - W_{app}\)</span> Since <span class="math inline">\(F_B = \rho_{fl} g V_{obj}\)</span> and <span class="math inline">\(W_{air} = \rho_{obj} g V_{obj}\)</span>: <span class="math inline">\(\rho_{obj} = \rho_{fl} \frac{W_{air}}{W_{air} - W_{app}}\)</span></li>
<li>This technique can be used to find either <span class="math inline">\(\rho_{obj}\)</span> (if <span class="math inline">\(\rho_{fl}\)</span> is known) or <span class="math inline">\(\rho_{fl}\)</span> (if <span class="math inline">\(\rho_{obj}\)</span> is known).</li>
</ul>
</div></div>
<aside class="notes">
<p>This is a common laboratory technique. By measuring the “lost” weight when an object is submerged, you’re essentially measuring the buoyant force, which in turn tells you about the volume of displaced fluid and thus the object’s (or fluid’s) density.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="chapter-14.5-fluid-dynamics" class="slide level2">
<h2>Chapter 14.5: Fluid Dynamics</h2>
<h3 id="learning-objectives-4">Learning Objectives</h3>
<p>By the end of this section, you will be able to:</p>
<ul>
<li>Describe the characteristics of flow.</li>
<li>Calculate flow rate.</li>
<li>Describe the relationship between flow rate and velocity.</li>
<li>Explain the consequences of the equation of continuity to the conservation of mass.</li>
</ul>
<aside class="notes">
<p>So far, we’ve focused on fluids at rest. Now, we’re transitioning to <strong>fluid dynamics</strong> – the study of fluids in motion. This is where things get more complex and exciting! We’ll start with fundamental concepts like flow types, flow rate, and how velocity changes in moving fluids, all tied together by the crucial principle of mass conservation.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="characteristics-of-flow-streamlines" class="slide level2">
<h2>Characteristics of Flow: Streamlines</h2>
<ul>
<li><strong>Streamline:</strong> Represents the path of a small volume of fluid as it flows.
<ul>
<li>The velocity vector is always tangential to the streamline.</li>
</ul></li>
<li><strong>Laminar Flow (Steady Flow):</strong> Smooth, parallel streamlines.
<ul>
<li>Layers flow without mixing.</li>
<li>Velocity may vary across the flow (e.g., faster in the center of a pipe due to viscosity).</li>
</ul></li>
<li><strong>Turbulent Flow:</strong> Irregular, chaotic streamlines that change over time.
<ul>
<li>Fluid mixes, forming eddies and whirlpools.</li>
<li>Occurs at high speeds or due to obstructions.</li>
</ul></li>
</ul>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/e731922652399f0f03dd33bca545f5cf4f7710b1" height="250"></p>
<p><em>Figure 14.25: (a) Laminar flow (b) Turbulent flow.</em></p>
<aside class="notes">
<p>Understanding these flow characteristics is essential. Laminar flow is predictable and easier to model, like a calm river. Turbulent flow is complex and chaotic, like rapids. Many real-world systems experience both, and the transition point is important for engineering design.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="flow-rate-q" class="slide level2">
<h2>Flow Rate (<span class="math inline">\(Q\)</span>)</h2>
<ul>
<li><strong>Volume Flow Rate:</strong> Volume of fluid passing a given location through an area per unit time. <span class="math display">\[ Q = \frac{V}{t} \]</span></li>
<li><strong>Relationship to Velocity:</strong> <span class="math display">\[ Q = Av \]</span>
<ul>
<li><span class="math inline">\(A\)</span>: cross-sectional area of flow.</li>
<li><span class="math inline">\(v\)</span>: average speed of the fluid.</li>
</ul></li>
<li><strong>SI Unit:</strong> <span class="math inline">\(\text{m}^3/\text{s}\)</span>. (Liters/minute are also common).</li>
</ul>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/26e3f8b758bc8c0592f019edca0c73ab5d819ff5" height="200"></p>
<p><em>Figure 14.26: Volume flow rate.</em></p>
<aside class="notes">
<p>Flow rate isn’t just about how fast the fluid is moving; it’s also about how much fluid is moving. A small pipe with very fast flow might have the same flow rate as a large pipe with slow flow. This formula is fundamental for analyzing fluid transport.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-equation-of-continuity" class="slide level2">
<h2>The Equation of Continuity</h2>
<ul>
<li>For an <strong>incompressible fluid</strong> (constant density) in steady flow, the flow rate is constant throughout the pipe.
<ul>
<li>No fluid is created or destroyed.</li>
<li><strong>Mass conservation</strong> implies volume flow rate conservation. <span class="math display">\[ Q_1 = Q_2 \]</span> <span class="math display">\[ A_1 v_1 = A_2 v_2 \]</span></li>
<li>If the cross-sectional area decreases, the fluid speed must increase (and vice versa).</li>
</ul></li>
</ul>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/93d94c1d069e12c42214e85dbbea8e52b3caa47b" height="250"></p>
<p><em>Figure 14.27: Fluid speed increases when a tube narrows.</em></p>
<aside class="notes">
<p>This principle is very intuitive. Think about putting your thumb over the end of a garden hose. The water comes out faster. You’re decreasing the area, so the velocity must increase to maintain the same flow rate. This is a direct consequence of mass conservation for incompressible fluids.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="example-calculating-fluid-speed-through-a-nozzle" class="slide level2 scrollable">
<h2>Example: Calculating Fluid Speed through a Nozzle</h2>
<p><strong>Problem:</strong> A nozzle with diameter 0.500 cm is attached to a hose with radius 0.900 cm. The flow rate is 0.500 L/s. Calculate the speed of water (a) in the hose and (b) in the nozzle.</p>
<p><strong>Given:</strong></p>
<p><span class="math inline">\(Q = 0.500 \text{ L/s} = 0.500 \times 10^{-3} \text{ m}^3/\text{s}\)</span></p>
<p>Hose: <span class="math inline">\(r_1 = 0.900 \text{ cm} = 0.00900 \text{ m}\)</span></p>
<p>Nozzle: <span class="math inline">\(d_2 = 0.500 \text{ cm} \Rightarrow r_2 = 0.250 \text{ cm} = 0.00250 \text{ m}\)</span></p>
<p><strong>Solution:</strong></p>
<ol type="a">
<li>Speed in the hose (<span class="math inline">\(v_1\)</span>):</li>
</ol>
<p><span class="math inline">\(A_1 = \pi r_1^2 = \pi (0.00900 \text{ m})^2\)</span></p>
<p><span class="math inline">\(v_1 = \frac{Q}{A_1} = \frac{0.500 \times 10^{-3} \text{ m}^3/\text{s}}{\pi (0.00900 \text{ m})^2} = 1.96 \text{ m/s}\)</span>.</p>
<ol start="2" type="a">
<li>Speed in the nozzle (<span class="math inline">\(v_2\)</span>):</li>
</ol>
<p>Using the equation of continuity <span class="math inline">\(A_1 v_1 = A_2 v_2\)</span>:</p>
<p><span class="math inline">\(v_2 = v_1 \frac{A_1}{A_2} = v_1 \frac{\pi r_1^2}{\pi r_2^2} = v_1 \left(\frac{r_1}{r_2}\right)^2\)</span></p>
<p><span class="math inline">\(v_2 = (1.96 \text{ m/s}) \left(\frac{0.900 \text{ cm}}{0.250 \text{ cm}}\right)^2 = (1.96 \text{ m/s}) (3.6)^2 = 25.5 \text{ m/s}\)</span>.</p>
<aside class="notes">
<p>This example shows the significant impact of narrowing a pipe. A relatively small reduction in radius leads to a large increase in fluid speed, demonstrating the <span class="math inline">\(r^2\)</span> dependence in the continuity equation.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="mass-flow-rate-and-general-continuity-equation" class="slide level2">
<h2>Mass Flow Rate and General Continuity Equation</h2>
<ul>
<li><p><strong>Mass Flow Rate (<span class="math inline">\(\frac{dm}{dt}\)</span>):</strong> The rate at which mass of fluid moves past a point.</p>
<p><span class="math display">\[ \frac{dm}{dt} = \rho A v \]</span></p></li>
<li><p><strong>General Continuity Equation:</strong> For any fluid (compressible or incompressible), mass flow rate is conserved:</p>
<p><span class="math display">\[ \left(\frac{dm}{dt}\right)_1 = \left(\frac{dm}{dt}\right)_2 \]</span></p>
<p><span class="math display">\[ \rho_1 A_1 v_1 = \rho_2 A_2 v_2 \]</span></p></li>
<li><p>If the fluid is incompressible (<span class="math inline">\(\rho_1 = \rho_2\)</span>), then <span class="math inline">\(\rho\)</span> cancels, returning <span class="math inline">\(A_1 v_1 = A_2 v_2\)</span>.</p></li>
</ul>
<aside class="notes">
<p>While the <span class="math inline">\(Av\)</span> form of continuity is popular, the <span class="math inline">\(\rho Av\)</span> form is more general and accounts for situations where fluid density might change, such as with gases or in extreme conditions. It’s a statement of the fundamental principle of mass conservation in fluid flow.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="chapter-14.6-bernoullis-equation" class="slide level2">
<h2>Chapter 14.6: Bernoulli’s Equation</h2>
<h3 id="learning-objectives-5">Learning Objectives</h3>
<p>By the end of this section, you will be able to:</p>
<ul>
<li>Explain the terms in Bernoulli’s equation.</li>
<li>Explain how Bernoulli’s equation is related to the conservation of energy.</li>
<li>Describe how to derive Bernoulli’s principle from Bernoulli’s equation.</li>
<li>Perform calculations using Bernoulli’s principle.</li>
<li>Describe some applications of Bernoulli’s principle.</li>
</ul>
<aside class="notes">
<p>Now we combine fluid motion with energy conservation. Bernoulli’s equation is a powerful tool that links pressure, velocity, and height in moving fluids. It’s essentially an energy conservation law for fluids and explains many phenomena, from why shower curtains billow inward to how airplane wings generate lift.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="bernoullis-equation" class="slide level2">
<h2>Bernoulli’s Equation</h2>
<ul>
<li>Based on the <strong>conservation of energy</strong> for an incompressible, frictionless fluid in laminar flow.</li>
<li>It states that along a streamline, the sum of pressure, kinetic energy density, and potential energy density is constant: <span class="math display">\[ p + \frac{1}{2} \rho v^2 + \rho g y = \text{constant} \]</span>
<ul>
<li><span class="math inline">\(p\)</span>: absolute pressure.</li>
<li><span class="math inline">\(\frac{1}{2} \rho v^2\)</span>: kinetic energy density (dynamic pressure).</li>
<li><span class="math inline">\(\rho g y\)</span>: potential energy density (hydrostatic pressure).</li>
</ul></li>
</ul>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/0556aab7edb96841558350eb145f7771e67166d3" height="250"></p>
<p><em>Figure 14.30: Geometry for deriving Bernoulli’s equation.</em></p>
<aside class="notes">
<p>Bernoulli’s equation is a statement of mechanical energy conservation applied to a fluid. The “constant” means that if you pick any two points along a streamline, the sum of these three terms will be the same. This equation has immense practical applications.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="analyzing-bernoullis-equation" class="slide level2">
<h2>Analyzing Bernoulli’s Equation</h2>
<ul>
<li><strong>Energy Transformation:</strong> Pressure, kinetic energy density, and potential energy density can interconvert, but their sum remains constant.</li>
<li><strong>Pressure Drop with Speed:</strong> As fluid speed (<em>v</em>) increases, the pressure (<em>p</em>) tends to decrease (assuming constant height), to keep the sum constant.
<ul>
<li><strong>Examples:</strong> Shower curtain bulging inward, cars pulling towards trucks on a highway.</li>
</ul></li>
</ul>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/ad862df1564ff87b4890b35ebdfbad23925b7260" height="250"></p>
<p><em>Figure 14.29: Pressure drop between passing vehicles.</em></p>
<aside class="notes">
<p>This is a key takeaway: faster fluid flow generally means lower pressure. The energy that goes into increasing kinetic energy must come from somewhere, and often it comes from a reduction in pressure. This is a counter-intuitive idea for many, but it’s crucial for understanding fluid dynamics.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="special-cases-of-bernoullis-equation" class="slide level2 scrollable">
<h2>Special Cases of Bernoulli’s Equation</h2>
<ol type="1">
<li><p><strong>Static Fluids (<span class="math inline">\(v_1 = v_2 = 0\)</span>):</strong></p>
<p><span class="math display">\[ p_1 + \rho g y_1 = p_2 + \rho g y_2 \]</span></p>
<p>If <span class="math inline">\(y_2 = 0\)</span>, then <span class="math inline">\(p_2 = p_1 + \rho g y_1\)</span>. This confirms pressure increases with depth, as seen in fluid statics.</p></li>
<li><p><strong>Bernoulli’s Principle (Constant Depth, <span class="math inline">\(y_1 = y_2\)</span>):</strong></p>
<p><span class="math display">\[ p_1 + \frac{1}{2} \rho v_1^2 = p_2 + \frac{1}{2} \rho v_2^2 \]</span></p>
<p>This clearly shows that if <span class="math inline">\(v_2 &gt; v_1\)</span>, then <span class="math inline">\(p_2 &lt; p_1\)</span>. Pressure drops as speed increases.</p></li>
</ol>
<aside class="notes">
<p>It’s reassuring that Bernoulli’s equation, when simplified for static fluids, reduces to our familiar hydrostatic pressure equation. Bernoulli’s principle is a frequently used simplification for horizontal flow, emphasizing the inverse relationship between speed and pressure.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="example-calculating-pressure-in-a-hose" class="slide level2">
<h2>Example: Calculating Pressure in a Hose</h2>
<p><strong>Problem:</strong> Water speed in a hose increases from 1.96 m/s to 25.5 m/s in a nozzle. Absolute pressure in the nozzle is <span class="math inline">\(1.01 \times 10^5 \text{ N/m}^2\)</span> (atmospheric). Assuming level, frictionless flow, calculate the pressure in the hose.</p>
<p><strong>Given:</strong></p>
<p><span class="math inline">\(v_1 = 1.96 \text{ m/s}\)</span> (hose)</p>
<p><span class="math inline">\(v_2 = 25.5 \text{ m/s}\)</span> (nozzle)</p>
<p><span class="math inline">\(p_2 = 1.01 \times 10^5 \text{ Pa}\)</span> (nozzle pressure)</p>
<p><span class="math inline">\(\rho_{water} = 1000 \text{ kg/m}^3\)</span></p>
<p>Level flow implies <span class="math inline">\(y_1 = y_2\)</span>.</p>
<p><strong>Solution:</strong></p>
<p>Using Bernoulli’s principle: <span class="math inline">\(p_1 + \frac{1}{2} \rho v_1^2 = p_2 + \frac{1}{2} \rho v_2^2\)</span></p>
<p>Solving for <span class="math inline">\(p_1\)</span>:</p>
<p><span class="math inline">\(p_1 = p_2 + \frac{1}{2} \rho v_2^2 - \frac{1}{2} \rho v_1^2 = p_2 + \frac{1}{2} \rho (v_2^2 - v_1^2)\)</span></p>
<p><span class="math inline">\(p_1 = 1.01 \times 10^5 \text{ Pa} + \frac{1}{2} (1000 \text{ kg/m}^3) [(25.5 \text{ m/s})^2 - (1.96 \text{ m/s})^2]\)</span></p>
<p><span class="math inline">\(p_1 = 1.01 \times 10^5 \text{ Pa} + 500 \text{ kg/m}^3 [650.25 \text{ m}^2/\text{s}^2 - 3.84 \text{ m}^2/\text{s}^2]\)</span></p>
<p><span class="math inline">\(p_1 = 1.01 \times 10^5 \text{ Pa} + 500 \text{ kg/m}^3 (646.41 \text{ m}^2/\text{s}^2)\)</span></p>
<p><span class="math inline">\(p_1 = 1.01 \times 10^5 \text{ Pa} + 3.23 \times 10^5 \text{ Pa} = 4.24 \times 10^5 \text{ Pa}\)</span>.</p>
<aside class="notes">
<p>The pressure in the hose is significantly higher than in the nozzle, which makes sense. The higher pressure in the hose is what pushes the water to accelerate as it enters the narrower nozzle, converting pressure energy into kinetic energy.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="applications-of-bernoullis-principle" class="slide level2 scrollable">
<h2>Applications of Bernoulli’s Principle</h2>
<ol type="1">
<li><strong>Entrainment:</strong> Using high-velocity fluid to create low pressure, which pulls other fluids into the stream.
<ul>
<li>Bunsen burners entrain air for combustion.</li>
<li>Atomizers entrain perfume drops.</li>
<li>Aspirators use water to create suction.</li>
<li>Chimneys entrain air to draw smoke up.</li>
</ul></li>
</ol>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/1ba2a97926142e00d774c630bf57526073d2f634" height="250"></p>
<p><em>Figure 14.31: Entrainment devices.</em></p>
<aside class="notes">
<p>Entrainment is a clever application of Bernoulli’s principle that you encounter frequently without realizing it. It’s about using the energy in one fluid stream to move another, often leveraging a pressure difference.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="applications-velocity-measurement" class="slide level2">
<h2>Applications: Velocity Measurement</h2>
<ul>
<li>Devices like the Pitot tube use Bernoulli’s principle to measure fluid velocity.</li>
<li>By creating a “dead spot” (zero velocity) at one opening and measuring pressure at a point of flow, the pressure difference can be related to fluid speed. <span class="math display">\[ p_1 = p_2 + \frac{1}{2} \rho v_2^2 \implies \frac{1}{2} \rho v_2^2 = p_1 - p_2 \]</span> <span class="math display">\[ v_2 = \sqrt{\frac{2(p_1 - p_2)}{\rho}} \]</span></li>
<li>Commonly used as air-speed indicators in aircraft.</li>
</ul>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/0df6619a653545e1cf95ea4b5db9735ff9ca174e" height="250"></p>
<p><em>Figure 14.32: Pitot tube for velocity measurement.</em></p>
<aside class="notes">
<p>Pitot tubes are ubiquitous in aviation and industrial flow measurement. By measuring the difference between static and total pressure, they can accurately determine the fluid velocity. It’s a direct application of converting kinetic energy into pressure.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="chapter-14.7-viscosity-and-turbulence" class="slide level2">
<h2>Chapter 14.7: Viscosity and Turbulence</h2>
<h3 id="learning-objectives-6">Learning Objectives</h3>
<p>By the end of this section, you will be able to:</p>
<ul>
<li>Explain what viscosity is.</li>
<li>Calculate flow and resistance with Poiseuille’s law.</li>
<li>Explain how pressure drops due to resistance.</li>
<li>Calculate the Reynolds number for an object moving through a fluid.</li>
<li>Use the Reynolds number for a system to determine whether it is laminar or turbulent.</li>
<li>Describe the conditions under which an object has a terminal speed.</li>
</ul>
<aside class="notes">
<p>Until now, we’ve often idealized fluids as “frictionless.” In reality, fluids have internal friction, known as viscosity, and their flow can become chaotic, or turbulent. This section will delve into these real-world complexities, introducing viscosity, Poiseuille’s law, and the Reynolds number to characterize fluid flow.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="viscosity-and-laminar-flow" class="slide level2">
<h2>Viscosity and Laminar Flow</h2>
<ul>
<li><strong>Viscosity (<span class="math inline">\(\eta\)</span>):</strong> A measure of internal friction within a fluid and between fluid and surroundings.
<ul>
<li>Juice has low viscosity; maple syrup has high viscosity.</li>
</ul></li>
<li><strong>Laminar Flow:</strong> Fluid layers slide smoothly past each other without mixing.</li>
<li><strong>Turbulence:</strong> Chaotic fluid flow with eddies and swirls, layers mix.
<ul>
<li>Caused by obstructions or high fluid speeds.</li>
</ul></li>
</ul>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/3ca554f2750942908ec411c5f0769e9c89d50fb8" height="200"></p>
<p><em>Figure 14.34: (a) Laminar flow (b) Turbulent flow.</em></p>
<aside class="notes">
<p>Viscosity is essentially “fluid friction.” It’s why some liquids flow easily and others are “thick.” Laminar flow is ordered and predictable, while turbulent flow is messy and complex. Recognizing these flow types is crucial for understanding fluid behavior in real-world applications.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="measuring-viscosity" class="slide level2">
<h2>Measuring Viscosity</h2>
<ul>
<li>Viscosity (<span class="math inline">\(\eta\)</span>) is defined by applying a force <span class="math inline">\(F\)</span> to move a top plate over a stationary bottom plate, with fluid in between. <span class="math display">\[ F = \eta \frac{Av}{L} \]</span>
<ul>
<li><span class="math inline">\(A\)</span>: area of the plates.</li>
<li><span class="math inline">\(v\)</span>: velocity of the top plate.</li>
<li><span class="math inline">\(L\)</span>: distance between plates.</li>
</ul></li>
<li>Solving for viscosity: <span class="math display">\[ \eta = \frac{FL}{Av} \]</span></li>
<li><strong>SI Unit:</strong> <span class="math inline">\(\text{Pa} \cdot \text{s}\)</span> (Pascal-second).</li>
</ul>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/68914b30783b6950085cbbd7778becc71b67827d" height="200"></p>
<p><em>Figure 14.36: Setup for measuring viscosity.</em></p>
<aside class="notes">
<p>This setup provides a precise way to quantify viscosity. The force required to maintain a constant velocity directly depends on the fluid’s internal friction. Different fluids, even at the same temperature, can have vastly different viscosities.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="poiseuilles-law-for-laminar-flow-in-tubes" class="slide level2">
<h2>Poiseuille’s Law for Laminar Flow in Tubes</h2>
<ul>
<li>Flow rate (<span class="math inline">\(Q\)</span>) in a horizontal tube is driven by a pressure difference (<span class="math inline">\(\Delta p = p_2 - p_1\)</span>) and opposed by resistance (<span class="math inline">\(R\)</span>). <span class="math display">\[ Q = \frac{\Delta p}{R} \]</span></li>
<li>For laminar flow in a uniform tube of radius <span class="math inline">\(r\)</span> and length <span class="math inline">\(l\)</span> with fluid viscosity <span class="math inline">\(\eta\)</span>, the <strong>resistance (<span class="math inline">\(R\)</span>)</strong> is: <span class="math display">\[ R = \frac{8 \eta l}{\pi r^4} \]</span></li>
<li>Combining these gives <strong>Poiseuille’s Law</strong> for flow rate: <span class="math display">\[ Q = \frac{(p_2 - p_1) \pi r^4}{8 \eta l} \]</span></li>
</ul>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/9f7c1666768bcf0316fd91d04d946b89a1d6b131" height="200"></p>
<p><em>Figure 14.38: Laminar flow in a pipe.</em></p>
<aside class="notes">
<p>Poiseuille’s law is a powerful equation for understanding fluid flow in pipes, like blood flow in arteries. Notice the <span class="math inline">\(r^4\)</span> term – this means that even small changes in the tube’s radius have a huge impact on flow rate. This is critical in medicine for understanding blood pressure and circulation.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="example-air-conditioning-system-flow-rate" class="slide level2 scrollable">
<h2>Example: Air Conditioning System Flow Rate</h2>
<p><strong>Problem:</strong> An AC system delivers air at gauge pressure 0.054 Pa (<span class="math inline">\(20^\circ\text{C}\)</span>). Conduit: <span class="math inline">\(D = 18.00 \text{ cm}\)</span>, <span class="math inline">\(L = 20 \text{ m}\)</span>. Room: <span class="math inline">\(12 \text{ m} \times 6 \text{ m} \times 3 \text{ m}\)</span>.</p>
<ol type="a">
<li>Volume flow rate assuming laminar flow?</li>
<li>Time to replace air in the room?</li>
<li>New flow rate if conduit <span class="math inline">\(D = 9.00 \text{ cm}\)</span>?</li>
</ol>
<p><strong>Given:</strong></p>
<p><span class="math inline">\(\Delta p = 0.054 \text{ Pa}\)</span></p>
<p><span class="math inline">\(\eta_{air} = 0.0181 \times 10^{-3} \text{ Pa} \cdot \text{s}\)</span> (from Table 14.4)</p>
<p><strong>Solution (a):</strong></p>
<p><span class="math inline">\(r = D/2 = 9.00 \text{ cm} = 0.09 \text{ m}\)</span></p>
<p><span class="math inline">\(Q = \frac{\Delta p \pi r^4}{8 \eta l} = \frac{(0.054 \text{ Pa}) \pi (0.09 \text{ m})^4}{8 (0.0181 \times 10^{-3} \text{ Pa} \cdot \text{s}) (20 \text{ m})} = 3.84 \times 10^{-3} \text{ m}^3/\text{s}\)</span>.</p>
<p><strong>Solution (b):</strong></p>
<p><span class="math inline">\(V_{room} = (12 \text{ m})(6 \text{ m})(3 \text{ m}) = 216 \text{ m}^3\)</span></p>
<p><span class="math inline">\(\Delta t = \frac{V_{room}}{Q} = \frac{216 \text{ m}^3}{3.84 \times 10^{-3} \text{ m}^3/\text{s}} = 5.63 \times 10^4 \text{ s} \approx 15.6 \text{ hours}\)</span>.</p>
<p><strong>Solution (c):</strong></p>
<p>New radius <span class="math inline">\(r' = 4.50 \text{ cm} = 0.045 \text{ m}\)</span> (half the original).</p>
<p>Since <span class="math inline">\(Q \propto r^4\)</span>, the new flow rate will be <span class="math inline">\(\left(\frac{r'}{r}\right)^4 Q = \left(\frac{0.045}{0.09}\right)^4 Q = \left(\frac{1}{2}\right)^4 Q = \frac{1}{16} Q\)</span>.</p>
<p><span class="math inline">\(Q' = \frac{1}{16} (3.84 \times 10^{-3} \text{ m}^3/\text{s}) = 2.40 \times 10^{-4} \text{ m}^3/\text{s}\)</span>.</p>
<aside class="notes">
<p>This example clearly shows the dramatic effect of tube radius on flow rate due to the <span class="math inline">\(r^4\)</span> dependence in Poiseuille’s law. Halving the diameter reduces the flow to one-sixteenth, significantly impacting the air turnover time in the room. This highlights why pipe sizing is critical in engineering.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="flow-and-resistance-as-causes-of-pressure-drops" class="slide level2">
<h2>Flow and Resistance as Causes of Pressure Drops</h2>
<ul>
<li>Pressure drops occur due to fluid flow encountering resistance. <span class="math display">\[ p_2 - p_1 = R Q \]</span></li>
<li>This equation is valid for both laminar and turbulent flows.</li>
<li><strong>Consequences:</strong>
<ul>
<li>During heavy use (high <span class="math inline">\(Q\)</span>), the pressure drop (<span class="math inline">\(p_2 - p_1\)</span>) is large, leading to lower pressure (<span class="math inline">\(p_1\)</span>) for users.</li>
<li>Resistance (<span class="math inline">\(R\)</span>) is much greater in narrow sections, causing larger pressure drops there.</li>
<li>Turbulence greatly increases <span class="math inline">\(R\)</span>, leading to significant pressure reduction downstream.</li>
</ul></li>
</ul>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/1fdfa6cf138838596e1422dade8785377ce291bc" height="200"></p>
<p><em>Figure 14.39: Pressure drop in a water main.</em></p>
<aside class="notes">
<p>This equation quantifies why water pressure drops when many people use water simultaneously, or why a blocked artery reduces blood flow and creates pressure issues. Resistance is the key factor in these pressure losses.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="measuring-turbulence-the-reynolds-number" class="slide level2">
<h2>Measuring Turbulence: The Reynolds Number</h2>
<ul>
<li><strong>Reynolds Number (<span class="math inline">\(N_R\)</span>):</strong> A dimensionless quantity that indicates whether flow is laminar or turbulent. <span class="math display">\[ N_R = \frac{2 \rho v r}{\eta} \quad (\text{for flow in a tube}) \]</span>
<ul>
<li><span class="math inline">\(\rho\)</span>: fluid density.</li>
<li><span class="math inline">\(v\)</span>: fluid speed.</li>
<li><span class="math inline">\(r\)</span>: tube radius.</li>
<li><span class="math inline">\(\eta\)</span>: fluid viscosity.</li>
</ul></li>
<li><strong>Turbulence Thresholds:</strong>
<ul>
<li><span class="math inline">\(N_R &lt; 2000\)</span>: Laminar flow.</li>
<li><span class="math inline">\(N_R &gt; 3000\)</span>: Turbulent flow.</li>
<li><span class="math inline">\(2000 &lt; N_R &lt; 3000\)</span>: Unstable flow (can be laminar but easily becomes turbulent).</li>
</ul></li>
</ul>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Turbulence leads to increased energy dissipation (lost as heat and eddies), making flow less efficient.</p>
</div>
</div>
</div>
<aside class="notes">
<p>The Reynolds number is an incredibly useful parameter in fluid dynamics. It allows engineers to predict and design systems to avoid unwanted turbulence, which can waste energy and cause wear. The transition region is particularly tricky, showcasing chaotic behavior where small disturbances can have large effects.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="example-turbulent-flow-or-laminar-flow" class="slide level2 scrollable">
<h2>Example: Turbulent Flow or Laminar Flow?</h2>
<p><strong>Problem:</strong> For the AC system (conduit <span class="math inline">\(D = 18.00 \text{ cm}\)</span>) from Example 14.8, we found <span class="math inline">\(Q = 3.84 \times 10^{-3} \text{ m}^3/\text{s}\)</span>.</p>
<ol type="a">
<li>Was the assumption of laminar flow valid?</li>
<li>At what velocity would the flow become turbulent?</li>
</ol>
<p><strong>Given:</strong></p>
<p><span class="math inline">\(Q = 3.84 \times 10^{-3} \text{ m}^3/\text{s}\)</span></p>
<p><span class="math inline">\(r = 0.09 \text{ m}\)</span></p>
<p><span class="math inline">\(\rho_{air} = 1.23 \text{ kg/m}^3\)</span> (from Table 14.1 at <span class="math inline">\(0^\circ\text{C}\)</span>, but usually taken as <span class="math inline">\(1.29 \text{ kg/m}^3\)</span> for air, use <span class="math inline">\(1.23 \text{ kg/m}^3\)</span> as given in prompt)</p>
<p><span class="math inline">\(\eta_{air} = 0.0181 \times 10^{-3} \text{ Pa} \cdot \text{s}\)</span></p>
<p><strong>Solution (a):</strong></p>
<p>First, find velocity <span class="math inline">\(v = \frac{Q}{\pi r^2} = \frac{3.84 \times 10^{-3} \text{ m}^3/\text{s}}{\pi (0.09 \text{ m})^2} = 0.15 \text{ m/s}\)</span>.</p>
<p>Now, calculate Reynolds number:</p>
<p><span class="math inline">\(N_R = \frac{2 \rho v r}{\eta} = \frac{2 (1.23 \text{ kg/m}^3) (0.15 \text{ m/s}) (0.09 \text{ m})}{0.0181 \times 10^{-3} \text{ Pa} \cdot \text{s}} = 1835\)</span>.</p>
<p>Since <span class="math inline">\(N_R = 1835 &lt; 2000\)</span>, the flow is laminar. The assumption was valid.</p>
<p><strong>Solution (b):</strong></p>
<p>Flow becomes turbulent when <span class="math inline">\(N_R \approx 2000\)</span>.</p>
<p><span class="math inline">\(v = \frac{N_R \eta}{2 \rho r} = \frac{2000 (0.0181 \times 10^{-3} \text{ Pa} \cdot \text{s})}{2 (1.23 \text{ kg/m}^3) (0.09 \text{ m})} = 0.16 \text{ m/s}\)</span>.</p>
<aside class="notes">
<p>This example shows how to use the Reynolds number to verify assumptions about flow behavior. It’s important for designers to keep flow laminar if efficiency is desired, as exceeding the critical Reynolds number will lead to turbulent flow and wasted energy.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="key-takeaways" class="slide level2">
<h2>Key Takeaways</h2>
<ul>
<li><strong>Phases of Matter:</strong> Solids are rigid, liquids flow and maintain volume, gases expand and are compressible.</li>
<li><strong>Density (<span class="math inline">\(\rho = m/V\)</span>):</strong> Mass per unit volume; determines floating/sinking. Pressure always pushes perpendicular to surfaces.</li>
<li><strong>Pressure (<span class="math inline">\(p = F/A\)</span>):</strong> Force per unit area. <span class="math inline">\(p = p_0 + \rho g h\)</span> for static fluids of constant density.</li>
<li><strong>Pascal’s Principle:</strong> Pressure changes in enclosed fluids transmit undiminished; basis for hydraulics (<span class="math inline">\(F_1/A_1 = F_2/A_2\)</span>).</li>
<li><strong>Archimedes’ Principle:</strong> Buoyant force equals weight of fluid displaced (<span class="math inline">\(F_B = w_{fl}\)</span>).</li>
<li><strong>Flow Rate (<span class="math inline">\(Q = Av\)</span>):</strong> Volume of fluid per unit time.</li>
<li><strong>Equation of Continuity (<span class="math inline">\(A_1 v_1 = A_2 v_2\)</span>):</strong> For incompressible fluids, speed increases as area decreases.</li>
<li><strong>Bernoulli’s Equation (<span class="math inline">\(p + \frac{1}{2} \rho v^2 + \rho g y = \text{constant}\)</span>):</strong> Conservation of energy for ideal fluids, linking pressure, velocity, and height.</li>
<li><strong>Viscosity (<span class="math inline">\(\eta\)</span>):</strong> Fluid friction; higher viscosity means slower flow.</li>
<li><strong>Poiseuille’s Law (<span class="math inline">\(Q = \frac{\Delta p \pi r^4}{8 \eta l}\)</span>):</strong> Describes laminar flow rate in tubes; flow is highly sensitive to radius (<span class="math inline">\(r^4\)</span>).</li>
<li><strong>Reynolds Number (<span class="math inline">\(N_R = \frac{2 \rho v r}{\eta}\)</span>):</strong> Predicts laminar (<span class="math inline">\(&lt;2000\)</span>) vs.&nbsp;turbulent (<span class="math inline">\(&gt;3000\)</span>) flow.</li>
</ul>
<aside class="notes">
<p>This slide summarizes the core concepts of this chapter. It’s a quick reference for the most important definitions, principles, and equations. Make sure you understand each of these points.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="key-equations" class="slide level2">
<h2>Key Equations</h2>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Equation</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\rho = \frac{m}{V}\)</span></td>
<td>Definition of density</td>
</tr>
<tr class="even">
<td><span class="math inline">\(p = \frac{F}{A}\)</span></td>
<td>Definition of pressure</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(p = p_0 + \rho g h\)</span></td>
<td>Pressure at a depth <em>h</em> in a fluid of constant density</td>
</tr>
<tr class="even">
<td><span class="math inline">\(p_{abs} = p_g + p_{atm}\)</span></td>
<td>Relationship between absolute and gauge pressure</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\frac{F_1}{A_1} = \frac{F_2}{A_2}\)</span></td>
<td>Pascal’s principle in a hydraulic system</td>
</tr>
<tr class="even">
<td><span class="math inline">\(F_B = w_{fl}\)</span></td>
<td>Archimedes’ principle (buoyant force)</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\text{fraction submerged} = \frac{\rho_{obj}}{\rho_{fl}}\)</span></td>
<td>Fraction of a floating object submerged</td>
</tr>
<tr class="even">
<td><span class="math inline">\(Q = Av\)</span></td>
<td>Volume flow rate</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(A_1 v_1 = A_2 v_2\)</span></td>
<td>Equation of continuity (for incompressible fluids)</td>
</tr>
<tr class="even">
<td><span class="math inline">\(p + \frac{1}{2} \rho v^2 + \rho g y = \text{constant}\)</span></td>
<td>Bernoulli’s equation</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(Q = \frac{(p_2 - p_1) \pi r^4}{8 \eta l}\)</span></td>
<td>Poiseuille’s law for laminar flow</td>
</tr>
<tr class="even">
<td><span class="math inline">\(N_R = \frac{2 \rho v r}{\eta}\)</span></td>
<td>Reynolds number (for flow in a tube)</td>
</tr>
</tbody>
</table>
<aside class="notes">
<p>This table brings together all the major equations we’ve covered. It’s a handy cheat sheet for solving problems and remembering the mathematical relationships between fluid properties.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="key-terms" class="slide level2">
<h2>Key Terms</h2>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Term</th>
<th>Definition</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Absolute Pressure</strong></td>
<td>The sum of gauge pressure and atmospheric pressure.</td>
</tr>
<tr class="even">
<td><strong>Archimedes’ Principle</strong></td>
<td>The buoyant force on an object equals the weight of the fluid it displaces.</td>
</tr>
<tr class="odd">
<td><strong>Bernoulli’s Equation</strong></td>
<td>States that the sum of pressure, kinetic energy density, and potential energy density is constant along a streamline for an ideal fluid.</td>
</tr>
<tr class="even">
<td><strong>Buoyant Force</strong></td>
<td>The upward force on an object in a fluid.</td>
</tr>
<tr class="odd">
<td><strong>Density (<span class="math inline">\(\rho\)</span>)</strong></td>
<td>Mass per unit volume.</td>
</tr>
<tr class="even">
<td><strong>Fluid Dynamics</strong></td>
<td>The study of fluids in motion.</td>
</tr>
<tr class="odd">
<td><strong>Flow Rate (<span class="math inline">\(Q\)</span>)</strong></td>
<td>Volume of fluid passing a point per unit time.</td>
</tr>
<tr class="even">
<td><strong>Gauge Pressure</strong></td>
<td>Pressure relative to atmospheric pressure.</td>
</tr>
<tr class="odd">
<td><strong>Incompressible Fluid</strong></td>
<td>A fluid whose volume changes negligibly with pressure.</td>
</tr>
<tr class="even">
<td><strong>Laminar Flow</strong></td>
<td>Smooth, orderly fluid flow in layers without mixing.</td>
</tr>
<tr class="odd">
<td><strong>Manometer</strong></td>
<td>A device for measuring pressure using a column of fluid.</td>
</tr>
<tr class="even">
<td><strong>Pascal’s Principle</strong></td>
<td>A change in pressure applied to an enclosed fluid is transmitted undiminished throughout the fluid.</td>
</tr>
<tr class="odd">
<td><strong>Poiseuille’s Law</strong></td>
<td>Describes the laminar flow rate of a viscous fluid through a tube.</td>
</tr>
<tr class="even">
<td><strong>Pressure (<span class="math inline">\(p\)</span>)</strong></td>
<td>Force per unit area.</td>
</tr>
<tr class="odd">
<td><strong>Reynolds Number (<span class="math inline">\(N_R\)</span>)</strong></td>
<td>A dimensionless quantity that predicts the onset of turbulence.</td>
</tr>
<tr class="even">
<td><strong>Specific Gravity</strong></td>
<td>Ratio of a substance’s density to water’s density at <span class="math inline">\(4.0^\circ\text{C}\)</span>.</td>
</tr>
<tr class="odd">
<td><strong>Streamline</strong></td>
<td>The path followed by a small element of fluid.</td>
</tr>
<tr class="even">
<td><strong>Turbulence</strong></td>
<td>Chaotic, irregular fluid flow with eddies and swirls.</td>
</tr>
<tr class="odd">
<td><strong>Viscosity (<span class="math inline">\(\eta\)</span>)</strong></td>
<td>A measure of a fluid’s internal friction or resistance to flow.</td>
</tr>
</tbody>
</table>
<aside class="notes">
<p>Familiarize yourself with these terms. A strong vocabulary is essential for understanding the concepts and communicating effectively in physics.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>


<script type="ojs-module-contents">
eyJjb250ZW50cyI6W119
</script>
<div id="exercise-loading-indicator" class="exercise-loading-indicator d-none d-flex align-items-center gap-2">
<div id="exercise-loading-status" class="d-flex gap-2">

</div>
<div class="spinner-grow spinner-grow-sm">

</div>
</div>
<script type="vfs-file">
W10=
</script>
</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="../qrjs_pics/unsoed_logo.png" class="slide-logo"></p>
<div class="footer footer-default">
<p><a href="https://imron-slide.vercel.app">irosyadi-2025</a></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': false,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: true,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script type="ojs-module-contents">
    eyJjb250ZW50cyI6W119
    </script>
    <script type="module">
    if (window.location.protocol === "file:") { alert("The OJS runtime does not work with file:// URLs. Please use a web server to view this document."); }
    window._ojs.paths.runtimeToDoc = "../../book_1";
    window._ojs.paths.runtimeToRoot = "../..";
    window._ojs.paths.docToRoot = "..";
    window._ojs.selfContained = false;
    window._ojs.runtime.interpretFromScriptTags();
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>