<!DOCTYPE html>
<html lang="en"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/quarto-contrib/live-runtime/live-runtime.js" type="module"></script>
<link href="../site_libs/quarto-contrib/live-runtime/live-runtime.css" rel="stylesheet"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.25">

  <meta name="author" content="Imron Rosyadi">
  <title>Physics</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-b0356e9119c1bdfd0db189d130feb51c.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <script type="module" src="../site_libs/quarto-ojs/quarto-ojs-runtime.js"></script>
  <link href="../site_libs/quarto-ojs/quarto-ojs.css" rel="stylesheet">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Physics</h1>
  <p class="subtitle">Chapter 4 The Second Law of Thermodynamics</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Imron Rosyadi 
</div>
</div>
</div>

</section>
<section id="introduction" class="slide level2">
<h2><strong>Introduction</strong></h2>
<p>The <strong>Second Law of Thermodynamics</strong> explains the direction of natural processes.</p>
<p>It helps us understand why some events spontaneously occur and others don’t.</p>
<p>This law introduces <strong>entropy</strong> as a fundamental concept related to disorder and energy dispersal.</p>
</section>
<section id="reversible-and-irreversible-processes" class="slide level2">
<h2><strong>4.1 Reversible and Irreversible Processes</strong></h2>
<h3 id="learning-objectives"><strong>Learning Objectives</strong></h3>
<ul>
<li>Define reversible and irreversible processes.</li>
<li>State the second law of thermodynamics via an irreversible process.</li>
</ul>
</section>
<section id="reversible-and-irreversible-processes-free-expansion" class="slide level2">
<h2><strong>4.1 Reversible and Irreversible Processes: Free Expansion</strong></h2>
<div class="columns">
<div class="column" style="width:50%;">
<p>Imagine an ideal gas in one half of a thermally insulated container.</p>
<p>The other half is a vacuum.</p>
<p>If the wall is removed, the gas expands to fill the entire container.</p>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/e7b2c51b69aabd2430989b9b70c958f1e8368480" height="250"></p>
<p><em>Figure 4.2 A gas expanding from half of a container to the entire container (a) before and (b) after the wall in the middle is removed.</em></p>
</div><div class="column" style="width:50%;">
<ul>
<li><strong>Work done (W):</strong> Since the other half is a vacuum, no force is exerted, so <span class="math inline">\(W=0\)</span>.</li>
<li><strong>Heat transfer (Q):</strong> The container is thermally insulated, so <span class="math inline">\(Q=0\)</span>.</li>
<li><strong>First Law:</strong> <span class="math inline">\(\Delta E_{int} = Q - W = 0\)</span>.
<ul>
<li>For an ideal gas, <span class="math inline">\(\Delta E_{int} = 0\)</span> means <strong>temperature (T) is constant</strong>.</li>
<li>Pressure halves as volume doubles: <span class="math inline">\(p = p_0/2\)</span>.</li>
</ul></li>
</ul>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Can the gas spontaneously return to its original half?</p>
<p>Our intuition says <strong>no</strong>. This process is <strong>irreversible</strong>.</p>
</div>
</div>
</div>
</div></div>
<aside class="notes">
<ul>
<li>Start by clearly defining the setup for free expansion: gas in one half, vacuum in the other, insulated container.</li>
<li>Explain why work done and heat transfer are zero.</li>
<li>Connect this to the first law of thermodynamics and its implications for internal energy and temperature of an ideal gas.</li>
<li>Highlight the change in pressure and volume.</li>
<li>Pose the question about the gas returning to its original state to introduce the concept of reversibility.</li>
<li>Emphasize that while the first law doesn’t explicitly forbid it, our intuition and observation point to it being unlikely.</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="reversible-and-irreversible-processes-definitions" class="slide level2">
<h2><strong>4.1 Reversible and Irreversible Processes: Definitions</strong></h2>
<ul>
<li><strong>Reversible Process:</strong>
<ul>
<li>A process where both the system and its environment can be restored to their exact initial states.</li>
<li>Requires the process to be <strong>quasi-static</strong> (system always near equilibrium).</li>
<li>Idealized processes, rarely seen in reality.</li>
<li>Example: Slow, isothermal expansion against a piston, where heat is continuously exchanged to maintain constant temperature.</li>
</ul></li>
<li><strong>Irreversible Process:</strong>
<ul>
<li>A process where the system and/or its environment <em>cannot</em> be restored to their original states simultaneously.</li>
<li>Almost all real-world processes are irreversible (e.g., friction, heat transfer across finite temperature differences).</li>
<li>Often called “natural processes.”</li>
<li>Characterized by <strong>finite gradients</strong> (e.g., temperature difference for heat flow).</li>
</ul></li>
</ul>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>Think of breaking a glass: easy to break (irreversible), impossible to put back exactly as it was without external changes.</p>
</div>
</div>
</div>
<aside class="notes">
<ul>
<li>Clearly define a reversible process, emphasizing the “system AND environment” aspect and the quasi-static requirement.</li>
<li>Provide a simple example of a nearly reversible process.</li>
<li>Define an irreversible process, highlighting that it’s what we encounter in reality and the inability to restore both system and environment.</li>
<li>Explain the role of finite gradients in irreversibility (e.g., heat flowing from hot to cold).</li>
<li>Use the analogy of breaking glass to make the concept more relatable and memorable.</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="reversible-and-irreversible-processes-microscopic-view" class="slide level2">
<h2><strong>4.1 Reversible and Irreversible Processes: Microscopic View</strong></h2>
<ul>
<li>From a microscopic view, individual particle motions are reversible (Newton’s Laws).</li>
<li>However, in macroscopic systems (<span class="math inline">\(&gt;10^{23}\)</span> particles), numerous collisions <strong>erase memory</strong> of initial states.</li>
<li>The probability of all particles spontaneously reversing their paths is astronomically small.
<ul>
<li><strong>Example:</strong> For gas expanded into vacuum, the chance of all molecules returning to the original half is virtually zero.</li>
<li>This is why free expansion is irreversible.</li>
</ul></li>
</ul>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Irreversibility arises from the overwhelming number of possible microscopic arrangements, making the “ordered” initial state incredibly improbable to spontaneously reoccur.</p>
</div>
</div>
</div>
<aside class="notes">
<ul>
<li>Discuss the contrast between microscopic reversibility (Newton’s laws) and macroscopic irreversibility.</li>
<li>Explain that the sheer number of particles in macroscopic systems leads to this effective irreversibility due to the vast phase space.</li>
<li>Reiterate the free expansion example, connecting it to the microscopic probability argument.</li>
<li>Emphasize that irreversibility isn’t about forbidden individual particle motion, but the statistical improbability of collective reversal.</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="reversible-and-irreversible-processes-heat-flow" class="slide level2">
<h2><strong>4.1 Reversible and Irreversible Processes: Heat Flow</strong></h2>
<div class="columns">
<div class="column" style="width:50%;">
<p>Consider two objects in thermal contact:</p>
<ul>
<li>One at temperature <span class="math inline">\(T_2\)</span></li>
<li>The other at temperature <span class="math inline">\(T_1\)</span>, where <span class="math inline">\(T_2 &gt; T_1\)</span>.</li>
</ul>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/ce83c857de4b341ba1200b95ba007f03cd444816" height="200"></p>
<p><em>Figure 4.3 Spontaneous heat flow from an object at higher temperature T2 to another at lower temperature T1.</em></p>
</div><div class="column" style="width:50%;">
<ul>
<li><strong>Observation:</strong> Heat <em>always</em> flows spontaneously from the hotter object to the colder one.
<ul>
<li>Example: Holding ice in your hand (heat leaves hand, enters ice).</li>
<li>Example: Heating a metal rod (heat flows from fire to hand).</li>
</ul></li>
</ul>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong><strong>Second Law of Thermodynamics (Clausius Statement)</strong></strong></p>
</div>
<div class="callout-content">
<p>Heat never flows spontaneously from a colder object to a hotter object.</p>
</div>
</div>
</div>
<ul>
<li>“Spontaneously” means without any external effort.</li>
<li>This statement summarizes empirical observations and is one of several equivalent formulations of the Second Law.</li>
</ul>
</div></div>
<aside class="notes">
<ul>
<li>Introduce the example of heat transfer between two objects at different temperatures.</li>
<li>Relate it to everyday experiences (ice, hot rod) to make it intuitive.</li>
<li>Formally state the Clausius statement of the Second Law, highlighting the word “spontaneously.”</li>
<li>Emphasize that this is an empirical observation and a fundamental principle.</li>
<li>Briefly mention that there are other equivalent statements, which will be covered later.</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="reversible-and-irreversible-processes-summary-of-processes" class="slide level2">
<h2><strong>4.1 Reversible and Irreversible Processes: Summary of Processes</strong></h2>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Process</th>
<th style="text-align: left;">Constant Quantity and Resulting Fact</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Isobaric</td>
<td style="text-align: left;">Constant pressure <span class="math inline">\(W = p\Delta V\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Isochoric</td>
<td style="text-align: left;">Constant volume <span class="math inline">\(W = 0\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Isothermal</td>
<td style="text-align: left;">Constant temperature <span class="math inline">\(\Delta T = 0\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Adiabatic</td>
<td style="text-align: left;">No heat transfer <span class="math inline">\(Q = 0\)</span></td>
</tr>
</tbody>
</table>
<p><em>Table 4.1 Summary of Simple Thermodynamic Processes</em></p>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>These idealized processes are <strong>reversible in principle</strong> because the system can always be considered at equilibrium.</p>
</div>
</div>
</div>
<aside class="notes">
<ul>
<li>Review the four basic thermodynamic processes.</li>
<li>For each, state the constant quantity and a key resulting fact (e.g., work done).</li>
<li>Emphasize that these are “idealized” and “reversible in principle,” connecting back to the quasi-static requirement.</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="heat-engines" class="slide level2">
<h2><strong>4.2 Heat Engines</strong></h2>
<h3 id="learning-objectives-1"><strong>Learning Objectives</strong></h3>
<ul>
<li>Describe the function and components of a heat engine.</li>
<li>Explain the efficiency of an engine.</li>
<li>Calculate the efficiency of an engine for a given cycle of an ideal gas.</li>
</ul>
</section>
<section id="heat-engines-function-and-components" class="slide level2 scrollable">
<h2><strong>4.2 Heat Engines: Function and Components</strong></h2>
<ul>
<li><strong>Heat Engine:</strong> A device that converts thermal energy (heat) into mechanical work.
<ul>
<li>Examples: Steam engines, internal combustion engines, power plants.</li>
</ul></li>
<li><strong>Components:</strong>
<ol type="1">
<li><strong>Heat Source (Hot Reservoir):</strong> Supplies heat (<span class="math inline">\(Q_h\)</span>) at high temperature (<span class="math inline">\(T_h\)</span>).</li>
<li><strong>Working Substance:</strong> Carries out the cycle (e.g., water in a steam engine, gas-air mixture in a car engine).</li>
<li><strong>Engine:</strong> Performs work (<span class="math inline">\(W\)</span>) from absorbed heat.</li>
<li><strong>Heat Sink (Cold Reservoir):</strong> Receives discarded heat (<span class="math inline">\(Q_c\)</span>) at low temperature (<span class="math inline">\(T_c\)</span>).</li>
</ol></li>
</ul>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/b252c90db4cfa3e18ed6a8fd30613efac1dfb21e" height="250"></p>
<p><em>Figure 4.4 A schematic representation of a heat engine. Energy flows from the hot reservoir to the cold reservoir while doing work.</em></p>
<aside class="notes">
<ul>
<li>Start with a clear definition of a heat engine and its purpose.</li>
<li>List the essential components: hot reservoir, cold reservoir, working substance, and the engine itself.</li>
<li>Explain the role of each component, relating them to the schematic diagram.</li>
<li>Emphasize that work is done <em>from</em> absorbed heat, and some heat is <em>always</em> discarded.</li>
<li>Briefly mention the sign convention for heat and work in engine diagrams (amounts, directions shown by arrows).</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="heat-engines-energy-conservation-and-efficiency" class="slide level2">
<h2><strong>4.2 Heat Engines: Energy Conservation and Efficiency</strong></h2>
<ul>
<li><p>Heat engines operate in <strong>cycles</strong>.</p>
<ul>
<li>After one cycle, the working substance returns to its initial state.</li>
<li>Therefore, <span class="math inline">\(\Delta E_{int} = 0\)</span> for a complete cycle.</li>
</ul></li>
<li><p><strong>First Law of Thermodynamics for a Cycle:</strong></p>
<p><span class="math inline">\(W = Q_{net} - \Delta E_{int}\)</span></p>
<p><span class="math inline">\(W = Q_h - Q_c - 0\)</span></p>
<p><span class="math display">\[W = Q_h - Q_c\]</span></p>
<ul>
<li><span class="math inline">\(Q_h\)</span>: Heat absorbed from hot reservoir.</li>
<li><span class="math inline">\(Q_c\)</span>: Heat discarded to cold reservoir.</li>
<li><span class="math inline">\(W\)</span>: Net work done by the engine.</li>
</ul></li>
<li><p><strong>Efficiency (<span class="math inline">\(e\)</span>):</strong> “What we get out” divided by “what we put in.” <span class="math display">\[e = \frac{W_{out}}{Q_{in}} = \frac{W}{Q_h}\]</span> Substituting <span class="math inline">\(W = Q_h - Q_c\)</span>: <span class="math display">\[e = \frac{Q_h - Q_c}{Q_h} = 1 - \frac{Q_c}{Q_h}\]</span></p></li>
</ul>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p>A heat engine <strong>cannot</strong> be 100% efficient (<span class="math inline">\(Q_c\)</span> can never be zero). This is a consequence of the Second Law.</p>
</div>
</div>
</div>
<aside class="notes">
<ul>
<li>Explain the significance of cyclic operation for a heat engine, leading to <span class="math inline">\(\Delta E_{int} = 0\)</span>.</li>
<li>Apply the First Law to derive the relationship between work, <span class="math inline">\(Q_h\)</span>, and <span class="math inline">\(Q_c\)</span>.</li>
<li>Define thermal efficiency intuitively (“what you get out / what you put in”).</li>
<li>Show the derivation of the efficiency formula in terms of <span class="math inline">\(Q_h\)</span> and <span class="math inline">\(Q_c\)</span>.</li>
<li>Pre-emptively state the limitation on 100% efficiency, linking it to the Second Law.</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="heat-engines-example---a-lawn-mower" class="slide level2">
<h2><strong>4.2 Heat Engines: Example - A Lawn Mower</strong></h2>
<p>A lawn mower has an efficiency of 25.0% and an average power of 3.00 kW. What are (a) the average work done and (b) the minimum heat discharge into the air by the lawn mower in one minute of use?</p>
<p><strong>Given:</strong></p>
<p><span class="math inline">\(e = 0.250\)</span></p>
<p><span class="math inline">\(P = 3.00 \text{ kW} = 3000 \text{ J/s}\)</span></p>
<p><span class="math inline">\(\Delta t = 1 \text{ min} = 60 \text{ s}\)</span></p>
<p><strong>Solution:</strong></p>
<p><strong>(a) Average work delivered (W):</strong></p>
<p><span class="math inline">\(W = P \times \Delta t\)</span></p>
<p><span class="math inline">\(W = (3000 \text{ J/s}) \times (60 \text{ s})\)</span></p>
<p><span class="math inline">\(W = 180,000 \text{ J} = 180 \text{ kJ}\)</span></p>
<p><strong>(b) Minimum heat discharged (<span class="math inline">\(Q_c\)</span>):</strong></p>
<p>We know <span class="math inline">\(e = \frac{W}{Q_h}\)</span>, so <span class="math inline">\(Q_h = \frac{W}{e}\)</span>.</p>
<p><span class="math inline">\(Q_h = \frac{180 \text{ kJ}}{0.250} = 720 \text{ kJ}\)</span></p>
<p>From <span class="math inline">\(W = Q_h - Q_c\)</span>, we get <span class="math inline">\(Q_c = Q_h - W\)</span>.</p>
<p><span class="math inline">\(Q_c = 720 \text{ kJ} - 180 \text{ kJ}\)</span></p>
<p><span class="math inline">\(Q_c = 540 \text{ kJ}\)</span></p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Alternatively, use <span class="math inline">\(Q_c = Q_h(1-e)\)</span>.</p>
<p><span class="math inline">\(Q_c = (720 \text{ kJ})(1 - 0.250) = (720 \text{ kJ})(0.750) = 540 \text{ kJ}\)</span></p>
<p>The minimum heat discharge is <span class="math inline">\(540 \text{ kJ}\)</span>.</p>
</div>
</div>
</div>
<aside class="notes">
<ul>
<li>Clearly state the problem and list the given values.</li>
<li>Break down the solution into two parts, (a) and (b).</li>
<li>For part (a), show the calculation of work using power and time.</li>
<li>For part (b), demonstrate two methods to calculate <span class="math inline">\(Q_c\)</span>:
<ul>
<li>Method 1: Calculate <span class="math inline">\(Q_h\)</span> first, then use <span class="math inline">\(Q_c = Q_h - W\)</span>.</li>
<li>Method 2: Use the efficiency definition <span class="math inline">\(e = W/Q_h\)</span> to relate <span class="math inline">\(Q_c\)</span> directly.</li>
</ul></li>
<li>Emphasize the significance: higher efficiency means less waste heat, which is better for the environment.</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="refrigerators-and-heat-pumps" class="slide level2">
<h2><strong>4.3 Refrigerators and Heat Pumps</strong></h2>
<h3 id="learning-objectives-2"><strong>Learning Objectives</strong></h3>
<ul>
<li>Describe a refrigerator and a heat pump and list their differences.</li>
<li>Calculate the performance coefficients of simple refrigerators and heat pumps.</li>
</ul>
</section>
<section id="refrigerators-and-heat-pumps-overview" class="slide level2">
<h2><strong>4.3 Refrigerators and Heat Pumps: Overview</strong></h2>
<ul>
<li><strong>Reversed Heat Engines:</strong> Refrigerators and heat pumps are essentially heat engines operating in reverse.
<ul>
<li>They require <strong>work input</strong> (<span class="math inline">\(W\)</span>) to transfer heat from a colder region to a hotter region.</li>
</ul></li>
</ul>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/c46b7cdb846736d193ab7b06e0cf671dfff3b0da" height="250"></p>
<p><em>Figure 4.6 A schematic representation of a refrigerator (or a heat pump). The arrow next to work (W) indicates work being put into the system.</em></p>
<ul>
<li><strong>Refrigerator:</strong>
<ul>
<li><strong>Purpose:</strong> To <strong>remove heat (<span class="math inline">\(Q_c\)</span>) from a cold reservoir</strong> (e.g., inside a fridge, air-conditioned room).</li>
<li>Work is done to move heat <em>against</em> its natural flow (from cold to hot).</li>
</ul></li>
<li><strong>Heat Pump:</strong>
<ul>
<li><strong>Purpose:</strong> To <strong>dump heat (<span class="math inline">\(Q_h\)</span>) into a hot reservoir</strong> (e.g., inside a house during winter).</li>
<li>Also uses work to move heat from a colder outside to a warmer inside.</li>
</ul></li>
</ul>
<aside class="notes">
<ul>
<li>Introduce refrigerators and heat pumps as reversed heat engines.</li>
<li>Highlight the key difference from heat engines: they require work input.</li>
<li>Explain the distinct primary purpose of each:
<ul>
<li>Refrigerator: focusing on removing heat from the cold side.</li>
<li>Heat pump: focusing on delivering heat to the hot side.</li>
</ul></li>
<li>Refer to the schematic to show the direction of heat flows (<span class="math inline">\(Q_c\)</span> absorbed, <span class="math inline">\(Q_h\)</span> discarded) and work input (<span class="math inline">\(W\)</span>).</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="refrigerators-and-heat-pumps-performance-coefficients" class="slide level2">
<h2><strong>4.3 Refrigerators and Heat Pumps: Performance Coefficients</strong></h2>
<ul>
<li><p>Since the focus is on “how much heat is moved for a given work input,” efficiency for these devices is called the <strong>Coefficient of Performance (COP)</strong>.</p></li>
<li><p><strong>For a Refrigerator (<span class="math inline">\(K_R\)</span>):</strong></p>
<ul>
<li>“What we get out” (heat removed from cold reservoir) divided by “what we put in” (work done). <span class="math display">\[K_R = \frac{Q_c}{W}\]</span></li>
<li>Using <span class="math inline">\(W = Q_h - Q_c\)</span> (from the First Law for a cycle, with <span class="math inline">\(W\)</span> now being <em>input</em>): <span class="math display">\[K_R = \frac{Q_c}{Q_h - Q_c}\]</span></li>
<li>Typical <span class="math inline">\(K_R\)</span> values are between 2 and 6.</li>
</ul></li>
<li><p><strong>For a Heat Pump (<span class="math inline">\(K_P\)</span>):</strong></p>
<ul>
<li>“What we get out” (heat delivered to hot reservoir) divided by “what we put in” (work done). <span class="math display">\[K_P = \frac{Q_h}{W}\]</span></li>
<li>Using <span class="math inline">\(W = Q_h - Q_c\)</span>: <span class="math display">\[K_P = \frac{Q_h}{Q_h - Q_c}\]</span></li>
<li>Typical <span class="math inline">\(K_P\)</span> values are between 3 and 7.</li>
</ul></li>
</ul>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>Note that <span class="math inline">\(K_P = K_R + 1\)</span>. This means a heat pump always delivers more heat to the hot reservoir than it removes from the cold reservoir, because the work input also becomes part of the heat delivered.</p>
</div>
</div>
</div>
<aside class="notes">
<ul>
<li>Explain why “efficiency” isn’t the best term for these devices and introduce “Coefficient of Performance” (COP).</li>
<li>Define <span class="math inline">\(K_R\)</span> for a refrigerator, clearly stating the “get out” and “put in” terms.</li>
<li>Show the derivation of <span class="math inline">\(K_R\)</span> using the First Law.</li>
<li>Define <span class="math inline">\(K_P\)</span> for a heat pump, similarly.</li>
<li>Show the derivation of <span class="math inline">\(K_P\)</span>.</li>
<li>Highlight the relationship <span class="math inline">\(K_P = K_R + 1\)</span> as an important takeaway.</li>
<li>Mention typical COP values to give a sense of scale.</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="statements-of-the-second-law-of-thermodynamics" class="slide level2">
<h2><strong>4.4 Statements of the Second Law of Thermodynamics</strong></h2>
<h3 id="learning-objectives-3"><strong>Learning Objectives</strong></h3>
<ul>
<li>Contrast the second law of thermodynamics statements according to Kelvin and Clausius formulations.</li>
<li>Interpret the second of thermodynamics via irreversibility.</li>
</ul>
</section>
<section id="statements-of-the-second-law-clausius-and-kelvin" class="slide level2">
<h2><strong>4.4 Statements of the Second Law: Clausius and Kelvin</strong></h2>
<p>The Second Law of Thermodynamics can be stated in several equivalent ways.</p>
<ul>
<li><strong>Clausius Statement (Heat Flow):</strong>
<ul>
<li>“Heat never flows spontaneously from a colder object to a hotter object.”</li>
<li>Implies that a “perfect refrigerator” (one that transfers heat from cold to hot <em>without work input</em>) is impossible.</li>
</ul></li>
<li><strong>Kelvin Statement (Heat Engines):</strong>
<ul>
<li>“It is impossible to convert the heat from a single source into work without any other effect.”</li>
<li>Implies that a “perfect heat engine” (one that is 100% efficient, converting <em>all</em> heat absorbed into work in a cycle) is impossible.</li>
</ul></li>
</ul>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/4e32d072a5f3f3135ee310d0259636757f93a12d" height="300"></p>
<p><em>Figure 4.8 (a) A “perfect heat engine” converts all input heat into work. (b) A “perfect refrigerator” transports heat from a cold reservoir to a hot reservoir without work input. Neither of these devices is achievable in reality.</em></p>
<aside class="notes">
<ul>
<li>Reiterate that there are multiple equivalent statements of the Second Law.</li>
<li>Present the Clausius statement again, linking it to the impossibility of a perfect refrigerator.</li>
<li>Present the Kelvin statement, linking it to the impossibility of a perfect heat engine (100% efficiency).</li>
<li>Use Figure 4.8 to visually illustrate these “impossible” devices.</li>
<li>Explain the importance of “without any other effect” in the Kelvin statement, emphasizing that it applies to <em>cyclic</em> processes.</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="statements-of-the-second-law-equivalence" class="slide level2 scrollable">
<h2><strong>4.4 Statements of the Second Law: Equivalence</strong></h2>
<p>The Kelvin and Clausius statements are equivalent. This means if one is false, the other must also be false.</p>
<p><strong>Proof (by contradiction):</strong> 1. <strong>Assume Clausius statement is FALSE:</strong> A perfect refrigerator exists (transfers <span class="math inline">\(Q\)</span> from <span class="math inline">\(T_c\)</span> to <span class="math inline">\(T_h\)</span> with <span class="math inline">\(W=0\)</span>). 2. <strong>Combine with a real heat engine:</strong> - Real engine takes <span class="math inline">\(Q_h' = Q + \Delta Q\)</span> from <span class="math inline">\(T_h\)</span>. - Does work <span class="math inline">\(W = \Delta Q\)</span>. - Discards <span class="math inline">\(Q_c' = Q\)</span> to <span class="math inline">\(T_c\)</span>. 3. <strong>Net effect of combined device:</strong> - Net heat removed from <span class="math inline">\(T_h\)</span>: <span class="math inline">\((Q + \Delta Q) - Q = \Delta Q\)</span>. - Net heat transfer to/from <span class="math inline">\(T_c\)</span>: <span class="math inline">\(Q - Q = 0\)</span>. - Net work done: <span class="math inline">\(W = \Delta Q\)</span>.</p>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/6d6dc3d3968f0f58f28ed1a46008ec2e64a142bd" height="250"></p>
<p><em>Figure 4.9 Combining a perfect refrigerator and a real heat engine yields a perfect heat engine because W = <span class="math inline">\(\Delta\)</span>Q.</em></p>
<ol start="4" type="1">
<li>This combined device is a <strong>perfect heat engine</strong> (takes <span class="math inline">\(\Delta Q\)</span> from a single reservoir <span class="math inline">\(T_h\)</span> and converts it all to work <span class="math inline">\(W = \Delta Q\)</span>).</li>
<li>This contradicts the <strong>Kelvin statement</strong>.</li>
<li>Therefore, if the Clausius statement is false, the Kelvin statement is also false. This proves their equivalence.</li>
</ol>
<aside class="notes">
<ul>
<li>Explain the concept of proving equivalence by showing that if one statement is false, the other must also be false.</li>
<li>Walk through the steps of the proof by contradiction:
<ul>
<li>Start by assuming the Clausius statement is false (perfect refrigerator exists).</li>
<li>Introduce a real heat engine.</li>
<li>Combine these two devices conceptually.</li>
<li>Analyze the net heat flows and work done by the combined system.</li>
<li>Show that this combination results in a “perfect heat engine,” which directly contradicts the Kelvin statement.</li>
</ul></li>
<li>Conclude that the initial assumption (Clausius statement is false) must be wrong, thus proving the equivalence.</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="statements-of-the-second-law-efficiency-limits" class="slide level2 scrollable">
<h2><strong>4.4 Statements of the Second Law: Efficiency Limits</strong></h2>
<p>Two important properties of heat engines operating between two heat reservoirs:</p>
<ol type="1">
<li><strong>Reversible engines are more efficient than irreversible engines.</strong>
<ul>
<li><em>Any reversible engine operating between two reservoirs has a greater efficiency than any irreversible engine operating between the same two reservoirs.</em></li>
<li>Proof involves showing that if an irreversible engine were more efficient, it could be combined with a reversible engine (run in reverse as a refrigerator) to violate the Clausius statement.</li>
</ul></li>
<li><strong>All reversible engines have the same efficiency.</strong>
<ul>
<li><em>All reversible engines operating between the same two reservoirs have the same efficiency.</em></li>
<li>Proof involves showing that if two reversible engines had different efficiencies, one could be combined with the other (run in reverse) to violate the Clausius statement.</li>
</ul></li>
</ol>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>These properties are fundamental to understanding the <strong>Carnot efficiency</strong>, which sets the upper limit for heat engine performance.</p>
</div>
</div>
</div>
<aside class="notes">
<ul>
<li>State the two key properties regarding heat engine efficiencies.</li>
<li>Briefly explain the reasoning behind each property, mentioning the use of contradiction and the Clausius statement. Avoid going into full proof detail, as it’s implied the undergraduate audience might not need the full mathematical rigor here.</li>
<li>Connect these properties to the upcoming concept of Carnot efficiency as a “preview.”</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-carnot-cycle" class="slide level2">
<h2><strong>4.5 The Carnot Cycle</strong></h2>
<h3 id="learning-objectives-4"><strong>Learning Objectives</strong></h3>
<ul>
<li>Describe the Carnot cycle with the roles of all four processes involved.</li>
<li>Outline the Carnot principle and its implications.</li>
<li>Demonstrate the equivalence of the Carnot principle and the second law of thermodynamics.</li>
</ul>
</section>
<section id="the-carnot-cycle-overview" class="slide level2">
<h2><strong>4.5 The Carnot Cycle: Overview</strong></h2>
<ul>
<li>Proposed by <strong>Sadi Carnot</strong> in 1824.</li>
<li>A hypothetical <strong>reversible cycle</strong> that achieves the <strong>highest possible efficiency</strong> between two given heat reservoirs (<span class="math inline">\(T_h\)</span> and <span class="math inline">\(T_c\)</span>).</li>
<li>Crucial for theoretical understanding and defining an absolute temperature scale.</li>
<li>Consists of four reversible processes:</li>
</ul>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/b01fcc2bc93d1dc9e88e3c8a6fb15765d79b4b33" height="300"></p>
<p><em>Figure 4.11 The four processes of the Carnot cycle.</em></p>
<aside class="notes">
<ul>
<li>Introduce Sadi Carnot and the significance of his cycle.</li>
<li>Emphasize its theoretical importance as the most efficient possible cycle.</li>
<li>List the four types of processes involved in the cycle.</li>
<li>Refer to Figure 4.11 to show the conceptual steps.</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-carnot-cycle-four-processes" class="slide level2 scrollable">
<h2><strong>4.5 The Carnot Cycle: Four Processes</strong></h2>
<p>Let’s trace the Carnot cycle on a <span class="math inline">\(pV\)</span> diagram, assuming an ideal gas as the working substance.</p>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/5256c262741b3231ef322e36fa22b0d4a64150b5" height="300"></p>
<p><em>Figure 4.12 The total work done by the gas in the Carnot cycle is shown and given by the area enclosed by the loop MNOPM.</em></p>
<ol type="1">
<li><strong>Isothermal Expansion (M to N):</strong>
<ul>
<li>Gas absorbs heat <span class="math inline">\(Q_h\)</span> from hot reservoir (<span class="math inline">\(T_h\)</span>).</li>
<li>Expands at constant <span class="math inline">\(T_h\)</span>, doing work <span class="math inline">\(W_1\)</span>.</li>
<li><span class="math inline">\(\Delta E_{int} = 0\)</span>, so <span class="math inline">\(Q_h = W_1 = nRT_h \ln(\frac{V_N}{V_M})\)</span>.</li>
</ul></li>
<li><strong>Adiabatic Expansion (N to O):</strong>
<ul>
<li>Gas thermally isolated (<span class="math inline">\(Q=0\)</span>).</li>
<li>Expands, doing work <span class="math inline">\(W_2\)</span>, and its temperature drops from <span class="math inline">\(T_h\)</span> to <span class="math inline">\(T_c\)</span>.</li>
<li><span class="math inline">\(T V^{\gamma-1} = \text{constant}\)</span>.</li>
</ul></li>
<li><strong>Isothermal Compression (O to P):</strong>
<ul>
<li>Gas releases heat <span class="math inline">\(Q_c\)</span> to cold reservoir (<span class="math inline">\(T_c\)</span>).</li>
<li>Compressed at constant <span class="math inline">\(T_c\)</span>, work <span class="math inline">\(W_3\)</span> is done <em>on</em> the gas.</li>
<li><span class="math inline">\(\Delta E_{int} = 0\)</span>, so <span class="math inline">\(Q_c = nRT_c \ln(\frac{V_O}{V_P})\)</span>.</li>
</ul></li>
<li><strong>Adiabatic Compression (P to M):</strong>
<ul>
<li>Gas thermally isolated (<span class="math inline">\(Q=0\)</span>).</li>
<li>Compressed, work <span class="math inline">\(W_4\)</span> is done <em>on</em> the gas, and its temperature rises from <span class="math inline">\(T_c\)</span> to <span class="math inline">\(T_h\)</span>.</li>
</ul></li>
</ol>
<aside class="notes">
<ul>
<li>Use Figure 4.12 as the visual aid for the <span class="math inline">\(pV\)</span> diagram.</li>
<li>Go through each of the four steps in detail:
<ul>
<li>Name of the process.</li>
<li>What happens to the gas (heat exchange, work, temperature, volume).</li>
<li>Relevant thermodynamic relationships for ideal gas (e.g., for isothermal, <span class="math inline">\(\Delta E_{int} = 0\)</span>; for adiabatic, <span class="math inline">\(TV^{\gamma-1} = \text{const}\)</span>).</li>
<li>Clearly indicate where <span class="math inline">\(Q_h\)</span> is absorbed and <span class="math inline">\(Q_c\)</span> is rejected.</li>
<li>Mention work done <em>by</em> or <em>on</em> the gas.</li>
</ul></li>
<li>Emphasize that the area enclosed by the loop represents the net work done.</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-carnot-cycle-efficiency" class="slide level2">
<h2><strong>4.5 The Carnot Cycle: Efficiency</strong></h2>
<ul>
<li><p>For a complete Carnot cycle, <span class="math inline">\(\Delta E_{int} = 0\)</span>.</p>
<ul>
<li>From the First Law: <span class="math inline">\(W = Q_h - Q_c\)</span>.</li>
</ul></li>
<li><p>The efficiency of a Carnot engine (<span class="math inline">\(e_C\)</span>) is: <span class="math display">\[e_C = \frac{W}{Q_h} = 1 - \frac{Q_c}{Q_h}\]</span></p></li>
<li><p>Through analysis of the adiabatic steps, it can be shown that for a Carnot cycle: <span class="math display">\[\frac{Q_c}{Q_h} = \frac{T_c}{T_h}\]</span> (where temperatures must be in Kelvin).</p></li>
<li><p>Therefore, the <strong>Carnot Efficiency</strong> is: <span class="math display">\[e_C = 1 - \frac{T_c}{T_h}\]</span></p></li>
</ul>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong><strong>Carnot’s Principle</strong></strong></p>
</div>
<div class="callout-content">
<p>No engine working between two reservoirs at constant temperatures can have a greater efficiency than a reversible engine. This means the Carnot efficiency <span class="math inline">\(e_C\)</span> is the <strong>maximum possible efficiency</strong> for <em>any</em> heat engine operating between <span class="math inline">\(T_h\)</span> and <span class="math inline">\(T_c\)</span>. Real engines always have <span class="math inline">\(e &lt; e_C\)</span>.</p>
</div>
</div>
</div>
<aside class="notes">
<ul>
<li>Reiterate the First Law for a cycle (<span class="math inline">\(W = Q_h - Q_c\)</span>).</li>
<li>Present the general efficiency formula.</li>
<li>State the crucial relationship <span class="math inline">\(Q_c/Q_h = T_c/T_h\)</span> for a Carnot cycle (without re-deriving it fully, as it’s complex for a single slide, but acknowledge its derivation comes from the adiabatic steps).</li>
<li>Provide the final Carnot efficiency formula <span class="math inline">\(e_C = 1 - T_c/T_h\)</span>.</li>
<li>Formally state Carnot’s Principle.</li>
<li>Emphasize its implication: <span class="math inline">\(e_C\)</span> is the absolute upper limit for efficiency, and real engines are always less efficient.</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-carnot-cycle-refrigeratorheat-pump-cops" class="slide level2">
<h2><strong>4.5 The Carnot Cycle: Refrigerator/Heat Pump COPs</strong></h2>
<ul>
<li><p>A Carnot refrigerator or heat pump is a Carnot engine running in reverse.</p>
<ul>
<li>The relationships <span class="math inline">\(W = Q_h - Q_c\)</span> and <span class="math inline">\(Q_c/Q_h = T_c/T_h\)</span> still hold.</li>
</ul></li>
<li><p><strong>Coefficient of Performance for a Carnot Refrigerator (<span class="math inline">\(K_{R,C}\)</span>):</strong> <span class="math display">\[K_{R,C} = \frac{Q_c}{W} = \frac{Q_c}{Q_h - Q_c}\]</span> Substituting <span class="math inline">\(Q_h = Q_c \frac{T_h}{T_c}\)</span>: <span class="math display">\[K_{R,C} = \frac{Q_c}{Q_c \frac{T_h}{T_c} - Q_c} = \frac{1}{\frac{T_h}{T_c} - 1}\]</span> <span class="math display">\[K_{R,C} = \frac{T_c}{T_h - T_c}\]</span></p></li>
<li><p><strong>Coefficient of Performance for a Carnot Heat Pump (<span class="math inline">\(K_{P,C}\)</span>):</strong> <span class="math display">\[K_{P,C} = \frac{Q_h}{W} = \frac{Q_h}{Q_h - Q_c}\]</span> Substituting <span class="math inline">\(Q_c = Q_h \frac{T_c}{T_h}\)</span>: <span class="math display">\[K_{P,C} = \frac{Q_h}{Q_h - Q_h \frac{T_c}{T_h}} = \frac{1}{1 - \frac{T_c}{T_h}}\]</span> <span class="math display">\[K_{P,C} = \frac{T_h}{T_h - T_c}\]</span></p></li>
</ul>
<aside class="notes">
<ul>
<li>Explain that Carnot refrigerator/heat pump are simply reversed Carnot engines.</li>
<li>Derive the <span class="math inline">\(K_{R,C}\)</span> formula, showing the steps for substitution.</li>
<li>Derive the <span class="math inline">\(K_{P,C}\)</span> formula, showing the steps for substitution.</li>
<li>Emphasize that these are the <em>maximum possible</em> COPs for devices operating between <span class="math inline">\(T_h\)</span> and <span class="math inline">\(T_c\)</span>.</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-carnot-cycle-example---a-carnot-engine" class="slide level2 scrollable">
<h2><strong>4.5 The Carnot Cycle: Example - A Carnot Engine</strong></h2>
<p>A Carnot engine has an efficiency of 0.60 and the temperature of its cold reservoir is 300 K.</p>
<ol type="a">
<li>What is the temperature of the hot reservoir?</li>
<li>If the engine does 300 J of work per cycle, how much heat is removed from the high-temperature reservoir per cycle?</li>
<li>How much heat is exhausted to the low-temperature reservoir per cycle?</li>
</ol>
<p><strong>Given:</strong></p>
<p><span class="math inline">\(e_C = 0.60\)</span></p>
<p><span class="math inline">\(T_c = 300 \text{ K}\)</span></p>
<p><span class="math inline">\(W = 300 \text{ J}\)</span></p>
<p><strong>Solution:</strong></p>
<p><strong>(a) Temperature of the hot reservoir (<span class="math inline">\(T_h\)</span>):</strong></p>
<p><span class="math inline">\(e_C = 1 - \frac{T_c}{T_h}\)</span></p>
<p><span class="math inline">\(0.60 = 1 - \frac{300 \text{ K}}{T_h}\)</span></p>
<p><span class="math inline">\(\frac{300 \text{ K}}{T_h} = 1 - 0.60 = 0.40\)</span></p>
<p><span class="math inline">\(T_h = \frac{300 \text{ K}}{0.40} = 750 \text{ K}\)</span></p>
<p><strong>(b) Heat removed from hot reservoir (<span class="math inline">\(Q_h\)</span>):</strong></p>
<p><span class="math inline">\(e_C = \frac{W}{Q_h} \implies Q_h = \frac{W}{e_C}\)</span></p>
<p><span class="math inline">\(Q_h = \frac{300 \text{ J}}{0.60} = 500 \text{ J}\)</span></p>
<p><strong>(c) Heat exhausted to cold reservoir (<span class="math inline">\(Q_c\)</span>):</strong></p>
<p><span class="math inline">\(W = Q_h - Q_c \implies Q_c = Q_h - W\)</span></p>
<p><span class="math inline">\(Q_c = 500 \text{ J} - 300 \text{ J} = 200 \text{ J}\)</span></p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Always use Kelvin for temperature in Carnot efficiency/COP calculations.</p>
</div>
</div>
</div>
<aside class="notes">
<ul>
<li>Walk through the problem step-by-step.</li>
<li>Clearly show the formula used for each calculation.</li>
<li>Emphasize the importance of using Kelvin for temperatures.</li>
<li>Highlight the relationship between the three quantities (<span class="math inline">\(W\)</span>, <span class="math inline">\(Q_h\)</span>, <span class="math inline">\(Q_c\)</span>) via the First Law.</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="entropy" class="slide level2">
<h2><strong>4.6 Entropy</strong></h2>
<h3 id="learning-objectives-5"><strong>Learning Objectives</strong></h3>
<ul>
<li>Describe the meaning of entropy.</li>
<li>Calculate the change of entropy for some simple processes.</li>
</ul>
</section>
<section id="entropy-definition-and-state-function" class="slide level2">
<h2><strong>4.6 Entropy: Definition and State Function</strong></h2>
<ul>
<li><strong>Entropy (<span class="math inline">\(S\)</span>):</strong> A thermodynamic variable that quantifies the <strong>disorder</strong> or <strong>randomness</strong> of a system.
<ul>
<li>Related to how energy is distributed among particles.</li>
</ul></li>
<li><strong>State Function:</strong>
<ul>
<li>Like internal energy (<span class="math inline">\(E_{int}\)</span>), entropy is a state function.</li>
<li>The change in entropy (<span class="math inline">\(\Delta S\)</span>) between two states depends <strong>only on the initial and final states</strong>, not on the path taken.</li>
</ul></li>
<li><strong>Entropy Change for Reversible Process at Constant Temperature:</strong>
<ul>
<li>If a system exchanges heat <span class="math inline">\(Q\)</span> reversibly at a constant temperature <span class="math inline">\(T\)</span> (in Kelvin): <span class="math display">\[\Delta S = \frac{Q}{T}\]</span></li>
<li>If <span class="math inline">\(Q &gt; 0\)</span> (heat absorbed), <span class="math inline">\(\Delta S &gt; 0\)</span> (entropy increases).</li>
<li>If <span class="math inline">\(Q &lt; 0\)</span> (heat lost), <span class="math inline">\(\Delta S &lt; 0\)</span> (entropy decreases).</li>
</ul></li>
</ul>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>For phase changes (e.g., melting ice), temperature remains constant, so <span class="math inline">\(\Delta S = Q/T\)</span> is directly applicable.</p>
</div>
</div>
</div>
<aside class="notes">
<ul>
<li>Start with a concise definition of entropy, linking it to disorder/randomness.</li>
<li>Emphasize that entropy is a state function, meaning path independence.</li>
<li>Introduce the formula for entropy change in a reversible process at constant temperature.</li>
<li>Explain the sign convention for <span class="math inline">\(Q\)</span> and its effect on <span class="math inline">\(\Delta S\)</span>.</li>
<li>Give phase change as a direct application example.</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="entropy-general-reversible-processes" class="slide level2">
<h2><strong>4.6 Entropy: General Reversible Processes</strong></h2>
<ul>
<li>For an arbitrary reversible transition where temperature is <em>not</em> constant:
<ul>
<li>Imagine the process as a series of infinitesimal steps, each exchanging heat <span class="math inline">\(dQ_{rev}\)</span> at temperature <span class="math inline">\(T\)</span>.</li>
<li>The total change in entropy is found by integrating: <span class="math display">\[\Delta S = \int_{A}^{B} \frac{dQ_{rev}}{T}\]</span></li>
<li>This integral is path-independent for reversible processes, reinforcing that <span class="math inline">\(S\)</span> is a state function.</li>
</ul></li>
<li><strong>Entropy Change in a Reversible Cyclic Process:</strong>
<ul>
<li>For any complete reversible cyclic process (like the Carnot cycle), the net change in entropy of the system is zero. <span class="math display">\[\oint \frac{dQ_{rev}}{T} = 0\]</span></li>
<li>This is because the system returns to its initial state.</li>
</ul></li>
</ul>
<aside class="notes">
<ul>
<li>Extend the entropy change calculation to variable-temperature reversible processes using the integral form.</li>
<li>Reiterate path independence from the integral definition.</li>
<li>Explain the entropy change for any reversible cyclic process, which must be zero because entropy is a state function.</li>
<li>Connect this back to the Carnot cycle, where <span class="math inline">\(\Delta S_{engine} = 0\)</span>.</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="entropy-second-law-entropy-statement" class="slide level2">
<h2><strong>4.6 Entropy: Second Law (Entropy Statement)</strong></h2>
<ul>
<li>What about irreversible processes?
<ul>
<li>The entropy of a <em>closed system</em> (or the universe) <em>always increases</em> for an irreversible process.</li>
<li>For a reversible process, the entropy of a closed system remains constant (<span class="math inline">\(\Delta S = 0\)</span>).</li>
</ul></li>
</ul>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong><strong>Second Law of Thermodynamics (Entropy Statement)</strong></strong></p>
</div>
<div class="callout-content">
<p>The entropy of a closed system and the entire universe never decreases.</p>
<p><span class="math display">\[\Delta S_{universe} \ge 0\]</span></p>
<ul>
<li>The equality (<span class="math inline">\(= 0\)</span>) holds for reversible processes.</li>
<li>The inequality (<span class="math inline">\(&gt; 0\)</span>) holds for irreversible (natural) processes.</li>
</ul>
</div>
</div>
</div>
<ul>
<li>This statement is consistent with the Clausius and Kelvin statements and Carnot’s principle.
<ul>
<li>Natural processes always proceed in a direction that increases the total entropy of the universe.</li>
<li>This is why spontaneous heat flow is from hot to cold, and why gas expands to fill a vacuum.</li>
</ul></li>
</ul>
<aside class="notes">
<ul>
<li>Transition from reversible to irreversible processes regarding entropy.</li>
<li>State the entropy formulation of the Second Law clearly.</li>
<li>Explain the meaning of the equality and inequality signs.</li>
<li>Emphasize that this statement underpins why natural processes occur in one direction.</li>
<li>Connect it back to the earlier examples of free expansion and heat flow.</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="entropy-example---entropy-change-of-melting-ice" class="slide level2 scrollable">
<h2><strong>4.6 Entropy: Example - Entropy Change of Melting Ice</strong></h2>
<p>Heat is slowly added to a 50-g chunk of ice at 0°C until it completely melts into water at the same temperature. What is the entropy change of the ice?</p>
<p><strong>Given:</strong></p>
<p><span class="math inline">\(m = 50 \text{ g}\)</span></p>
<p><span class="math inline">\(T = 0^\circ\text{C} = 273 \text{ K}\)</span></p>
<p>Latent heat of fusion for water, <span class="math inline">\(L_f = 335 \text{ J/g}\)</span></p>
<p><strong>Strategy:</strong></p>
<ul>
<li>This is a phase change at constant temperature, so the process can be considered reversible for the ice.</li>
<li>Use <span class="math inline">\(\Delta S = Q/T\)</span>.</li>
<li>First, calculate the heat absorbed during melting, <span class="math inline">\(Q = mL_f\)</span>.</li>
</ul>
<p><strong>Solution:</strong></p>
<ol type="1">
<li><p><strong>Calculate heat absorbed (<span class="math inline">\(Q\)</span>):</strong></p>
<p><span class="math inline">\(Q = m L_f = (50 \text{ g}) \times (335 \text{ J/g})\)</span></p>
<p><span class="math inline">\(Q = 16,750 \text{ J} = 16.75 \text{ kJ}\)</span></p></li>
<li><p><strong>Calculate entropy change (<span class="math inline">\(\Delta S\)</span>):</strong></p>
<p><span class="math inline">\(\Delta S = \frac{Q}{T} = \frac{16,750 \text{ J}}{273 \text{ K}}\)</span></p>
<p><span class="math inline">\(\Delta S \approx 61.36 \text{ J/K}\)</span></p></li>
</ol>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>The entropy of the ice increases because it absorbs heat and becomes more disordered (liquid water molecules have more freedom than solid ice molecules).</p>
</div>
</div>
</div>
<aside class="notes">
<ul>
<li>Clearly state the problem and list the given values.</li>
<li>Outline the strategy, identifying it as a constant temperature reversible process for the system.</li>
<li>Walk through the calculation of heat absorbed (<span class="math inline">\(Q\)</span>).</li>
<li>Then, calculate the entropy change (<span class="math inline">\(\Delta S\)</span>).</li>
<li>Emphasize the physical interpretation of the positive entropy change (increased disorder).</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="entropy-on-a-microscopic-scale" class="slide level2">
<h2><strong>4.7 Entropy on a Microscopic Scale</strong></h2>
<h3 id="learning-objectives-6"><strong>Learning Objectives</strong></h3>
<ul>
<li>Interpret the meaning of entropy at a microscopic scale.</li>
<li>Calculate a change in entropy for an irreversible process of a system and contrast with the change in entropy of the universe.</li>
<li>Explain the third law of thermodynamics.</li>
</ul>
</section>
<section id="entropy-on-a-microscopic-scale-disorder-and-probability" class="slide level2">
<h2><strong>4.7 Entropy on a Microscopic Scale: Disorder and Probability</strong></h2>
<ul>
<li>On a microscopic scale, entropy is related to the <strong>number of possible microscopic arrangements (microstates)</strong> that correspond to a given macroscopic state (macrostate).
<ul>
<li>A system with more microstates has higher entropy.</li>
<li>More microstates generally means more <strong>disorder</strong> or <strong>randomness</strong>.</li>
</ul></li>
<li><strong>Boltzmann’s Entropy Formula:</strong> <span class="math display">\[S = k_B \ln W\]</span>
<ul>
<li><span class="math inline">\(k_B\)</span>: Boltzmann constant (<span class="math inline">\(1.38 \times 10^{-23} \text{ J/K}\)</span>).</li>
<li><span class="math inline">\(W\)</span>: Number of microstates corresponding to the macrostate.</li>
</ul></li>
<li><strong>Second Law (in terms of disorder):</strong> <em>In any irreversible process, the universe becomes more disordered.</em>
<ul>
<li><strong>Example: Shuffling cards:</strong> A new deck (ordered) has low entropy. Shuffling increases the number of possible arrangements, increasing disorder and entropy.</li>
<li><strong>Example: Free expansion:</strong> Gas molecules can occupy a larger volume, meaning more possible positions (microstates), thus increasing entropy.</li>
</ul></li>
</ul>
<aside class="notes">
<ul>
<li>Introduce the microscopic interpretation of entropy, linking it to microstates and disorder.</li>
<li>Present Boltzmann’s formula (<span class="math inline">\(S = k_B \ln W\)</span>) as the mathematical representation, explaining <span class="math inline">\(k_B\)</span> and <span class="math inline">\(W\)</span>.</li>
<li>Rephrase the Second Law in terms of disorder, providing intuitive examples like shuffling cards and free expansion.</li>
<li>Emphasize that natural processes tend towards states of higher probability (more microstates/disorder).</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="entropy-on-a-microscopic-scale-example---entropy-change-of-the-universe" class="slide level2 scrollable">
<h2><strong>4.7 Entropy on a Microscopic Scale: Example - Entropy Change of the Universe</strong></h2>
<p>50 g of ice at 0°C is placed in contact with a heat reservoir at 20°C. Heat flows spontaneously from the reservoir to the ice, which melts and eventually reaches 20°C. Find the change in entropy of (a) the ice and (b) the universe.</p>
<p><strong>Given:</strong></p>
<p><span class="math inline">\(m_{ice} = 50 \text{ g} = 0.050 \text{ kg}\)</span></p>
<p><span class="math inline">\(T_{ice, initial} = 0^\circ\text{C} = 273 \text{ K}\)</span></p>
<p><span class="math inline">\(T_{reservoir} = 20^\circ\text{C} = 293 \text{ K}\)</span></p>
<p><span class="math inline">\(L_f = 335 \text{ J/g} = 335,000 \text{ J/kg}\)</span></p>
<p><span class="math inline">\(c_{water} = 4186 \text{ J/(kg} \cdot \text{K)}\)</span></p>
<p><strong>Solution:</strong></p>
<p><strong>(a) Change in entropy of the ice (<span class="math inline">\(\Delta S_{ice}\)</span>):</strong></p>
<p>This involves two reversible steps for the ice: 1. <strong>Melting at 0°C (273 K):</strong></p>
<pre><code>$Q_1 = m L_f = (0.050 \text{ kg})(335,000 \text{ J/kg}) = 16,750 \text{ J}$

$\Delta S_1 = \frac{Q_1}{T_1} = \frac{16,750 \text{ J}}{273 \text{ K}} = 61.36 \text{ J/K}$</code></pre>
<ol start="2" type="1">
<li><p><strong>Warming water from 0°C to 20°C (273 K to 293 K):</strong></p>
<p><span class="math inline">\(\Delta S_2 = \int_{T_1}^{T_2} \frac{dQ}{T} = \int_{T_1}^{T_2} \frac{mc dT}{T} = mc \ln(\frac{T_2}{T_1})\)</span></p>
<p><span class="math inline">\(\Delta S_2 = (0.050 \text{ kg})(4186 \text{ J/(kg} \cdot \text{K)}) \ln(\frac{293 \text{ K}}{273 \text{ K}})\)</span></p>
<p><span class="math inline">\(\Delta S_2 = (209.3 \text{ J/K}) \ln(1.073) \approx 14.65 \text{ J/K}\)</span></p>
<p>Total <span class="math inline">\(\Delta S_{ice} = \Delta S_1 + \Delta S_2 = 61.36 \text{ J/K} + 14.65 \text{ J/K} = 76.01 \text{ J/K}\)</span></p></li>
</ol>
<p><strong>(b) Change in entropy of the universe (<span class="math inline">\(\Delta S_{universe}\)</span>):</strong> The reservoir provides all the heat.</p>
<p>Total heat transferred from reservoir:</p>
<p><span class="math inline">\(Q_{total} = Q_1 + Q_2 = m L_f + m c \Delta T = 16,750 \text{ J} + (0.050 \text{ kg})(4186 \text{ J/(kg} \cdot \text{K)})(20 \text{ K})\)</span></p>
<p><span class="math inline">\(Q_{total} = 16,750 \text{ J} + 4186 \text{ J} = 20,936 \text{ J}\)</span></p>
<p>Change in entropy of the reservoir (at constant <span class="math inline">\(T_R = 293 \text{ K}\)</span>):</p>
<p><span class="math inline">\(\Delta S_{reservoir} = \frac{-Q_{total}}{T_{reservoir}} = \frac{-20,936 \text{ J}}{293 \text{ K}} = -71.45 \text{ J/K}\)</span></p>
<p>Total <span class="math inline">\(\Delta S_{universe} = \Delta S_{ice} + \Delta S_{reservoir} = 76.01 \text{ J/K} - 71.45 \text{ J/K} = 4.56 \text{ J/K}\)</span></p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>Since <span class="math inline">\(\Delta S_{universe} &gt; 0\)</span>, the irreversible process (spontaneous heat flow and melting) indeed increases the total entropy of the universe, confirming the Second Law.</p>
</div>
</div>
</div>
<aside class="notes">
<ul>
<li>This is a multi-step calculation. Guide students through each part.</li>
<li>Break down the entropy change for the ice into two phases: melting (constant T) and warming (variable T, requiring integration).</li>
<li>Clearly show the calculation for each part.</li>
<li>Then, calculate the total heat provided by the reservoir.</li>
<li>Calculate the entropy change of the reservoir (it’s negative as heat is lost).</li>
<li>Finally, sum the entropy changes to get the universe’s entropy change.</li>
<li>Emphasize that <span class="math inline">\(\Delta S_{universe} &gt; 0\)</span> is the key result confirming the Second Law.</li>
<li>Discuss the increase in disorder of the ice (solid to liquid) vs.&nbsp;the slight decrease in disorder of the reservoir (losing heat), with the net result being an increase in overall disorder.</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="entropy-on-a-microscopic-scale-third-law-of-thermodynamics" class="slide level2">
<h2><strong>4.7 Entropy on a Microscopic Scale: Third Law of Thermodynamics</strong></h2>
<ul>
<li>The Second Law states that <span class="math inline">\(\Delta S_{universe} \ge 0\)</span>.</li>
<li>But what happens as temperature approaches absolute zero (<span class="math inline">\(T \to 0 \text{ K}\)</span>)?</li>
</ul>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong><strong>Third Law of Thermodynamics</strong></strong></p>
</div>
<div class="callout-content">
<p>The absolute zero temperature (<span class="math inline">\(0 \text{ K}\)</span>) cannot be reached through any finite number of cooling steps. (Alternatively: A system becomes perfectly ordered when its temperature approaches absolute zero, and its entropy approaches its absolute minimum (often taken as zero for a pure, crystalline substance)). <span class="math display">\[\lim_{T \to 0 \text{ K}} \Delta S = 0\]</span></p>
</div>
</div>
</div>
<ul>
<li><strong>Implications:</strong>
<ul>
<li>It’s impossible to build a “perfect engine” that uses a reservoir at <span class="math inline">\(0 \text{ K}\)</span> to achieve 100% efficiency.</li>
<li>At <span class="math inline">\(0 \text{ K}\)</span>, all thermal motion ceases, and a system is in its lowest energy state, ideally with only one possible microstate (<span class="math inline">\(W=1 \implies S = k_B \ln 1 = 0\)</span>).</li>
</ul></li>
</ul>
<aside class="notes">
<ul>
<li>Introduce the Third Law of Thermodynamics as an extension beyond the Second Law regarding low temperatures.</li>
<li>State the two common formulations of the Third Law.</li>
<li>Explain the implication for reaching absolute zero and for engine efficiency (connecting back to the Second Law).</li>
<li>Briefly connect it to the microscopic view: at 0 K, ideally, there’s only one microstate, meaning zero entropy (for a perfect crystal).</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="key-takeaways" class="slide level2">
<h2><strong>Key Takeaways</strong></h2>
<ul>
<li><strong>Reversible vs.&nbsp;Irreversible:</strong> Reversible processes are idealized and can be reversed without any change in the environment; irreversible processes (natural processes) cannot.</li>
<li><strong>Second Law (Clausius):</strong> Heat never flows spontaneously from cold to hot.</li>
<li><strong>Second Law (Kelvin):</strong> It’s impossible for an engine in a cycle to convert all absorbed heat into work.</li>
<li><strong>Heat Engine Efficiency:</strong> <span class="math inline">\(e = 1 - \frac{Q_c}{Q_h}\)</span>.</li>
<li><strong>Refrigerator/Heat Pump COP:</strong> <span class="math inline">\(K_R = \frac{Q_c}{W}\)</span>, <span class="math inline">\(K_P = \frac{Q_h}{W}\)</span>.</li>
<li><strong>Carnot Cycle:</strong> The most efficient reversible cycle between two temperatures.</li>
<li><strong>Carnot Efficiency:</strong> <span class="math inline">\(e_C = 1 - \frac{T_c}{T_h}\)</span> (maximum possible efficiency).</li>
<li><strong>Carnot COPs:</strong> <span class="math inline">\(K_{R,C} = \frac{T_c}{T_h - T_c}\)</span>, <span class="math inline">\(K_{P,C} = \frac{T_h}{T_h - T_c}\)</span> (maximum possible COPs).</li>
<li><strong>Entropy (<span class="math inline">\(S\)</span>):</strong> A measure of disorder/randomness; a state function.</li>
<li><strong>Entropy Change (reversible, constant T):</strong> <span class="math inline">\(\Delta S = \frac{Q_{rev}}{T}\)</span>.</li>
<li><strong>Entropy Change (reversible, variable T):</strong> <span class="math inline">\(\Delta S = \int \frac{dQ_{rev}}{T}\)</span>.</li>
<li><strong>Second Law (Entropy):</strong> <span class="math inline">\(\Delta S_{universe} \ge 0\)</span> (increases for irreversible processes, constant for reversible).</li>
<li><strong>Third Law:</strong> Absolute zero temperature cannot be reached; entropy approaches its minimum (zero for perfect crystals) as <span class="math inline">\(T \to 0 \text{ K}\)</span>.</li>
</ul>
<aside class="notes">
<ul>
<li>This slide acts as a comprehensive summary of all the main concepts covered.</li>
<li>Each bullet point should be a concise reminder of a key definition, principle, or formula.</li>
<li>Encourage students to review these points as a quick reference for the chapter.</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="key-equations" class="slide level2">
<h2><strong>Key Equations</strong></h2>
<table class="caption-top">
<colgroup>
<col style="width: 43%">
<col style="width: 56%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Equation</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(W = Q_h - Q_c\)</span></td>
<td style="text-align: left;">Work done by a heat engine in a cycle (First Law)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(e = 1 - \frac{Q_c}{Q_h}\)</span></td>
<td style="text-align: left;">Efficiency of a heat engine</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(K_R = \frac{Q_c}{W}\)</span></td>
<td style="text-align: left;">Coefficient of Performance for a Refrigerator</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(K_P = \frac{Q_h}{W}\)</span></td>
<td style="text-align: left;">Coefficient of Performance for a Heat Pump</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(e_C = 1 - \frac{T_c}{T_h}\)</span></td>
<td style="text-align: left;">Carnot efficiency (maximum possible)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(K_{R,C} = \frac{T_c}{T_h - T_c}\)</span></td>
<td style="text-align: left;">COP of a Carnot Refrigerator (maximum possible)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(K_{P,C} = \frac{T_h}{T_h - T_c}\)</span></td>
<td style="text-align: left;">COP of a Carnot Heat Pump (maximum possible)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\Delta S = \frac{Q_{rev}}{T}\)</span></td>
<td style="text-align: left;">Entropy change for reversible process at constant T</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\Delta S = \int \frac{dQ_{rev}}{T}\)</span></td>
<td style="text-align: left;">Entropy change for general reversible process</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\Delta S_{universe} \ge 0\)</span></td>
<td style="text-align: left;">Second Law of Thermodynamics (Entropy Statement)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\lim_{T \to 0 \text{ K}} \Delta S = 0\)</span></td>
<td style="text-align: left;">Third Law of Thermodynamics</td>
</tr>
</tbody>
</table>
<aside class="notes">
<ul>
<li>This slide provides a focused reference for the most important formulas.</li>
<li>Students can quickly consult this for problem-solving.</li>
<li>Ensure all variables are implicitly understood from previous slides or briefly explained if ambiguity exists.</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="key-terms" class="slide level2">
<h2><strong>Key Terms</strong></h2>
<table class="caption-top">
<colgroup>
<col style="width: 15%">
<col style="width: 85%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Term</th>
<th style="text-align: left;">Definition</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Reversible Process</strong></td>
<td style="text-align: left;">A thermodynamic process where both the system and its environment can be restored to their exact initial states.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Irreversible Process</strong></td>
<td style="text-align: left;">A thermodynamic process where the system and/or its environment cannot be restored to their original states simultaneously.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Heat Engine</strong></td>
<td style="text-align: left;">A device that converts thermal energy (heat) into mechanical work by operating between a hot and a cold reservoir.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Efficiency</strong> (<span class="math inline">\(e\)</span>)</td>
<td style="text-align: left;">The ratio of work output to heat input for a heat engine.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Refrigerator</strong></td>
<td style="text-align: left;">A device that uses work input to transfer heat from a cold reservoir to a hot reservoir.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Heat Pump</strong></td>
<td style="text-align: left;">A device that uses work input to transfer heat from a cold reservoir to a hot reservoir, with the goal of heating the hot reservoir.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Coefficient of Performance</strong> (COP)</td>
<td style="text-align: left;">A measure of the effectiveness of a refrigerator or heat pump, defined as the ratio of desired heat transfer to work input.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Carnot Cycle</strong></td>
<td style="text-align: left;">A theoretical reversible thermodynamic cycle that represents the most efficient possible cycle for converting heat into work between two temperatures.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Carnot’s Principle</strong></td>
<td style="text-align: left;">States that no engine working between two constant temperature reservoirs can have a greater efficiency than a reversible engine.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Entropy</strong> (<span class="math inline">\(S\)</span>)</td>
<td style="text-align: left;">A thermodynamic state function that quantifies the disorder or randomness of a system and the dispersal of energy.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Clausius Statement</strong></td>
<td style="text-align: left;">States that heat never flows spontaneously from a colder object to a hotter object.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Kelvin Statement</strong></td>
<td style="text-align: left;">States that it is impossible to convert the heat from a single source entirely into work without any other effect.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Third Law of Thermodynamics</strong></td>
<td style="text-align: left;">States that absolute zero temperature cannot be reached, and a system’s entropy approaches its minimum as temperature approaches absolute zero.</td>
</tr>
</tbody>
</table>
<aside class="notes">
<ul>
<li>This slide defines the essential vocabulary for the chapter.</li>
<li>Each term should have a concise, clear definition.</li>
<li>Encourage students to understand these terms thoroughly as they form the foundation of the topic.</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>


<script type="ojs-module-contents">
eyJjb250ZW50cyI6W119
</script>
<div id="exercise-loading-indicator" class="exercise-loading-indicator d-none d-flex align-items-center gap-2">
<div id="exercise-loading-status" class="d-flex gap-2">

</div>
<div class="spinner-grow spinner-grow-sm">

</div>
</div>
<script type="vfs-file">
W10=
</script>
</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="../qrjs_pics/unsoed_logo.png" class="slide-logo"></p>
<div class="footer footer-default">
<p><a href="https://imron-slide.vercel.app">irosyadi-2025</a></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': false,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: true,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script type="ojs-module-contents">
    eyJjb250ZW50cyI6W119
    </script>
    <script type="module">
    if (window.location.protocol === "file:") { alert("The OJS runtime does not work with file:// URLs. Please use a web server to view this document."); }
    window._ojs.paths.runtimeToDoc = "../../book_2";
    window._ojs.paths.runtimeToRoot = "../..";
    window._ojs.paths.docToRoot = "..";
    window._ojs.selfContained = false;
    window._ojs.runtime.interpretFromScriptTags();
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>