<!DOCTYPE html>
<html lang="en"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/quarto-contrib/live-runtime/live-runtime.js" type="module"></script>
<link href="../site_libs/quarto-contrib/live-runtime/live-runtime.css" rel="stylesheet"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.25">

  <meta name="author" content="Imron Rosyadi">
  <title>Physics</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-b0356e9119c1bdfd0db189d130feb51c.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <script type="module" src="../site_libs/quarto-ojs/quarto-ojs-runtime.js"></script>
  <link href="../site_libs/quarto-ojs/quarto-ojs.css" rel="stylesheet">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Physics</h1>
  <p class="subtitle">Chapter 1: Temperature and Heat</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Imron Rosyadi 
</div>
</div>
</div>

</section>
<section id="chapter-overview" class="slide level2">
<h2>Chapter Overview</h2>
<h3 id="temperature-and-heat">Temperature and Heat</h3>
<p>1.1 Temperature and Thermal Equilibrium<br>
1.2 Thermometers and Temperature Scales<br>
1.3 Thermal Expansion<br>
1.4 Heat Transfer, Specific Heat, and Calorimetry<br>
1.5 Phase Changes<br>
1.6 Mechanisms of Heat Transfer</p>
</section>
<section id="temperature-and-thermal-equilibrium" class="slide level2">
<h2>1.1 Temperature and Thermal Equilibrium</h2>
<h3 id="learning-objectives">Learning Objectives</h3>
<p>By the end of this section, you will be able to:</p>
<ul>
<li>Define temperature and describe it qualitatively</li>
<li>Explain thermal equilibrium</li>
<li>Explain the zeroth law of thermodynamics</li>
</ul>
</section>
<section id="what-is-temperature" class="slide level2">
<h2>What is Temperature?</h2>
<p>Temperature has evolved from the common concepts of hot and cold.</p>
<p>In physics, <strong>temperature</strong> is operationally defined as the quantity measured by a thermometer.</p>
<ul>
<li>More physically, temperature is proportional to the average kinetic energy of translational motion of molecules.</li>
</ul>
<p>Differences in temperature drive <strong>heat transfer</strong>, which is the movement of energy due to a temperature difference.</p>
<aside class="notes">
<p>Temperature is a fundamental concept in thermodynamics. Our initial understanding comes from our senses of hot and cold, but physics provides a more rigorous definition. Operationally, we define temperature by how we measure it with a thermometer. On a microscopic level, temperature is directly related to the average kinetic energy of the particles within a substance. This means that hotter objects have faster-moving particles. These temperature differences are what drive the flow of energy we call heat transfer.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="thermal-equilibrium" class="slide level2">
<h2>Thermal Equilibrium</h2>
<p><strong>Thermal equilibrium</strong> occurs when two objects in close contact, allowing energy transfer, no longer have a net transfer of energy between them.</p>
<ul>
<li>This also means that two objects in thermal equilibrium have the same temperature.</li>
</ul>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>Key Idea:</strong> If objects remain in contact for a long time, they typically reach thermal equilibrium.</p>
</div>
</div>
</div>
</section>
<section id="the-zeroth-law-of-thermodynamics" class="slide level2">
<h2>The Zeroth Law of Thermodynamics</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p>The <strong>Zeroth Law of Thermodynamics</strong> states:</p>
<ul>
<li>If object A is in thermal equilibrium with object B,</li>
<li>And object B is in thermal equilibrium with object C,</li>
<li>Then object A is in thermal equilibrium with object C.</li>
</ul>
<p>This law is fundamental for defining temperature, as it implies that if two objects are in thermal equilibrium, they share a common property: their temperature.</p>
</div><div class="column" style="width:50%;">
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/bfca89d249427174621330e94955097c48c57a25" height="350"></p>
<p><em>Figure 1.2: Illustrating the Zeroth Law of Thermodynamics.</em></p>
</div></div>
<aside class="notes">
<p>The Zeroth Law is crucial because it allows us to use a thermometer to measure the temperature of an object. If the thermometer (A) reaches equilibrium with object B and gives a certain reading, and then it’s placed in contact with object C and gives the <em>same</em> reading, it means B and C are at the same temperature. This is how a thermometer can measure the temperature of “something else” and not just its own temperature. Without this law, comparing temperatures would be much more complex.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="thermometers-and-temperature-scales" class="slide level2">
<h2>1.2 Thermometers and Temperature Scales</h2>
<h3 id="learning-objectives-1">Learning Objectives</h3>
<p>By the end of this section, you will be able to:</p>
<ul>
<li>Describe several different types of thermometers</li>
<li>Convert temperatures between the Celsius, Fahrenheit, and Kelvin scales</li>
</ul>
</section>
<section id="thermometers" class="slide level2">
<h2>Thermometers</h2>
<p>Any physical property that depends consistently on temperature can be used to make a thermometer.</p>
<p>Common properties:</p>
<ul>
<li><strong>Volume expansion:</strong> Alcohol or mercury thermometers.</li>
<li><strong>Electrical resistance:</strong> Used in electronic thermometers.</li>
<li><strong>Color/Infrared radiation emission:</strong> Pyrometers, liquid crystal strips.</li>
</ul>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/3647b15190166d4f1533a34ff2e2b5b97912540f" height="350"></p>
<p><em>Figure 1.3: Examples of different thermometer types.</em></p>
<aside class="notes">
<p>Thermometers are essential tools for quantitative temperature measurement. The principle behind them is that various physical properties change predictably with temperature. For instance, most substances expand when heated, which is the basis for traditional liquid-in-glass thermometers. Electrical resistance also changes with temperature, allowing for digital thermometers. Even the color or amount of infrared radiation emitted by an object can indicate its temperature, as seen in pyrometers.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="temperature-scales" class="slide level2">
<h2>Temperature Scales</h2>
<p>Three common temperature scales: Fahrenheit, Celsius, and Kelvin.</p>
<ul>
<li>Scales are defined by reproducible temperatures, typically freezing and boiling points of water.</li>
</ul>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Celsius (°C)</strong></p>
<ul>
<li>Freezing point of water: 0°C</li>
<li>Boiling point of water: 100°C</li>
</ul>
<p><strong>Fahrenheit (°F)</strong></p>
<ul>
<li>Freezing point of water: 32°F</li>
<li>Boiling point of water: 212°F</li>
<li>A 1°C difference is 1.8 times larger than a 1°F difference (<span class="math inline">\(\Delta T_F = \frac{9}{5} \Delta T_C\)</span>).</li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>Kelvin (K)</strong></p>
<ul>
<li><strong>Absolute temperature scale:</strong> Zero point is <strong>absolute zero</strong> (where average kinetic energy is zero).</li>
<li>Freezing point of water: 273.15 K</li>
<li>Boiling point of water: 373.15 K</li>
<li>Temperature differences are the same as Celsius (<span class="math inline">\(\Delta T_C = \Delta T_K\)</span>).</li>
<li>SI unit for temperature.</li>
</ul>
</div></div>
<aside class="notes">
<p>It’s important to understand the origins and relationships between these scales. Celsius is metric and scientifically convenient due to its 100-degree range for water’s phase changes. Fahrenheit is still used in everyday contexts in some countries. Kelvin is the absolute scale, meaning its zero point, absolute zero, is the lowest possible temperature. This scale is preferred in science because many physical laws simplify when expressed in absolute temperature.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="temperature-conversions" class="slide level2">
<h2>Temperature Conversions</h2>
<p>Relationships between temperature scales:</p>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/96f26777502f9f86c1c5d2d5f1f6b65d3c5e1254" height="300"></p>
<p><em>Figure 1.4: Comparing Fahrenheit, Celsius, and Kelvin scales.</em></p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">To convert from…</th>
<th style="text-align: left;">Use this equation…</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Celsius to Fahrenheit</td>
<td style="text-align: left;"><span class="math inline">\(T_F = \frac{9}{5} T_C + 32\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Fahrenheit to Celsius</td>
<td style="text-align: left;"><span class="math inline">\(T_C = \frac{5}{9} (T_F - 32)\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Celsius to Kelvin</td>
<td style="text-align: left;"><span class="math inline">\(T_K = T_C + 273.15\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Kelvin to Celsius</td>
<td style="text-align: left;"><span class="math inline">\(T_C = T_K - 273.15\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fahrenheit to Kelvin</td>
<td style="text-align: left;"><span class="math inline">\(T_K = \frac{5}{9} (T_F - 32) + 273.15\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Kelvin to Fahrenheit</td>
<td style="text-align: left;"><span class="math inline">\(T_F = \frac{9}{5} (T_K - 273.15) + 32\)</span></td>
</tr>
</tbody>
</table>
<aside class="notes">
<p>These equations are essential for converting between the different temperature scales. Remember that converting Fahrenheit to Kelvin often involves an intermediate step of converting to Celsius first. Understanding the relationship between the scales, especially how temperature differences are related, is key.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="example-room-temperature-conversion" class="slide level2 scrollable">
<h2>Example: Room Temperature Conversion</h2>
<p><strong>Problem:</strong> “Room temperature” is generally defined as 25°C.</p>
<ol type="a">
<li>What is room temperature in °F?</li>
<li>What is it in K?</li>
</ol>
<p><strong>Solution:</strong></p>
<ol type="a">
<li>Celsius to Fahrenheit:</li>
</ol>
<p><span class="math inline">\(T_F = \frac{9}{5} T_C + 32 = \frac{9}{5}(25^\circ\text{C}) + 32 = 45 + 32 = 77^\circ\text{F}\)</span>.</p>
<ol start="2" type="a">
<li>Celsius to Kelvin:</li>
</ol>
<p><span class="math inline">\(T_K = T_C + 273.15 = 25^\circ\text{C} + 273.15 = 298 \text{ K}\)</span>.</p>
</section>
<section id="constant-volume-gas-thermometer" class="slide level2">
<h2>Constant-Volume Gas Thermometer</h2>
<ul>
<li><p>Used as a standard for precise temperature measurement.</p></li>
<li><p>Temperature is proportional to the pressure of a gas held at constant volume. <span class="math display">\[T = \frac{P}{P_{TP}} T_{TP}\]</span></p></li>
<li><p>Where <span class="math inline">\(T_{TP}\)</span> is the triple-point temperature (273.16 K).</p></li>
<li><p>Results are most accurate when extrapolated to zero gas density.</p></li>
</ul>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>The triple point of water (ice, liquid water, and water vapor coexist stably) provides a highly accurate and reproducible reference temperature.</p>
</div>
</div>
</div>
<aside class="notes">
<p>While liquid-in-glass thermometers are common, for highly accurate scientific measurements, the constant-volume gas thermometer is often used as a standard. Its principle relies on the linear relationship between the pressure of an ideal gas and its absolute temperature at constant volume. The triple point of water is a crucial fixed point for calibrating these thermometers, offering a more precise reference than just freezing or boiling points, which depend on pressure.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="thermal-expansion" class="slide level2">
<h2>1.3 Thermal Expansion</h2>
<h3 id="learning-objectives-2">Learning Objectives</h3>
<p>By the end of this section, you will be able to:</p>
<ul>
<li>Answer qualitative questions about the effects of thermal expansion</li>
<li>Solve problems involving thermal expansion, including those involving thermal stress</li>
</ul>
</section>
<section id="what-is-thermal-expansion" class="slide level2">
<h2>What is Thermal Expansion?</h2>
<p><strong>Thermal expansion</strong> is the change in size or volume of a system as its temperature changes.</p>
<ul>
<li>Most substances expand when heated and contract when cooled.</li>
<li>This is due to increased kinetic energy of atoms/molecules, leading to increased average distance between them.</li>
</ul>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/a4b9d7c2a5427a5941108c136a41f0fb3b3ce3b1" height="350"></p>
<p><em>Figure 1.5: Expansion joints in bridges accommodate thermal expansion.</em></p>
<aside class="notes">
<p>Thermal expansion is a very common phenomenon, from rising hot air balloons to the creaking sounds of houses at night. It’s important for engineers to account for thermal expansion when designing structures like bridges and railways, which is why expansion joints are installed. The underlying cause is the increased vibrational energy of particles at higher temperatures, which effectively pushes them further apart.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="linear-thermal-expansion" class="slide level2">
<h2>Linear Thermal Expansion</h2>
<p>For a given material, the change in length (<span class="math inline">\(\Delta L\)</span>) is proportional to the original length (<span class="math inline">\(L\)</span>) and the change in temperature (<span class="math inline">\(\Delta T\)</span>).</p>
<p><span class="math display">\[\Delta L = \alpha L \Delta T\]</span></p>
<ul>
<li><span class="math inline">\(\alpha\)</span> is the <strong>coefficient of linear expansion</strong>, a material property (units: 1/°C or 1/K).</li>
<li><span class="math inline">\(\Delta T\)</span> is the change in temperature.</li>
</ul>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><span class="math inline">\(\alpha\)</span> is typically very small and is approximated as constant for most practical purposes.</p>
</div>
</div>
</div>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Material</th>
<th style="text-align: left;"><span class="math inline">\(\alpha\)</span> (1/°C)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Aluminum</td>
<td style="text-align: left;"><span class="math inline">\(25 \times 10^{-6}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Steel</td>
<td style="text-align: left;"><span class="math inline">\(12 \times 10^{-6}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Pyrex® glass</td>
<td style="text-align: left;"><span class="math inline">\(3 \times 10^{-6}\)</span></td>
</tr>
</tbody>
</table>
<p><em>Table 1.2 (partial): Coefficients of Linear Expansion.</em></p>
<aside class="notes">
<p>This equation describes how a material’s length changes with temperature. It’s a linear approximation, meaning it works well for relatively small temperature changes. The coefficient of linear expansion, alpha, is unique to each material and phase. Understanding these coefficients allows us to predict and account for changes in dimensions due to temperature fluctuations.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="example-golden-gate-bridge-expansion" class="slide level2 scrollable">
<h2>Example: Golden Gate Bridge Expansion</h2>
<p><strong>Problem:</strong> The main span of the Golden Gate Bridge is 1275 m long at its coldest (–15°C). What is its change in length when it warms to 40°C? Assume it’s made entirely of steel (<span class="math inline">\(\alpha = 12 \times 10^{-6} /^\circ\text{C}\)</span>).</p>
<p><strong>Strategy:</strong> Use <span class="math inline">\(\Delta L = \alpha L \Delta T\)</span>.</p>
<p><strong>Solution:</strong></p>
<ol type="1">
<li><p>Calculate <span class="math inline">\(\Delta T = T_{final} - T_{initial} = 40^\circ\text{C} - (-15^\circ\text{C}) = 55^\circ\text{C}\)</span>.</p></li>
<li><p>Substitute values:</p>
<p><span class="math inline">\(\Delta L = (12 \times 10^{-6} /^\circ\text{C})(1275 \text{ m})(55^\circ\text{C})\)</span></p>
<p><span class="math inline">\(\Delta L = 0.84 \text{ m}\)</span></p></li>
</ol>
<p><strong>Significance:</strong> A change of 0.84 meters (about 33 inches) is significant for a bridge, highlighting the need for expansion joints.</p>
</section>
<section id="thermal-expansion-in-2d-and-3d" class="slide level2">
<h2>Thermal Expansion in 2D and 3D</h2>
<p>Objects expand in all dimensions: length, area, and volume.</p>
<ul>
<li>Holes in materials also expand with temperature.</li>
</ul>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/4dcab8d022984550f826921e988100ff483f6de8" height="250"></p>
<p><em>Figure 1.7: Expansion in two and three dimensions.</em></p>
<p><strong>Area Expansion:</strong></p>
<p>For small <span class="math inline">\(\Delta T\)</span>: <span class="math inline">\(\Delta A = 2 \alpha A \Delta T\)</span></p>
<p><strong>Volume Expansion:</strong></p>
<p><span class="math display">\[\Delta V = \beta V \Delta T\]</span> - <span class="math inline">\(\beta\)</span> is the <strong>coefficient of volume expansion</strong>. - For isotropic solids, <span class="math inline">\(\beta \approx 3\alpha\)</span>.</p>
<aside class="notes">
<p>It’s important to realize that thermal expansion isn’t limited to just length. An entire object, including any internal voids or holes, will expand proportionally in all dimensions. The relationship <span class="math inline">\(\beta \approx 3\alpha\)</span> for solids simplifies calculations, showing that volume expansion is roughly three times the linear expansion. For liquids and gases, only volume expansion is typically defined, as their shapes aren’t fixed.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="anomalous-expansion-of-water" class="slide level2">
<h2>Anomalous Expansion of Water</h2>
<p>Water is an important exception to typical thermal expansion behavior.</p>
<ul>
<li>Most substances are densest as solids.</li>
<li>Water is densest at <strong>4°C</strong>.</li>
<li>It expands (density decreases) both above 4°C and below 4°C (down to 0°C).</li>
</ul>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/8d6c8d276581ff160c900e54fb7e7b332d9c1b8e" height="300"></p>
<p><em>Figure 1.8: Density of water vs.&nbsp;temperature.</em></p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>This unusual property allows aquatic life to survive in cold climates. Water at 4°C sinks to the bottom, and ice (less dense) forms on the surface, insulating the water below.</p>
</div>
</div>
</div>
</section>
<section id="thermal-stress" class="slide level2">
<h2>Thermal Stress</h2>
<p><strong>Thermal stress</strong> occurs when an object’s temperature changes but it is prevented from expanding or contracting freely.</p>
<ul>
<li>This stress can be very large and cause damage.</li>
<li>Engineers design components with expansion joints or use materials with similar expansion coefficients (e.g., steel in concrete).</li>
</ul>
<p>To calculate thermal stress:</p>
<ul>
<li>Imagine the object expanding/contracting freely (<span class="math inline">\(\Delta L = \alpha L_0 \Delta T\)</span>).</li>
<li>Calculate the force needed to return it to its original length (<span class="math inline">\(F/A = Y (\Delta L / L_0)\)</span>).</li>
<li>Combining these: <span class="math inline">\(F/A = Y \alpha \Delta T\)</span>. (<span class="math inline">\(Y\)</span> is Young’s modulus).</li>
</ul>
<aside class="notes">
<p>Thermal stress is a critical consideration in many engineering applications. Imagine a concrete bridge without expansion joints – the expansion on a hot day could cause it to buckle, or contraction on a cold day could lead to cracks. By understanding and calculating thermal stress, engineers can choose appropriate materials and designs to prevent such failures.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="heat-transfer-specific-heat-and-calorimetry" class="slide level2">
<h2>1.4 Heat Transfer, Specific Heat, and Calorimetry</h2>
<h3 id="learning-objectives-3">Learning Objectives</h3>
<p>By the end of this section, you will be able to:</p>
<ul>
<li>Explain phenomena involving heat as a form of energy transfer</li>
<li>Solve problems involving heat transfer</li>
</ul>
</section>
<section id="internal-energy-and-heat" class="slide level2">
<h2>Internal Energy and Heat</h2>
<p><strong>Internal energy</strong> is the sum of the microscopic energies of a system’s molecules.</p>
<ul>
<li>Includes thermal energy, proportional to temperature.</li>
</ul>
<p><strong>Heat</strong> is energy transferred spontaneously due to a temperature difference.</p>
<ul>
<li>It’s a form of energy flow, not a property an object “has.”</li>
<li>SI unit: Joules (J).</li>
<li>Other common unit: calorie (cal) or kilocalorie (kcal).</li>
</ul>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/20481cb6eddc555307b8ac3b37ad52b8a0c7dafc" height="300"></p>
<p><em>Figure 1.9: Heat transfer from a soda to ice to reach thermal equilibrium.</em></p>
<aside class="notes">
<p>It’s vital to distinguish between internal energy and heat. Internal energy is a property <em>of</em> a system, representing the total energy of its molecules. Heat, on the other hand, is the <em>transfer</em> of energy <em>between</em> systems due to a temperature difference. A common misconception is to say an object “has heat”; rather, it has internal energy, and heat is the process by which that internal energy can change.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="mechanical-equivalent-of-heat" class="slide level2">
<h2>Mechanical Equivalent of Heat</h2>
<p>James Prescott Joule’s experiments established that work and heat can produce the same effects.</p>
<ul>
<li><strong>Mechanical equivalent of heat:</strong> The amount of work needed to produce the same effects as heat transfer.</li>
<li><span class="math inline">\(1.000 \text{ kcal} = 4186 \text{ J}\)</span></li>
</ul>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/aa45352115b3f47b6e30e07fd823b728b14224f9" height="350"></p>
<p><em>Figure 1.10: Joule’s experiment, showing conversion of gravitational potential energy into increased internal energy (heat).</em></p>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>Heat and work are <em>not</em> state variables. Internal energy and temperature <em>are</em> state variables.</p>
</div>
</div>
</div>
<aside class="notes">
<p>Joule’s work was groundbreaking because it helped consolidate the idea that heat is a form of energy, not a separate fluid (caloric). His experiments demonstrated that mechanical work could directly lead to an increase in a substance’s temperature, quantifying the relationship between mechanical energy and thermal energy. This was a crucial step in developing the law of conservation of energy and the field of thermodynamics.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="temperature-change-and-heat-capacity" class="slide level2">
<h2>Temperature Change and Heat Capacity</h2>
<p>When heat is transferred to a substance (without phase change or work), its temperature changes.</p>
<p>The amount of heat (<span class="math inline">\(Q\)</span>) transferred is approximately:</p>
<p><span class="math display">\[Q = mc\Delta T\]</span></p>
<ul>
<li><span class="math inline">\(m\)</span> is the mass of the substance.</li>
<li><span class="math inline">\(\Delta T\)</span> is the change in temperature.</li>
<li><span class="math inline">\(c\)</span> is the <strong>specific heat</strong> (or specific heat capacity).
<ul>
<li>Specific heat depends on the material and its phase (solid, liquid, gas).</li>
<li>SI units: J/(kg·K) or J/(kg·°C).</li>
</ul></li>
</ul>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Water has one of the largest specific heats, which helps stabilize Earth’s climate.</p>
</div>
</div>
</div>
<aside class="notes">
<p>This equation is fundamental for calculating temperature changes due to heat transfer. Specific heat is a crucial property, as it tells us how much energy is needed to change the temperature of a unit mass of a substance by one degree. Water’s high specific heat is why it takes a long time to boil and also why large bodies of water moderate local climates. The specific heat can vary with temperature, but for many problems, we assume it’s constant over the given temperature range.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="specific-heats-of-various-substances" class="slide level2">
<h2>Specific Heats of Various Substances</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Substances</th>
<th style="text-align: left;">Specific Heat (<span class="math inline">\(c\)</span>) J/(kg·°C)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong><em>Solids</em></strong></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Aluminum</td>
<td style="text-align: left;">900</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Copper</td>
<td style="text-align: left;">387</td>
</tr>
<tr class="even">
<td style="text-align: left;">Glass</td>
<td style="text-align: left;">840</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ice (average, –50°C to 0°C)</td>
<td style="text-align: left;">2090</td>
</tr>
<tr class="even">
<td style="text-align: left;">Iron, steel</td>
<td style="text-align: left;">452</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong><em>Liquids</em></strong></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Ethanol</td>
<td style="text-align: left;">2450</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mercury</td>
<td style="text-align: left;">139</td>
</tr>
<tr class="even">
<td style="text-align: left;">Water (15.0°C)</td>
<td style="text-align: left;">4186</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong><em>Gases</em></strong></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Air (dry)</td>
<td style="text-align: left;">721 (1015)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Steam (100°C)</td>
<td style="text-align: left;">1520 (2020)</td>
</tr>
</tbody>
</table>
<p><em>Table 1.3 (partial): Specific Heats of Various Substances.</em> <em>(Values in parentheses for gases are at constant pressure.)</em></p>
</section>
<section id="example-heating-a-pan-of-water" class="slide level2 scrollable">
<h2>Example: Heating a Pan of Water</h2>
<p><strong>Problem:</strong> A 0.500-kg aluminum pan and 0.250 L of water in it are heated from 20.0°C to 80.0°C.</p>
<ol type="a">
<li>How much heat is required?</li>
<li>What percentage of the heat is used to raise the temperature of the pan and the water?</li>
</ol>
<p><strong>Knowns:</strong> - <span class="math inline">\(m_{Al} = 0.500 \text{ kg}\)</span>, <span class="math inline">\(c_{Al} = 900 \text{ J/(kg}\cdot^\circ\text{C})\)</span> - <span class="math inline">\(V_W = 0.250 \text{ L} \implies m_W = 0.250 \text{ kg}\)</span> (since density of water is 1 kg/L) - <span class="math inline">\(c_W = 4186 \text{ J/(kg}\cdot^\circ\text{C})\)</span> - <span class="math inline">\(\Delta T = 80.0^\circ\text{C} - 20.0^\circ\text{C} = 60.0^\circ\text{C}\)</span></p>
<p><strong>Solution:</strong></p>
<ol type="1">
<li>Heat to water: <span class="math inline">\(Q_W = m_W c_W \Delta T = (0.250 \text{ kg})(4186 \text{ J/(kg}\cdot^\circ\text{C}))(60.0^\circ\text{C}) = 62.8 \text{ kJ}\)</span>.</li>
<li>Heat to aluminum: <span class="math inline">\(Q_{Al} = m_{Al} c_{Al} \Delta T = (0.500 \text{ kg})(900 \text{ J/(kg}\cdot^\circ\text{C}))(60.0^\circ\text{C}) = 27.0 \text{ kJ}\)</span>.</li>
<li>Total heat: <span class="math inline">\(Q_{Total} = Q_W + Q_{Al} = 62.8 \text{ kJ} + 27.0 \text{ kJ} = 89.8 \text{ kJ}\)</span>.</li>
</ol>
<p><strong>Percentages:</strong></p>
<ol start="2" type="a">
<li>Pan: <span class="math inline">\((27.0 \text{ kJ} / 89.8 \text{ kJ}) \times 100\% = 30.1\%\)</span>.</li>
<li>Water: <span class="math inline">\((62.8 \text{ kJ} / 89.8 \text{ kJ}) \times 100\% = 69.9\%\)</span>.</li>
</ol>
</section>
<section id="calorimetry" class="slide level2">
<h2>Calorimetry</h2>
<p><strong>Calorimetry</strong> is the use of a calorimeter (a container preventing heat transfer with surroundings) to measure heat.</p>
<p>For objects thermally isolated from their surroundings: - Heat gained by colder objects = Heat lost by hotter objects. - This is based on the conservation of energy.</p>
<p><span class="math display">\[Q_{hot} + Q_{cold} = 0\]</span></p>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>When solving calorimetry problems, set the sum of all heat transfers within the isolated system to zero. Remember that heat gained is positive, and heat lost is negative.</p>
</div>
</div>
</div>
</section>
<section id="phase-changes" class="slide level2">
<h2>1.5 Phase Changes</h2>
<h3 id="learning-objectives-4">Learning Objectives</h3>
<p>By the end of this section, you will be able to:</p>
<ul>
<li>Describe phase transitions and equilibrium between phases</li>
<li>Solve problems involving latent heat</li>
<li>Solve calorimetry problems involving phase changes</li>
</ul>
</section>
<section id="phase-transitions" class="slide level2">
<h2>Phase Transitions</h2>
<p>A <strong>phase transition</strong> is a change from one state of matter to another.</p>
<ul>
<li><strong>Melting (fusion):</strong> Solid <span class="math inline">\(\to\)</span> Liquid (opposite: freezing)</li>
<li><strong>Evaporation (vaporization):</strong> Liquid <span class="math inline">\(\to\)</span> Gas (opposite: condensation)</li>
<li><strong>Sublimation:</strong> Solid <span class="math inline">\(\to\)</span> Gas (opposite: deposition)</li>
</ul>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/b003195ec8d6ce438dce6dae769dea49e28af689" height="300"></p>
<p><em>Figure 1.13: Dry ice subliming (left) and frost forming (right).</em></p>
<aside class="notes">
<p>Phase transitions are common and crucial processes. They occur at specific temperatures and pressures, known as melting points and boiling points, respectively. These points can vary with pressure. Sublimation is a less common but interesting phase change where a solid directly turns into a gas, like dry ice.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="phase-diagrams" class="slide level2">
<h2>Phase Diagrams</h2>
<p>A <strong>phase diagram</strong> is a <em>pT</em> graph showing the phase of a substance at different pressures and temperatures.</p>
<ul>
<li><strong>Triple point:</strong> Unique combination of temperature and pressure where solid, liquid, and gas phases coexist in equilibrium.</li>
<li><strong>Critical point:</strong> Temperature and pressure above which liquid and gas phases cannot be distinguished (supercritical fluid).</li>
</ul>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/d7998f89d43369bd070ef145ffd459f3d5a88fdd" height="500"></p>
<p><em>Figure 1.12: Phase diagram for water.</em></p>
<aside class="notes">
<p>Phase diagrams are powerful tools for visualizing the conditions under which a substance exists in different phases. For water, the phase diagram shows its unique negative slope for the melting curve, meaning increasing pressure can melt ice. The triple point is a very precise and stable reference point for temperature calibration. Beyond the critical point, the distinction between liquid and gas vanishes, leading to exotic properties of supercritical fluids.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="equilibrium-during-phase-changes" class="slide level2">
<h2>Equilibrium during Phase Changes</h2>
<p>At a phase transition temperature (e.g., melting point, boiling point), phases coexist in equilibrium.</p>
<ul>
<li>Adding heat causes more of one phase; removing heat causes more of the other.</li>
<li><strong>Vapor pressure:</strong> The equilibrium pressure of a gas above its liquid at a given temperature in a closed container.
<ul>
<li>Boiling occurs when vapor pressure equals ambient pressure.</li>
</ul></li>
</ul>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/5c7e33fc516662fd50edc298951bce8154a26609" height="300"></p>
<p><em>Figure 1.14: Liquid-gas equilibrium at different boiling points.</em></p>
<aside class="notes">
<p>During a phase change, the system is in equilibrium, meaning the rates of forward and reverse processes are equal. For example, at the boiling point, molecules are evaporating and condensing at the same rate. This is why temperature remains constant during a phase change even as heat is added or removed. The concept of vapor pressure is crucial for understanding evaporation and boiling.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="latent-heat" class="slide level2">
<h2>Latent Heat</h2>
<p>During a phase change, heat transfer occurs <em>without</em> changing the temperature.</p>
<ul>
<li>This energy is used to break or form molecular bonds.</li>
<li><strong>Latent heat:</strong> The energy per unit mass involved in a phase change.</li>
</ul>
<p><span class="math display">\[Q = mL_f \quad \text{(melting/freezing)}\]</span> <span class="math display">\[Q = mL_v \quad \text{(vaporization/condensation)}\]</span></p>
<ul>
<li><span class="math inline">\(L_f\)</span> is the <strong>latent heat of fusion</strong>.</li>
<li><span class="math inline">\(L_v\)</span> is the <strong>latent heat of vaporization</strong>.</li>
</ul>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/30a4474a953a1c0aba667f301d05a4844c88cea8" height="300"></p>
<p><em>Figure 1.15: Temperature vs.&nbsp;heat added for water, showing latent heat regions.</em></p>
<aside class="notes">
<p>Latent heats are “hidden” because they don’t cause a temperature change. Instead, they facilitate the rearrangement of molecules, either breaking them apart (melting, vaporization) or allowing them to come closer together (freezing, condensation). These values are specific to each substance and are typically much larger than specific heats, indicating that significant energy is involved in changing phases. This property is exploited in applications like preventing frost damage to fruit by spraying water.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="heats-of-fusion-and-vaporization" class="slide level2">
<h2>Heats of Fusion and Vaporization</h2>
<table class="caption-top">
<colgroup>
<col style="width: 13%">
<col style="width: 25%">
<col style="width: 18%">
<col style="width: 25%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Substance</th>
<th style="text-align: left;">Melting Point (°C)</th>
<th style="text-align: left;"><span class="math inline">\(L_f\)</span> (kJ/kg)</th>
<th style="text-align: left;">Boiling Point (°C)</th>
<th style="text-align: left;"><span class="math inline">\(L_v\)</span> (kJ/kg)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Water</td>
<td style="text-align: left;">0.00</td>
<td style="text-align: left;">334</td>
<td style="text-align: left;">100.0</td>
<td style="text-align: left;">2256</td>
</tr>
<tr class="even">
<td style="text-align: left;">Aluminum</td>
<td style="text-align: left;">660</td>
<td style="text-align: left;">380</td>
<td style="text-align: left;">2450</td>
<td style="text-align: left;">11400</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ethanol</td>
<td style="text-align: left;">–114</td>
<td style="text-align: left;">104</td>
<td style="text-align: left;">78.3</td>
<td style="text-align: left;">854</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mercury</td>
<td style="text-align: left;">–38.9</td>
<td style="text-align: left;">11.8</td>
<td style="text-align: left;">357</td>
<td style="text-align: left;">272</td>
</tr>
</tbody>
</table>
<p><em>Table 1.4 (partial): Heats of Fusion and Vaporization.</em></p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Notice that <span class="math inline">\(L_v\)</span> is generally much larger than <span class="math inline">\(L_f\)</span>, meaning more energy is required to turn a liquid into a gas than a solid into a liquid. This is because molecules are completely separated in the gas phase.</p>
</div>
</div>
</div>
</section>
<section id="example-chilling-soda-with-ice" class="slide level2">
<h2>Example: Chilling Soda with Ice</h2>
<p><strong>Problem:</strong> Three ice cubes (6.0 g each, at 0°C) are added to 0.250 kg of 20°C soda. Assuming no heat loss to surroundings and soda has water’s specific heat. Find the final temperature when all ice has melted.</p>
<p><strong>Knowns:</strong></p>
<ul>
<li><span class="math inline">\(m_{ice} = 3 \times 0.006 \text{ kg} = 0.018 \text{ kg}\)</span></li>
<li><span class="math inline">\(T_{ice, initial} = 0^\circ\text{C}\)</span></li>
<li><span class="math inline">\(L_f = 334 \text{ kJ/kg} = 334 \times 10^3 \text{ J/kg}\)</span> (for water/ice)</li>
<li><span class="math inline">\(m_{soda} = 0.250 \text{ kg}\)</span></li>
<li><span class="math inline">\(T_{soda, initial} = 20^\circ\text{C}\)</span></li>
<li><span class="math inline">\(c_W = 4186 \text{ J/(kg}\cdot^\circ\text{C})\)</span> (for soda)</li>
</ul>
<p><strong>Strategy:</strong> Use calorimetry: <span class="math inline">\(Q_{ice} + Q_{soda} = 0\)</span>.</p>
<p><span class="math inline">\(Q_{ice} = \text{heat to melt ice} + \text{heat to warm melted ice}\)</span></p>
<p><span class="math inline">\(Q_{ice} = m_{ice} L_f + m_{ice} c_W (T_f - 0^\circ\text{C})\)</span></p>
<p><span class="math inline">\(Q_{soda} = m_{soda} c_W (T_f - 20^\circ\text{C})\)</span></p>
<p><strong>Solution:</strong></p>
<p><span class="math inline">\(m_{ice} L_f + m_{ice} c_W T_f + m_{soda} c_W (T_f - 20^\circ\text{C}) = 0\)</span></p>
<p>Solve for <span class="math inline">\(T_f\)</span>:</p>
<p><span class="math inline">\(T_f = \frac{m_{soda} c_W (20^\circ\text{C}) - m_{ice} L_f}{(m_{soda} + m_{ice}) c_W}\)</span></p>
<p><span class="math inline">\(T_f = \frac{(0.250 \text{ kg})(4186 \text{ J/kg}\cdot^\circ\text{C})(20^\circ\text{C}) - (0.018 \text{ kg})(334 \times 10^3 \text{ J/kg})}{(0.250 \text{ kg} + 0.018 \text{ kg})(4186 \text{ J/kg}\cdot^\circ\text{C})}\)</span></p>
<p><span class="math inline">\(T_f = \frac{20930 \text{ J} - 6012 \text{ J}}{(0.268 \text{ kg})(4186 \text{ J/kg}\cdot^\circ\text{C})} = \frac{14918 \text{ J}}{1122.08 \text{ J}/^\circ\text{C}} \approx 13^\circ\text{C}\)</span></p>
</section>
<section id="mechanisms-of-heat-transfer" class="slide level2">
<h2>1.6 Mechanisms of Heat Transfer</h2>
<h3 id="learning-objectives-5">Learning Objectives</h3>
<p>By the end of this section, you will be able to:</p>
<ul>
<li>Explain some phenomena that involve conductive, convective, and radiative heat transfer</li>
<li>Solve problems on the relationships between heat transfer, time, and rate of heat transfer</li>
<li>Solve problems using the formulas for conduction and radiation</li>
</ul>
</section>
<section id="three-mechanisms-of-heat-transfer" class="slide level2 scrollable">
<h2>Three Mechanisms of Heat Transfer</h2>
<p>Whenever there is a temperature difference, heat transfer occurs by one or more of these methods:</p>
<ol type="1">
<li><strong>Conduction:</strong> Heat transfer through stationary matter by physical contact.</li>
<li><strong>Convection:</strong> Heat transfer by the macroscopic movement of a fluid (liquid or gas).</li>
<li><strong>Radiation:</strong> Heat transfer by emission or absorption of electromagnetic radiation.</li>
</ol>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/288e9977cde196dca1f7ed805005c72492598490" height="350"></p>
<p><em>Figure 1.19: All three heat transfer mechanisms around a fireplace.</em></p>
<aside class="notes">
<p>These three mechanisms cover all possible ways heat can transfer. It’s rare for only one mechanism to be active in a real-world scenario; usually, they act in combination. Understanding each mechanism individually is key to analyzing complex heat transfer situations. All three are driven by temperature differences, with faster transfer for larger differences.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="conduction" class="slide level2">
<h2>Conduction</h2>
<p>Heat transfer through direct physical contact.</p>
<ul>
<li>Occurs due to collisions between molecules, transferring kinetic energy.</li>
<li>Faster in materials with free electrons (metals).</li>
<li>Insulators are poor conductors (e.g., polystyrene foam, trapped air).</li>
</ul>
<p><strong>Rate of conductive heat transfer (<span class="math inline">\(P\)</span>):</strong> <span class="math display">\[P = \frac{kA(T_h - T_c)}{d}\]</span></p>
<ul>
<li><span class="math inline">\(k\)</span>: <strong>Thermal conductivity</strong> of the material (W/(m·°C)).</li>
<li><span class="math inline">\(A\)</span>: Cross-sectional area.</li>
<li><span class="math inline">\(T_h - T_c\)</span>: Temperature difference across the material.</li>
<li><span class="math inline">\(d\)</span>: Thickness of the material.</li>
</ul>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>The ratio <span class="math inline">\(d/k\)</span> is called the <strong>R factor</strong>, a measure of insulating ability. A larger R factor means better insulation.</p>
</div>
</div>
</div>
<aside class="notes">
<p>Conduction is the primary way heat moves through solids. Think about touching a hot metal spoon versus a wooden spoon. The metal spoon conducts heat much faster because of its free electrons. Thermal conductivity, ‘k’, is a measure of how good a material is at conducting heat. Insulators, like foam or air, have low ‘k’ values.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="thermal-conductivities" class="slide level2">
<h2>Thermal Conductivities</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Substance</th>
<th style="text-align: left;">Thermal Conductivity <span class="math inline">\(k\)</span> (W/m·°C)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Diamond</td>
<td style="text-align: left;">2000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Silver</td>
<td style="text-align: left;">420</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Copper</td>
<td style="text-align: left;">390</td>
</tr>
<tr class="even">
<td style="text-align: left;">Aluminum</td>
<td style="text-align: left;">220</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Steel</td>
<td style="text-align: left;">80</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ice</td>
<td style="text-align: left;">2.2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Glass (average)</td>
<td style="text-align: left;">0.84</td>
</tr>
<tr class="even">
<td style="text-align: left;">Water</td>
<td style="text-align: left;">0.6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Polystyrene foam</td>
<td style="text-align: left;">0.035</td>
</tr>
<tr class="even">
<td style="text-align: left;">Air</td>
<td style="text-align: left;">0.023</td>
</tr>
</tbody>
</table>
<p><em>Table 1.5 (partial): Thermal Conductivities of Common Substances.</em></p>
</section>
<section id="example-ice-melting-in-an-icebox" class="slide level2 scrollable">
<h2>Example: Ice Melting in an Icebox</h2>
<p><strong>Problem:</strong> A polystyrene foam icebox (total area <span class="math inline">\(0.950 \text{ m}^2\)</span>, thickness <span class="math inline">\(2.50 \text{ cm}\)</span>) contains ice, water, and canned beverages at 0°C. How much ice melts in one day if the icebox is in a car trunk at 35.0°C?</p>
<p><strong>Knowns:</strong></p>
<ul>
<li><span class="math inline">\(k = 0.035 \text{ W/(m}\cdot^\circ\text{C})\)</span> (polystyrene foam)</li>
<li><span class="math inline">\(A = 0.950 \text{ m}^2\)</span></li>
<li><span class="math inline">\(d = 2.50 \text{ cm} = 0.0250 \text{ m}\)</span></li>
<li><span class="math inline">\(T_c = 0^\circ\text{C}\)</span>, <span class="math inline">\(T_h = 35.0^\circ\text{C}\)</span></li>
<li><span class="math inline">\(t = 1 \text{ day} = 86,400 \text{ s}\)</span></li>
<li><span class="math inline">\(L_f = 334 \times 10^3 \text{ J/kg}\)</span> (for ice)</li>
</ul>
<p><strong>Strategy:</strong> 1. Calculate the rate of heat transfer (<span class="math inline">\(P\)</span>) by conduction. 2. Calculate the total heat transferred (<span class="math inline">\(Q = P \times t\)</span>). 3. Calculate the mass of ice melted (<span class="math inline">\(m = Q / L_f\)</span>).</p>
<p><strong>Solution:</strong></p>
<ol type="1">
<li><span class="math inline">\(P = \frac{kA(T_h - T_c)}{d} = \frac{(0.035 \text{ W/m}\cdot^\circ\text{C})(0.950 \text{ m}^2)(35.0^\circ\text{C})}{0.0250 \text{ m}} = 46.6 \text{ W}\)</span>.</li>
<li><span class="math inline">\(Q = (46.6 \text{ J/s})(86,400 \text{ s}) = 4.03 \times 10^6 \text{ J}\)</span>.</li>
<li><span class="math inline">\(m = \frac{4.03 \times 10^6 \text{ J}}{334 \times 10^3 \text{ J/kg}} = 12.1 \text{ kg}\)</span>.</li>
</ol>
<p><strong>Significance:</strong> About 12.1 kg (26.7 lbs) of ice melts in a day, which is a significant amount and shows the effectiveness of polystyrene foam as an insulator.</p>
</section>
<section id="convection" class="slide level2">
<h2>Convection</h2>
<p>Heat transfer by the macroscopic movement of a fluid.</p>
<ul>
<li><strong>Forced convection:</strong> Fluid movement driven by external means (fans, pumps).
<ul>
<li>E.g., car cooling system, blowing on hot food.</li>
</ul></li>
<li><strong>Natural (free) convection:</strong> Fluid movement driven by buoyant forces (hot fluid rises, cold fluid sinks).
<ul>
<li>E.g., hot air rising in a room, ocean currents.</li>
</ul></li>
</ul>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/fe224950e7a44b9798508a03a46e546f12f8314b" height="300"></p>
<p><em>Figure 1.25: Natural convection in a pot of boiling water.</em></p>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>Convection is typically more effective than conduction for heat transfer in fluids over macroscopic distances.</p>
</div>
</div>
</div>
<aside class="notes">
<p>Convection is how heat moves in liquids and gases. It’s responsible for many everyday phenomena and plays a huge role in weather patterns and ocean currents. The density changes due to temperature are what drive natural convection. Think of a radiator in a room: it heats the air, which rises, cools, and sinks, creating a circulation pattern.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="convection-with-phase-change" class="slide level2">
<h2>Convection with Phase Change</h2>
<p>Convection can be combined with phase changes for significant cooling or heating effects.</p>
<ul>
<li><strong>Evaporative cooling:</strong> When sweat evaporates from skin, it removes a large amount of heat (<span class="math inline">\(Q = mL_v\)</span>) from the body.
<ul>
<li>This is why sweating cools us down, even if the air temperature is high.</li>
</ul></li>
<li><strong>Cloud formation:</strong> Water vapor condensing into liquid droplets in the atmosphere releases latent heat, driving powerful weather systems like thunderheads and hurricanes.</li>
</ul>
<p><img src="https://openstax.org/apps/image-cdn/v1/f=webp/apps/archive/20250916.165151/resources/9b4b2131e7e490aa7da2b1ec21e4ee1a289d6719" height="300"></p>
<p><em>Figure 1.27: Cumulus clouds formed by convection and condensation.</em></p>
</section>
<section id="radiation" class="slide level2">
<h2>Radiation</h2>
<p>Heat transfer by emission or absorption of electromagnetic waves.</p>
<ul>
<li>No medium is required for radiation to propagate (e.g., Sun warms Earth through vacuum).</li>
<li>Hotter objects radiate more energy, especially at shorter wavelengths (e.g., from red to white hot).</li>
<li><strong>Emissivity (<span class="math inline">\(e\)</span>):</strong> A measure of an object’s ability to emit and absorb thermal radiation (0 to 1).
<ul>
<li>Black objects: good absorbers and emitters (<span class="math inline">\(e \approx 1\)</span>).</li>
<li>White/shiny objects: poor absorbers and emitters (<span class="math inline">\(e \approx 0\)</span>).</li>
</ul></li>
</ul>
<p><strong>Stefan-Boltzmann Law of Radiation:</strong> The net rate of heat transfer by radiation between an object (temperature <span class="math inline">\(T_1\)</span>, emissivity <span class="math inline">\(e\)</span>) and its surroundings (temperature <span class="math inline">\(T_2\)</span>) is:</p>
<p><span class="math display">\[P_{net} = \sigma A e (T_2^4 - T_1^4)\]</span></p>
<ul>
<li><span class="math inline">\(\sigma = 5.67 \times 10^{-8} \text{ J/(s}\cdot\text{m}^2\cdot\text{K}^4)\)</span> (Stefan-Boltzmann constant).</li>
<li><span class="math inline">\(A\)</span>: Surface area of the object.</li>
<li><span class="math inline">\(T_1, T_2\)</span>: Temperatures in Kelvins.</li>
</ul>
<aside class="notes">
<p>Radiation is unique because it doesn’t require direct contact or a fluid medium. It’s how the sun heats us. The Stefan-Boltzmann law shows a very strong dependence on temperature (to the fourth power!), which means even small temperature differences can lead to significant radiative heat transfer. Emissivity ‘e’ is also important: black surfaces absorb and emit radiation much more effectively than shiny or white surfaces.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="example-net-heat-transfer-of-a-person" class="slide level2">
<h2>Example: Net Heat Transfer of a Person</h2>
<p><strong>Problem:</strong> What is the rate of heat transfer by radiation of an unclothed person (<span class="math inline">\(A = 1.50 \text{ m}^2\)</span>, <span class="math inline">\(T_1 = 33.0^\circ\text{C}\)</span>) standing in a dark room (<span class="math inline">\(T_2 = 22.0^\circ\text{C}\)</span>)? The emissivity of skin is <span class="math inline">\(e = 0.97\)</span>.</p>
<p><strong>Strategy:</strong> Use the Stefan-Boltzmann law: <span class="math inline">\(P_{net} = \sigma A e (T_2^4 - T_1^4)\)</span>.</p>
<p><strong>Remember to convert temperatures to Kelvin!</strong></p>
<p><strong>Knowns:</strong> - <span class="math inline">\(\sigma = 5.67 \times 10^{-8} \text{ J/(s}\cdot\text{m}^2\cdot\text{K}^4)\)</span> - <span class="math inline">\(A = 1.50 \text{ m}^2\)</span> - <span class="math inline">\(e = 0.97\)</span> - <span class="math inline">\(T_1 = 33.0^\circ\text{C} + 273.15 = 306.15 \text{ K}\)</span> - <span class="math inline">\(T_2 = 22.0^\circ\text{C} + 273.15 = 295.15 \text{ K}\)</span></p>
<p><strong>Solution:</strong></p>
<p><span class="math inline">\(P_{net} = (5.67 \times 10^{-8})(1.50)(0.97) ((295.15)^4 - (306.15)^4)\)</span></p>
<p><span class="math inline">\(P_{net} = (8.24 \times 10^{-8}) (7.59 \times 10^9 - 8.76 \times 10^9)\)</span></p>
<p><span class="math inline">\(P_{net} = (8.24 \times 10^{-8}) (-1.17 \times 10^9)\)</span></p>
<p><span class="math inline">\(P_{net} \approx -96.3 \text{ W}\)</span></p>
<p><strong>Significance:</strong> The person loses about 96.3 W of heat to the environment through radiation. The negative sign indicates heat is leaving the person. This is a significant amount, suggesting the person would feel cold.</p>
</section>
<section id="key-takeaways" class="slide level2 scrollable">
<h2>Key Takeaways</h2>
<ol type="1">
<li><strong>Temperature and Heat:</strong> Temperature is a measure of average molecular kinetic energy, while heat is the transfer of thermal energy due to a temperature difference.</li>
<li><strong>Thermal Equilibrium &amp; Zeroth Law:</strong> Objects in thermal equilibrium have the same temperature, and the Zeroth Law allows for consistent temperature measurement.</li>
<li><strong>Temperature Scales:</strong> Fahrenheit, Celsius, and Kelvin (absolute scale) are used, with specific conversion formulas.</li>
<li><strong>Thermal Expansion:</strong> Most materials expand with increasing temperature (<span class="math inline">\(\Delta L = \alpha L \Delta T\)</span>, <span class="math inline">\(\Delta V = \beta V \Delta T\)</span>), with water being a notable exception (densest at 4°C).</li>
<li><strong>Heat Capacity &amp; Calorimetry:</strong> Specific heat (<span class="math inline">\(Q = mc\Delta T\)</span>) quantifies heat transfer for temperature changes; calorimetry uses energy conservation (<span class="math inline">\(Q_{hot} + Q_{cold} = 0\)</span>).</li>
<li><strong>Phase Changes &amp; Latent Heat:</strong> Heat transfer during phase changes occurs at constant temperature, using latent heats of fusion (<span class="math inline">\(L_f\)</span>) or vaporization (<span class="math inline">\(L_v\)</span>) (<span class="math inline">\(Q = mL\)</span>).</li>
<li><strong>Heat Transfer Mechanisms:</strong>
<ul>
<li><strong>Conduction:</strong> Direct contact (<span class="math inline">\(P = \frac{kA\Delta T}{d}\)</span>).</li>
<li><strong>Convection:</strong> Fluid movement.</li>
<li><strong>Radiation:</strong> Electromagnetic waves (<span class="math inline">\(P_{net} = \sigma A e (T_2^4 - T_1^4)\)</span>).</li>
</ul></li>
</ol>
</section>
<section id="key-equations" class="slide level2">
<h2>Key Equations</h2>
<table class="caption-top">
<colgroup>
<col style="width: 48%">
<col style="width: 51%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Equation</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(T_F = \frac{9}{5} T_C + 32\)</span></td>
<td style="text-align: left;">Celsius to Fahrenheit conversion</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(T_C = T_K - 273.15\)</span></td>
<td style="text-align: left;">Kelvin to Celsius conversion</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\Delta L = \alpha L \Delta T\)</span></td>
<td style="text-align: left;">Linear thermal expansion</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\Delta V = \beta V \Delta T\)</span></td>
<td style="text-align: left;">Volume thermal expansion</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(F/A = Y \alpha \Delta T\)</span></td>
<td style="text-align: left;">Thermal stress (fixed ends)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(Q = mc\Delta T\)</span></td>
<td style="text-align: left;">Heat transfer for temperature change</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(Q_{hot} + Q_{cold} = 0\)</span></td>
<td style="text-align: left;">Conservation of energy in calorimetry</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(Q = mL_f\)</span></td>
<td style="text-align: left;">Heat transfer for melting/freezing</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(Q = mL_v\)</span></td>
<td style="text-align: left;">Heat transfer for vaporization/condensation</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(P = \frac{kA(T_h - T_c)}{d}\)</span></td>
<td style="text-align: left;">Rate of heat transfer by conduction</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(P_{net} = \sigma A e (T_2^4 - T_1^4)\)</span></td>
<td style="text-align: left;">Net rate of heat transfer by radiation</td>
</tr>
</tbody>
</table>
</section>
<section id="key-terms" class="slide level2">
<h2>Key Terms</h2>
<table class="caption-top">
<colgroup>
<col style="width: 18%">
<col style="width: 81%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Term</th>
<th style="text-align: left;">Definition</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Temperature</strong></td>
<td style="text-align: left;">Quantity measured by a thermometer; proportional to average kinetic energy of molecular translation.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Heat Transfer</strong></td>
<td style="text-align: left;">Movement of energy due to a difference in temperature.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Thermal Equilibrium</strong></td>
<td style="text-align: left;">State where no net energy is transferred between objects in contact.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Zeroth Law of Thermodynamics</strong></td>
<td style="text-align: left;">If A is in equilibrium with B, and B with C, then A is in equilibrium with C.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Absolute Zero</strong></td>
<td style="text-align: left;">Lowest possible temperature where molecular kinetic energy is zero (0 K).</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Thermal Expansion</strong></td>
<td style="text-align: left;">Change in size or volume of a system due to temperature change.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Coefficient of Linear Expansion (<span class="math inline">\(\alpha\)</span>)</strong></td>
<td style="text-align: left;">Material property describing fractional change in length per degree Celsius or Kelvin.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Coefficient of Volume Expansion (<span class="math inline">\(\beta\)</span>)</strong></td>
<td style="text-align: left;">Material property describing fractional change in volume per degree Celsius or Kelvin.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Thermal Stress</strong></td>
<td style="text-align: left;">Stress created when an object is constrained from expanding or contracting due to temperature changes.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Internal Energy</strong></td>
<td style="text-align: left;">Sum of microscopic energies of a system.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Heat</strong></td>
<td style="text-align: left;">Energy transferred spontaneously due to a temperature difference.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Specific Heat (<span class="math inline">\(c\)</span>)</strong></td>
<td style="text-align: left;">Amount of heat needed to change the temperature of 1.00 kg of mass by 1.00°C (or 1.00 K).</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Calorimetry</strong></td>
<td style="text-align: left;">Measurement of heat transfer using a calorimeter.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Phase Transition</strong></td>
<td style="text-align: left;">Change of a substance from one state (solid, liquid, gas) to another.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Phase Diagram</strong></td>
<td style="text-align: left;">A <em>pT</em> graph showing the phases of a substance at different pressures and temperatures.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Triple Point</strong></td>
<td style="text-align: left;">Unique temperature and pressure where solid, liquid, and gas phases of a substance coexist in equilibrium.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Latent Heat (<span class="math inline">\(L\)</span>)</strong></td>
<td style="text-align: left;">Energy per unit mass required to change the phase of a substance at constant temperature.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Latent Heat of Fusion (<span class="math inline">\(L_f\)</span>)</strong></td>
<td style="text-align: left;">Energy per unit mass for melting/freezing.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Latent Heat of Vaporization (<span class="math inline">\(L_v\)</span>)</strong></td>
<td style="text-align: left;">Energy per unit mass for vaporization/condensation.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Conduction</strong></td>
<td style="text-align: left;">Heat transfer through stationary matter by physical contact.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Thermal Conductivity (<span class="math inline">\(k\)</span>)</strong></td>
<td style="text-align: left;">Material property indicating its ability to conduct heat.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Convection</strong></td>
<td style="text-align: left;">Heat transfer by the macroscopic movement of a fluid.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Radiation</strong></td>
<td style="text-align: left;">Heat transfer by the emission or absorption of electromagnetic waves.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Emissivity (<span class="math inline">\(e\)</span>)</strong></td>
<td style="text-align: left;">A measure of how effectively an object emits and absorbs thermal radiation (0 to 1).</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Stefan-Boltzmann Constant (<span class="math inline">\(\sigma\)</span>)</strong></td>
<td style="text-align: left;">Fundamental constant used in the Stefan-Boltzmann law of radiation.</td>
</tr>
</tbody>
</table>


<script type="ojs-module-contents">
eyJjb250ZW50cyI6W119
</script>
<div id="exercise-loading-indicator" class="exercise-loading-indicator d-none d-flex align-items-center gap-2">
<div id="exercise-loading-status" class="d-flex gap-2">

</div>
<div class="spinner-grow spinner-grow-sm">

</div>
</div>
<script type="vfs-file">
W10=
</script>
</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="../qrjs_pics/unsoed_logo.png" class="slide-logo"></p>
<div class="footer footer-default">
<p><a href="https://imron-slide.vercel.app">irosyadi-2025</a></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': false,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: true,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script type="ojs-module-contents">
    eyJjb250ZW50cyI6W119
    </script>
    <script type="module">
    if (window.location.protocol === "file:") { alert("The OJS runtime does not work with file:// URLs. Please use a web server to view this document."); }
    window._ojs.paths.runtimeToDoc = "../../book_2";
    window._ojs.paths.runtimeToRoot = "../..";
    window._ojs.paths.docToRoot = "..";
    window._ojs.selfContained = false;
    window._ojs.runtime.interpretFromScriptTags();
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>