--- 
title: "Signal and Systems"
author: "Imron Rosyadi"
format:
  live-revealjs:
    logo: "qrjs_assets/unsoed_logo.png"
    footer: "[irosyadi-2025](https://imron-slide.vercel.app)"
    slide-number: true
    chalkboard: true
    scrollable: true
    controls: true
    progress: true
    preview-links: false
    transition: fade
    incremental: false
    smaller: false
    theme: [default, qrjs_assets/ir_style.scss]
filters:
  - pyodide
---

## Slide 1

- Item 1
- Item 2
- Item 3

---

## Slide 2

- Item 2.1
- Item 2.2
- Item 2.3

---

## Multiple columns 

:::: {.columns}
::: {.column width="40%"}
**Left column**  

- Item L1
- Item L2 
:::
::: {.column width="60%"}
**Right column**  

- Item R1
- Item R2
- Item R3 
:::
::::

---

## Speaker Notes

Slide content  

- Item content 1
- Item content 2

::: {.notes}
Speaker notes go here. Hi I'm speaker notes.
:::

---

## Aside and Footnotes

This is aside and footnotes:

- Green ^[A footnote]
- Brown
- Purple

::: aside
Some additional commentary of more peripheral interest.
:::

--- 

## Code Block

```{.python code-line-numbers="|6-8|10"}
import numpy as np
import matplotlib.pyplot as plt

r = np.arange(0, 2, 0.01)
theta = 2 * np.pi * r
fig, ax = plt.subplots(subplot_kw={'projection': 'polar'})
ax.plot(theta, r)
ax.set_rticks([0.5, 1, 1.5, 2])
ax.grid(True)
plt.show()
```

---

## Slide Background {background-color="aquamarine"}

- Background ("#806040")
- Background ("black")

---

## {background-color="#806040"}

- Slide
- without title

---

::: {.panel-tabset}

### Tab A

Content for `Tab A`:  

- Item A.1
- Item A.2

### Tab B

Content for `Tab B`:

- Item B.1
- Item B.2
- Item B.3

:::

---

## IFrame {background-iframe="https://wikipedia.org"}

---

## Video {background-video="qrjs_present_asset/earth.mp4" background-video-loop="true" background-video-muted="true"}

This slides's background video will play in a loop with audio muted.

---

## Slide Title {background-color="black" background-image="https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Wikipedia-logo-v2.svg/1024px-Wikipedia-logo-v2.svg.png" background-size="300px"}

This slide's background image will be sized to 300px.

---

## Simple Latex

$e=mc^2$

---

## Block Latex

$$
e=mc^2
$$

---

## LaTeX Equations

[MathJax](https://www.mathjax.org/) rendering of equations to HTML

::: columns
::: {.column width="40%"}
``` tex
\begin{gather*}
a_1=b_1+c_1\\
a_2=b_2+c_2-d_2+e_2
\end{gather*}

\begin{align}
a_{11}& =b_{11}&
  a_{12}& =b_{12}\\
a_{21}& =b_{21}&
  a_{22}& =b_{22}+c_{22}
\end{align}
```
:::

::: {.column width="60%"}
```{=tex}
\begin{gather*}
a_1=b_1+c_1\\
a_2=b_2+c_2-d_2+e_2
\end{gather*}
```
```{=tex}
\begin{align}
a_{11}& =b_{11}&
  a_{12}& =b_{12}\\
a_{21}& =b_{21}&
  a_{22}& =b_{22}+c_{22}
\end{align}
```
:::
:::

---

## Interactive

```{pyodide}
for x in range(5):
  print(x ** 2)
```
