---
title: "Aljabar Linear"
subtitle: "Rencana Pembelajaran Semester"
author: "Imron Rosyadi"
format:
  live-revealjs:
    logo: "qrjs_assets/unsoed_logo.png"
    footer: "[irosyadi-2025](https://imron-slide.vercel.app)"
    slide-number: true
    chalkboard: true
    scrollable: true
    controls: true
    progress: true
    preview-links: false
    transition: fade
    incremental: false
    smaller: false
    theme: [default, qrjs_assets/ir_style.scss]
filters:
  - pyodide
---

# Aljabar Linear

---

## Dosen Pengajar

1. Imron Rosyadi (kelas A)
2. Aisya Nur Aulia Yusuf (kelas B)
3. Norma Amalia (kelas C)
4. Yogi Ramadhani (kelas D)

---

## Jadwal, Kelas, Google Meet

- MK Aljabar Linear - Kelas A
- Lecturer: Imron Rosyadi
- Schedule: Monday, 13:00 – 15:40
- Room: GEDUNG TEKNIK E 203
- [Google Meet: meet.google.com/bqm-jnqt-yrw](https://meet.google.com/bqm-jnqt-yrw)

---

## Tautan Penting

- [Course Page: imron-course.vercel.app](https://imron-course.vercel.app/)
- [Presentation: imron-slide.vercel.app](https://imron-slide.vercel.app/)
- [Discussion: discord.gg/6nNTvfmz](https://discord.gg/6nNTvfmz), expired at 29 Aug 2025
- [Attendance: teraversa.unsoed.ac.id](https://teraversa.unsoed.ac.id/login)
- [Online Learning: eldiru.unsoed.ac.id](https://eldiru.unsoed.ac.id/)

---

## Metode Pembelajaran

- **English-Indonesia**: Salindia presentasi dalam bahasa Inggris, tetapi penyampaian menggunakan bahasa Indonesia.
- **Luring-Daring**: Pembelajaran dilakukan dengan tatap muka luring, tetapi diselingi secara daring. Cek Discord untuk informasi.
- **Visualisasi-Interaktif**: Pembelajaran akan menyediakan sumberdaya berupa visualisasi interaktif untuk memudahkan pemahaman. Cek berbagai link yang disediakan.
- **Case-based Approach**: Pembelajaran akan dikaitkan dengan topik bidang Electrical and Computer Engineering
- **Diskusi-Informasi via Discord**: Diskusikan materi, ajukan pertanyaan, langsung via Discord (channel #aljabar-linear-1).
- **Web-based Presentation**: Salindia presentasi berbentuk laman web, tetapi anda bisa mengekspornya ke PDF.
- **Review via Recording**: Sesi pembelajaran akan (diusahakan untuk) direkam dan diunggah ke Youtube


---

## Buku Referensi

- *Referensi Utama:* Anton, H., Rorres, C. (2013). Elementary Linear Algebra: Applications Version. John Wiley & Sons.
- *Referensi Pendukung:* Lay, D. C., Lay, S. R., McDonald, J. (2016). Linear Algebra and Its Applications. Pearson.

---

## Referensi Interaktif

### Interactive Linear Algebra Courses
- [TU Delft - Linear algebra](https://interactivetextbooks.tudelft.nl/linear-algebra/index.html)
- [UBC Newest- Interactive Linear Algebra](https://personal.math.ubc.ca/~tbjw/ila/)
- [Immersive Linear Algebra](https://immersivemath.com/ila/)

### Interactive Tools
- [Online Octave](https://octave-online.net/)
- [Calculator - GeoGebra](https://www.geogebra.org/calculator)

### Video Courses
- [Gilbert Strang: Linear Algebra](https://www.youtube.com/watch?v=YrHlHbtiSM0)

---

## Capaian Pembelajaran Lulusan (CPL)


*Capaian Pembelajaran Lulusan (CPL) yang Dibebankan:* 

Menguasai matematika, fisika, kimia dan statistik, teknologi informasi dan rekayasa sebagai landasan penerapan di bidang teknik elektro.

---

## Capaian Pembelajaran Mata Kuliah (CPMK) Aljabar Linear 1

- CPMK-1: Mahasiswa mampu menguasai penyelesaian sistem persamaan linear, melakukan operasi matriks dan menentukan determinan matriks, dan menerapkannya di bidang teknik elektro.
- CPMK-2: Mahasiswa mampu menguasai konsep vektor, operasi vektor, dan ruang vector dan menerapkannya di bidang teknik elektro.
- CPMK-3: Mahasiswa mampu menguasai konsep eigenvalue, eigenvector, transformasi linear, dan menerapkan aljabar linear di bidang teknik elektro.

---

## Rencana Pertemuan

**CPMK-1: Mahasiswa mampu menguasai penyelesaian sistem persamaan linear, melakukan operasi matriks dan menentukan determinan matriks, dan menerapkannya di bidang teknik elektro.**

- Pekan 1. Sistem Persamaan Linear dan Eliminasi Gauss-Jordan
- Pekan 2. Matriks dan Operasi Matriks 
- Pekan 3. Matriks dan Operasi Matriks (Determinan)
- Pekan 4. Aplikasi Sistem Persamaan Linear dan Matriks
- Pekan 5. Ujian Kompetensi CPMK 1 & Project-based Learning

---

## Rencana Pertemuan

**CPMK-2: Mahasiswa mampu menguasai konsep vektor, operasi vektor, dan ruang vector dan menerapkannya di bidang teknik elektro.**

- Pekan 6. Vektor di Ruang Euclidian
- Pekan 7. Vektor di Ruang Euclidian
- Pekan 8. Ruang Vektor Umum (Ruang Vektor, Sub Ruang)
- Pekan 9. Ruang Vektor Umum (Independensi Linear, Basis, Dimensi)
- Pekan 10. Ruang Vektor Umum (Rank, Nullity)
- Pekan 11. Ujian Kompetensi CPMK 2 (UTS)

---

## Rencana Pertemuan

**CPMK 3: Mahasiswa mampu menguasai konsep transformasi matriks, eigenvalue, eigenvector, dan menerapkan aljabar linear di bidang teknik elektro.**

- Pekan 12. Transformasi Matriks
- Pekan 13. Eigenvalue dan Eigenvector
- Pekan 14. Aplikasi Aljabar Linear
- Pekan 15. Aplikasi Aljabar Linear
- Pekan 16. Ujian Kompetensi CPMK 2 (UAS) & Laporan Project-based Learning
